### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by Granipouss** [chrisvfritz/prerender-spa-plugin#1]
Hi,

I'm using this plugin to prerender some pages of a vue project (built with [that template](https://github.com/soixantecircuits/nd)) with the following settings :
``` javascript
new PrerenderSpaPlugin(
    config.build.assetsRoot, // = "./dist"
    [ '/home', '/about', '/contact' ],
    {
        captureAfterTime: 5000,
        maxAttempts: 10,
        phantomOptions: '--disk-cache=true',
        phantomPageSettings: { loadImages: true }
    }
)
```

It creates the following files :
```
dist
 |-- static/
 |     |-- css/ ..
 |     +-- img/ ..
 |-- about/index.html
 +-- index.html
```
The issue is that ./dist/index.html requires files from ./dist/static/ and ./dist/about/index.html from ./dist/about/static/ which don't exist. Is there a way to have it requires from the root instead ?

**Comment by chrisvfritz** [comment]
For local file references in HTML, you just need to make sure that the asset paths are either root relative (e.g. `/static/my-image.jpg`) or absolute (e.g. `https://example.com/static/my-image.jpg`).

**Comment by Granipouss** [comment]
Thank you for the answer, I've set a public path to have all paths root relative.

**Comment by sjmlsxp** [comment]
root relative (e.g. /static/my-image.jpg). after build -> http://localhost:8011/static/my-image.jpg
how to fixed like '/static/my-image.jpg', not 'http://localhost:8011/static/my-image.jpg'
