### ISSUE TITLE
Syntax error after prerender.

### ISSUE THREAD

**Issue by vinsonyung** [chrisvfritz/prerender-spa-plugin#100]
Hi, thank you for such a great plugin. :)

I found syntax error in Facebook Pixel code after prerendered.

Original:
```js
  <script>
    ... skipped ...
  </script>
  <noscript>
    <img height="1" width="1" src="https://www.facebook.com/tr?id=xxxxxxxxxx&ev=PageView&noscript=1" />
  </noscript>
```

After:
```js
  <script>
    ... skipped ...
  </script>
<noscript>&lt;img height=1 width=1 src="https://www.facebook.com/tr?id=xxxxxxxxxx&amp;ev=PageView&amp;noscript=1"&gt;</noscript>
```

**Comment by drewlustro** [comment]
Looks like PhantomJS is rendering the contents of `<noscript>` verbatim, HTML entity escaped (of course).

You can avoid this by removing the original `<noscript>` block.
