### ISSUE TITLE
Problem with unsupported features in PhantomJS

### ISSUE THREAD

**Issue by santi-git** [chrisvfritz/prerender-spa-plugin#101]
I'm using prerender for a VueJS app made with the PWA template. I recently added a library which uses IntersectionObserver, which is not implemented for all browsers, I added the polyfill for those cases.
But in the build step prerender fails with this output:

```
/home/santiago/Projects/ubykuo-pwa/node_modules/prerender-spa-plugin/lib/compile-to-html.js:82
                    if (error) throw stdout
                               ^
WARNING: JavaScript error while prerendering: /
ReferenceError: Can't find variable: IntersectionObserver

  phantomjs://code/phantom-page-render.js:26 in onError
```

Is there anyway to include the polyfills for PhantomJS?

**Comment by drewlustro** [comment]
Honestly not sure how to address this, as PhantomJS has been sunset. It's tough to apply edge browser features to it.
