### ISSUE TITLE
Feature request. Compatibility with sitemap-webpack-plugin

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [chrisvfritz/prerender-spa-plugin#104]
It would be great if `prerender-spa-plugin` integrates with [sitemap-webpack-plugin](https://github.com/schneidmaster/sitemap-webpack-plugin), so we could easily pass generated paths to `sitemap-webpack-plugin`, instead of manually typing them.

Thank you!

**Comment by drewlustro** [comment]
Thanks for the suggestion!

I understand the value, but why considering that `sitemap-webpack-plugin` advertises compatibility with `static-site-generator-webpack-plugin` (which accomplishes something similar to this plugin).

**Comment by NoraGithub** [comment]
Would you please provide an example for this with `static-site-generator-webpack-plugin`? @drewlustro
