### ISSUE TITLE
Without webpack

### ISSUE THREAD

**Issue by tdwells90** [chrisvfritz/prerender-spa-plugin#106]
Hi,

Quick question, I wasn't sure whether to put it in here or tweet you so apologies if this is the wrong place...

Is it possible to use this package outside of webpack? I'm using Vue with meteor and was looking into prerendering options!

Thanks in advance.

Tom.

**Comment by ricricucit** [comment]
no, this is a webpack plugin.

**Comment by drewlustro** [comment]
@ricricucit thanks for chiming in.
