### ISSUE TITLE
Style attribute binding gets overridden by pre-rendering

### ISSUE THREAD

**Issue by ricricucit** [chrisvfritz/prerender-spa-plugin#107]
I build a simple "parallax" using [vuejs style binding](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax-1) `:style` and I found out that the prerender-spa-plugin executed  phantomjs, which added static inline styles (eg. `style="-webkit-transform: translateY(0px);"`) which, once generated, overrides the actual style-binding of the app.

For this reason I would _maybe_ propose the possibility of skipping inline-style attributes when pre-rendering the application...would that be easy to implement, or: does someone could point me towards a (good) solution to work around this issue?

**Comment by drewlustro** [comment]
**Great idea!**

I'm currently working on an adaptor of this that employs _Chrome Headless_ via puppeteer instead of phantomJS, so we'll soon have more robust API's as that matures.

--- 

In terms of what you can do right now to solve this issue, consider using `options.postProcessHtml` by providing regex to strip out applicable:

```html
<div class="foo" style="transform: translate3d(0, 0, 1);"> ... </div>
<!-- ➡️  -->
<div class="foo">... </div>
```

`webpack.config.js`

```jsx
// Manually transform the HTML for each page after prerendering,
// for example to set the page title and metadata in edge cases
// where you cannot handle this via your routing solution.
//
// The function's context argument contains two properties:
//
// - html :: the resulting HTML after prerendering)
// - route :: the route currently being processed
//            e.g. "/", "/about", or "/contact")
//
// Whatever is returned will be printed to the prerendered file.
postProcessHtml: function (context) {
  var titles = {
    '/': 'Home',
    '/about': 'Our Story',
    '/contact': 'Contact Us'
  }
  return context.html.replace(
    /<title>[^<]*<\/title>/i,
    '<title>' + titles[context.route] + '</title>'
  )
}
```

Hope that helps. Cheers.

**Comment by ricricucit** [comment]
sounds good, thanks for the tip!

**Comment by ricricucit** [comment]
@drewlustro I'm not 100% sure yet, but this seems to be a problem for [`router link`](https://router.vuejs.org/en/api/router-link.html) as well. Seems to be rendered as regular URL and not getting picked up by the vue-router...

**Comment by drewlustro** [comment]
What is problematic? This plugin is supposed to render static, vanilla HTML.

`router link` is a custom element defined by `vue-router`. Thus, it would not (and should not) prerender as anything but an ordinary `<a>` link.

**Comment by ricricucit** [comment]
no, sorry, I'm not sure I should be the one to close this 😛
