### ISSUE TITLE
Compatibility with html-webpack-plugin

### ISSUE THREAD

**Issue by lyzs90** [chrisvfritz/prerender-spa-plugin#108]
node: 8.1.2
webpack:  3.6.0
html-webpack-plugin: 2.30.1
prerender-spa-plugin: 2.1.0

=====

I have a VueJs app which i'm trying to prerender, but seem to have trouble getting both plugins to play nice with each other.

This is my project structure:
```
index.html
dist
|__ js
     |__ main.min.js
```

I'm using **html-webpack-plugin** first to move `index.html` into `/dist` and to insert the script tags, then 
 **prerender-spa-plugin** on the `/` route.

I logged the `prerenderedHTML` variable in `index.js` of **prerender-spa-plugin**  and it shows:
```html
<html>
  <head></head>
  <body>
    <pre style="word-wrap: break-word; white-space: pre-wrap;">{"statusCode":404,"error":"Not Found"}
    </pre>
  </body>
</html>
```

However, it leaves me with a `index.html` with correctly appended script tags.

Trying to run webpack a second time (without clearing out `/dist`). Logs the nicely prerendered `index.html`, but again **prerender-spa-plugin** somehow doesnt write to the file.

The puzzling thing is, if I remove the **html-webpack-plugin** portion from config and run webpack a third time (again without clearing out `/dist`), i finally get my nicely prerendered `index.html` . 

Here's my plugin config for reference:
```javascript
plugins: [
  // other plugins,
  new HtmlWebpackPlugin({
     template: path.resolve('index.html'),
     filename: path.resolve('dist/index.html'),
  }),
  new PrerenderSpaPlugin(
    path.resolve('dist'),
    ['/'],
    {
       captureAfterTime: 5000,
    },
]
```
If necessary, i'll get a minimal repro up tomorrow. Cheers, appreciate the help (:

**Comment by drewlustro** [comment]
Perhaps it's having trouble resolving `filename` or the absolute path:

```js
plugins: [
  // other plugins,
  new HtmlWebpackPlugin({
     template: 'index.html', // worth a try, but probably no effect
     filename: path.resolve(__dirname, 'dist/index.html'), // worth a try
  }),
  new PrerenderSpaPlugin(
    path.resolve(__dirname, './dist'), // worth a try
    ['/'],
    {
       captureAfterTime: 5000,
    },
]
```

**Comment by lyzs90** [comment]
@drewlustro thanks ill give it a shot and let you know how it goes

**Comment by lyzs90** [comment]
managed to get it to work.  i had to modify **prerender-spa-plugin** to use the complier's `done` hook instead of `after-emit`. and also remove the `done()` callback. but not sure if this is the best solution...

i think the problem is because `index.html` is only written by **html-webpack-plugin** during the `after-emit` hook (it assigns to `compilation.assets[file]`). however, **prerender-spa-plugin** also hooks onto `after-emit` and expects an `index.html` furnished with script tags.

**Comment by drewlustro** [comment]
Bizaare. It sounds like `prerender-spa-plugin` is reading from your `dist/index.html` if you're getting differing changes after every run.
