### ISSUE TITLE
Prerender Vue.js routes separate from build process

### ISSUE THREAD

**Issue by MattPurland** [chrisvfritz/prerender-spa-plugin#111]
Hi,

Not so much as an issue but more a request for help. I'm currently using this plugin in a Vue.js app, and it works perfectly. What I'd like to know is is it possible to build the prerender routes without completely building the app? So instead of running 'npm run build', I could run 'npm run prerender' and just prerender the routes?

Many thanks!

**Comment by lyzs90** [comment]
u do mean a separate webpack config file just to do the prerendering? then run it via `webpack --config prerender.config.js`

**Comment by drewlustro** [comment]
Yes; @lyzs90 is right.

A separate webpack config that simply operates on your `build/` or `dist/` directory would work ✅ .

Closing. Feel free to comment here if you have more troubleshooting questions.
