### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by Leshgan** [chrisvfritz/prerender-spa-plugin#112]
Hi.
I'm compiling vue.js spa. Plugin worked well, but one day I got this
/node_modules/prerender-spa-plugin/lib/compile-to-html.js:82
                    if (error) throw stdout
                               ^
WARNING: JavaScript error while prerendering: /
TypeError: undefined is not an object (evaluating 'e.item.name')

  phantomjs://code/phantom-page-render.js:26 in onError

Please help.

**Comment by tonywangcn** [comment]
did you solve this?

**Comment by Leshgan** [comment]
Yes. There was empty object in loop. Pay attention
