### ISSUE TITLE
CDN Support

### ISSUE THREAD

**Issue by dsanders11** [chrisvfritz/prerender-spa-plugin#114]
Is there any hope of this ever working with CDNs? Sometimes it seems the entire webpack ecosystem is built in a world where CDNs aren't a thing...

If the generated `index.html` has absolute links for use with a CDN, say, the HTML is served from `www.example.com` and the assets are served from `static.example.com`, pre-rendering will fail because the assets are not actually on the CDN yet during the build process. You'd have to pre-render *after* deploying, so you'd end up with a two-stage deployment. Perhaps a separate build target that uses relative URLs instead of the CDN ones so that everything is available during build?

Is there a solution I'm overlooking?

**Comment by drewlustro** [comment]
If the URL's are the same, why would pre-rendering "fail"?

Worst-case scenario I could think of is you have some broken URL's upon pre-render (which are cosmetic), but then when you actually deploy the assets work.

What cannot be accomplished by some simple domain/subdomain regex find+replace with the `postProcessHtml` option?

---

If I am mistaken, could you please elaborate on your build system + CDN setup?

**Comment by chanyying** [comment]
@drewlustro 

Yes, I have the same problem, `assetsPublicPath` Using the CDN URL，but，index.html Don't use

**Comment by dsanders11** [comment]
> If the URL's are the same, why would pre-rendering "fail"?

Because the files don't exist on `static.example.com`. The build, and pre-rendering, occurs long before the files are deployed.

> Worst-case scenario I could think of is you have some broken URL's upon pre-render (which are cosmetic), but then when you actually deploy the assets work.

Nothing gets pre-rendered. Those broken URLs are to the JavaScript which modifies the DOM. If the links are broken then the JavaScript never executes so you haven't actually accomplished anything, all you've done is render index.html which is essentially a no-op.

> What cannot be accomplished by some simple domain/subdomain regex find+replace with the postProcessHtml option?

The CDN domain is also baked into the Webpack manifest.

**Comment by drewlustro** [comment]
**A 2-step deploy is not uncommon.**

At some point, we all have to write some code instead of assuming that there will be a plugin (or option for said plugin) to handle every project need.

Why not create a new task like `npm run prebuild` that creates all of your assets and uploads them to `static.example.com` as a prerequisite to `npm run build`?

#### package.json (hypothetical snippet)

```jsx
{
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "prebuild": "node build/prebuild.js && rsync -r dist/static/* example.com:/sites/example/static",
    "build": "npm run prebuild && node build/build.js",
  }
}
```

**Comment by Dhgan** [comment]
I use the `__webpack_public_path__` to solve this problem. we can set dynamically value of `__webpack_public_path__` by judge different environments at runtime. [https://webpack.js.org/concepts/output/#advanced](https://webpack.js.org/concepts/output/#advanced)

**Comment by krestaino** [comment]
@Dhgan, where do you put that? Have an example by any chance?

**Comment by Dhgan** [comment]
@krestaino You can look at this. [prerender-cdn-demo](https://github.com/Dhgan/prerender-cdn-demo)

**Comment by krestaino** [comment]
@Dhgan Fantastic, thanks a lot!

**Comment by lili21** [comment]
shouldn't be close.

**Comment by dunhuang** [comment]
I use a proxy server to proxy CDN requests to localhost itself during prerender process.

Of course you should add `127.0.0.1  ${cdn.com}`  to your `/etc/hosts`, and stop any local server who is listening to 80.

[https://github.com/dunhuang/prerender-cdn-vue-demo](https://github.com/dunhuang/prerender-cdn-vue-demo)

**Comment by arthabus** [comment]
[this comment](https://github.com/chrisvfritz/prerender-spa-plugin/issues/215#issuecomment-415942268) helped me, maybe it would be useful to someone else as well.

**Comment by dunhuang** [comment]
The plugin provides the solution, [prerender-spa-cdn-plugin](https://github.com/dunhuang/prerender-spa-cdn-plugin/blob/master/README.md).  
Example: [vue-cli3 with PUBLIC_PATH=//cdn.abcd.com](https://github.com/dunhuang/prerender-spa-cdn-plugin/tree/master/examples/vuecli3-cdn)

```
const PrerenderSpaCdnPlugin = require('prerender-spa-cdn-plugin')
// ...
new PrerenderSpaCdnPlugin({
  staticDir: path.join(__dirname, 'dist'),
  routes: ['/', '/about'],
  rendererOptions: {
    maxConcurrentRoutes: 1,
    injectProperty: '__PRERENDER_INJECTED',
    inject: {
      rendering: true
    }
  }
})
```

**Comment by bertms** [comment]
> The plugin provides the solution, [prerender-spa-cdn-plugin](https://github.com/dunhuang/prerender-spa-cdn-plugin/blob/master/README.md).
> Example: [vue-cli3 with PUBLIC_PATH=//cdn.abcd.com](https://github.com/dunhuang/prerender-spa-cdn-plugin/tree/master/examples/vuecli3-cdn)
> 
> ```
> const PrerenderSpaCdnPlugin = require('prerender-spa-cdn-plugin')
> // ...
> new PrerenderSpaCdnPlugin({
>   staticDir: path.join(__dirname, 'dist'),
>   routes: ['/', '/about'],
>   rendererOptions: {
>     maxConcurrentRoutes: 1,
>     injectProperty: '__PRERENDER_INJECTED',
>     inject: {
>       rendering: true
>     }
>   }
> })
> ```

The pre-rendered page of this plugin has no HTML content

`plugins.push(new prerenderSpaCdnPlugin({
                staticDir: path.join(__dirname, outputFolder + '/' + engineId),
                routes: projectConfig.seoPages,
                rendererOptions: {
                    maxConcurrentRoutes: 10,
                    injectProperty: '__PRERENDER_INJECTED',
                    inject: {
                        rendering: true
                    },
                }
            }));
`
