### ISSUE TITLE
Data from axios isn't rendered

### ISSUE THREAD

**Issue by iamdubx** [chrisvfritz/prerender-spa-plugin#115]
Hi. I have such setup

```js
mounted () {
    axios.get('/static/data.json')
      .then((res) => {
        this.fetched = res.data
      })
  }
```
```html
<div v-for="fetch in fetched">
      <h1>{{ fetch.title }}</h1>
      <p>{{ fetch.content }}</p>
      <img :src="fetch.image" alt="">
    </div>
```

When I run prerender with `webpack` template I got no axios data in rendered html file. 
How to fix it?

**Comment by wxsms** [comment]
https://github.com/chrisvfritz/prerender-spa-plugin#webpack-advanced

**Comment by drewlustro** [comment]
+1 to @wxsms; perhaps try a longer `captureAfterTime` and `console.log` out when axios' `get()` fires and when the `then()` runs. See if you can find out if both those are triggering upon prerender.

**Closing.** Feel free to ask additional Q's here.
