### ISSUE TITLE
Does not work with nested routes

### ISSUE THREAD

**Issue by Sandwell** [chrisvfritz/prerender-spa-plugin#117]
I'm a using Vue 2, Webpack, vue-router and Prerender Spa Plugin.

I'm facing an issue when I try to prerender my nested routes.

The plug-in works fine for the routes '/' and '/first-level'.
But when I add a nested routes '/first-level/second-level', the output html is the same as the  index.html for the '/' route.

Here is my webpack conf :
![](https://i.stack.imgur.com/3B46V.png)

And my routes config : 
![image](https://user-images.githubusercontent.com/13133191/32097234-1b6ad1aa-bb09-11e7-9643-7bd8389a05b2.png)

Does anyone encoutered the same issue ?

**Comment by bingex** [comment]
Hi @Sandwell ,
I had the same issue. 
What I did:
- changed mode to 'history' in Vue router config
- added publicPath: '/' to the output in Webpack config
Hope it will help you

**Comment by shijiezhou1** [comment]
You are not rendering unknown router.
