### ISSUE TITLE
Cannot prerender when I change 'assetPublicPath' in config/index.js via VUE CLI

### ISSUE THREAD

**Issue by saberneko** [chrisvfritz/prerender-spa-plugin#118]
Hello,
I generated my app from vue cli webpack template(vue 2.x) and using prerender-spa-plugin like this in webpack.prod.conf.js
```
 ....
var PrerenderSpaPlugin = require('prerender-spa-plugin');
 ....
 new PrerenderSpaPlugin(
      path.resolve(__dirname, '../dist'),
      ['/', '/products/1', '/products/2', '/products/3'],
      {}
    ),
 .....
```
I've already installed plugin in package.json.。

Now, I need to build app and put them to my server, so I set 'assetPublicPath' in config/index.js ' from default '/' to '/myappname/'. 
```
assetsPublicPath: '/myappname/',
```
but when I run 'npm run build'  it doesn't prerender. 

The index.html is built like this
```
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title><link href="/myappname/static/css/app.9967f1180b40a718a437899cf04a0b95.css" rel="stylesheet"></head><body><div id="app"></div><script type="text/javascript" src="/myappname/static/js/manifest.a3b5dd84941d8e757d86.js"></script><script type="text/javascript" src="/myappname/static/js/vendor.7a386700ac3af33aa6ef.js"></script><script type="text/javascript" src="/myappname/static/js/app.3bfdb3c0c794e663b235.js"></script></body></html>
```
When I deploy them to my server.(URL is http://XXX.com/vue-standardization). Nothing is rendered.

AND I find if I set 'assetPublicPath' to a default path '/'.
```
assetsPublicPath: '/',
```
 It can prerender. BUT js and css <script> src path in index.html will also change to '/static/js/app.....' & '/static/css/...'.  What I need here is '/myappname/static/js/app....'. 

The index.html is built like this
```
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title><link href="/static/css/app.da896b4b342541a977581467d55e2f70.css" rel="stylesheet"><script type="text/javascript" charset="utf-8" async="" src="/static/js/2.18817e3664fc7bfec08a.js"></script><script type="text/javascript" charset="utf-8" async="" src="/static/js/1.bd38a5bbc4e658905f4c.js"></script><style type="text/css">.wrapper[data-v-01e9ad39]{color:#4682b4}.home-head[data-v-01e9ad39],.wrapper[data-v-01e9ad39]{width:100%;height:200px;line-height:200px;text-align:center}.home-head[data-v-01e9ad39]{background:#4682b4;color:#fff}.home-title[data-v-01e9ad39]{color:inherit;font-weight:700;font-size:3em}......
(html which is rendered).....
<script type="text/javascript" src="/static/js/manifest.c0cc765c53274d00267e.js"></script><script type="text/javascript" src="/static/js/vendor.7a386700ac3af33aa6ef.js"></script><script type="text/javascript" src="/static/js/app.3bfdb3c0c794e663b235.js"></script></body></html>
```

**Comment by 2xAA** [comment]
I'm also having exactly the same issue. Nothing to add, just that when I set `assetsPublicPath` there is no prerendered HTML, just the HTML before the Vue app has mounted.

**Comment by G-Veigar** [comment]
I'm also having exactly the same issue too

**Comment by AGGGIN** [comment]
config.js
```
 build: {
    env: require('./prod.env'),
    index: path.resolve(__dirname, '../dist/app/index.html'),
    assetsRoot: path.resolve(__dirname, '../dist/app/'),
    assetsSubDirectory: 'app/assets',
    assetsPublicPath: '/',
    productionSourceMap: true,
    productionGzip: false,
    productionGzipExtensions: ['js', 'css'],
    bundleAnalyzerReport: process.env.npm_config_report
  }
```
router
```
new Router({
  base: process.env.NODE_ENV === 'production' ? '/app/' : config.dev.assetsPublicPath,
  routes: [....]
})
```

run build then put the `assets `folder out :-( ，has any better solution？

**Comment by Zeus-Iqd** [comment]
I'm also having exactly the same issue too

**Comment by SHERlocked93** [comment]
I'm also having the same issue too, and don't know how to do ...

**Comment by MattiasMartens** [comment]
Leaving this here in case it helps the next person.

I had what I think is the same issue, the plugin needed any src files the app relied on to have the same directory path, relative to the app, that they would have when being served on the server. So if I wanted my app to be at `/index.html` and my bundle to be at `public/main.js`, I would have to replicate that structure in my output directory.

I didn't want to do that so I instead worked around the limitation by removing the asset path from the webpack config, instead adding the path prefix back in to the output when prerender was done with it:

```
        context.html = context.html.replace(
          /src="(.*).js"/g,
          `src="${assetPath}$1.js"`
        );
```
