### ISSUE TITLE
It won't build with Docker

### ISSUE THREAD

**Issue by tsauvajon** [chrisvfritz/prerender-spa-plugin#120]
When adding the `prerender-spa-plugin` to an existing app following the Vue doc : https://vuejs-templates.github.io/webpack/prerender.html or when cloning this repo's examples, it can build both applications normally on my host (yarn 1.3.2, node 8.6.0) but not inside a container, with Docker.

I've tried the `node:latest` (9.0.0), `node:carbon-alpine` (8.9.0 on alpine), `node:carbon` and `node_boron` (6.11) images.
I ran the build with npm (v3 and v5) and yarn (1.2.1).
Nothing seems to make it work.

I also tried to give it my host's node_modules, or fetch them inside the container, nothing helped.

Here's the error thrown by the plugin:
``` bash
[...]/node_modules/prerender-spa-plugin/lib/compile-to-html.js:82
                    if (error) throw stdout
                               ^
```

Full log:
```
yarn run v1.2.1
$ node build/build.js
(node:26) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

/usr/src/app/node_modules/prerender-spa-plugin/lib/compile-to-html.js:82
                    if (error) throw stdout
                               ^

error Command failed with exit code 1.
```

The Dockerfile is extremely simple (and works without the `prerender-spa-plugin` for the same app:
```
FROM node:carbon-alpine

WORKDIR /usr/src/app
COPY . .

RUN yarn && yarn build
```

Reproduction:
Copy the above docker file and try to build the image `docker build -t app .`

**Comment by nekitk** [comment]
Solved this by using `node:carbon-wheezy` instead of `alpine`

Thanks to this discussion: https://github.com/marcbachmann/node-html-pdf/issues/233

**Comment by tsauvajon** [comment]
@nekitk Thanks I'll try when I have some spare time (and close the issue).

**Comment by marienfressinaud** [comment]
The point of using `alpine` is to keep images as light as possible. Using `wheezy` sounds more like a workaround than a real solution to me :(

**Comment by tsauvajon** [comment]
@marienfressinaud I guess you could always use a multipart Dockerfile, that would allow you to keep your final image light. Building the image would still require you to pull the `wheezy` image, though.

**Comment by marienfressinaud** [comment]
That would be an acceptable option (for me at least) but still a workaround though. I'll try to have a look some day but don't know when yet ^^'

**Comment by b12f** [comment]
This worked for us:

```
RUN apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
```
