### ISSUE TITLE
Can not find variable:webpackJsonp

### ISSUE THREAD

**Issue by huangche007** [chrisvfritz/prerender-spa-plugin#121]
When i use this plug and npm run build,it show can not find variable:webpackJsonp

you can see this:[http://img.blog.csdn.net/20171106155946162?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMDYyNDk4Ng==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast](http://img.blog.csdn.net/20171106155946162?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMDYyNDk4Ng==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

My Rout list just like this:
`const Index = resolve =>{
  require(['@/components/Index'],resolve);
};
export default [
    {
      path: '/',
      name: 'Index',
      component: Index,
      redirect: '/news',
    },
]`

**Comment by MacFly669** [comment]
Hi huangche007 !
Have you find a way  to solve it ? I'm facing at the same issue

**Comment by stereobooster** [comment]
[code-splitting](https://github.com/chrisvfritz/prerender-spa-plugin#code-splitting) issue by any chance?
