### ISSUE TITLE
Finish PuppeteerRenderer

### ISSUE THREAD

**Issue by Tribex** [chrisvfritz/prerender-spa-plugin#129]
Uses Google Chrome's [puppeteer](https://github.com/GoogleChrome/puppeteer) to render page instead of PhantomJS. This currently intended as the default renderer for `v3`.

The current version is functional, but not fully tested.

- [x] Test on Linux
- [x] Test on macOS
- [x] Test on Windows

I don't have easy access to a functional Windows or macOS dev environment at the moment, so if anyone could test on those platforms, that would be great.

**Comment by boris-graeff** [comment]
Tested on Linux :
First try with default renderer => body is empty, no generated HTML.
But it works fine with renderAfterTime option. :)

Thanks for you work, I can remove Intl polyfill !

**Comment by Tribex** [comment]
Yeah, you'll need to set one of the available "renderAfter..." options before it will render anything. Otherwise it just dumps the HTML to a file before the JS executes.

**Comment by stereobooster** [comment]
```js
 await page.goto(pageUrl, { waitUntil: "networkidle" });
```

Will solve all problems

(or `networkidle0`/`networkidle2` in case of puppeteer 0.13+)

**Comment by Tribex** [comment]
@stereobooster Ah, thanks for the tip! I'll have to take a look sometime.

**Comment by stereobooster** [comment]
This is just a beginning of a journey:
- you also need to make sure state of the form elements saved https://github.com/stereobooster/react-snap/issues/84
- CSS-in-JS solutions work https://github.com/stereobooster/react-snap/issues/76
- remove `blob:` URLs from HTML, because they don't make sense in generated HTML
- make sure to use `page.content()` to get `DOCTYPE` https://github.com/stereobooster/react-snap/pull/32

**Comment by Tribex** [comment]
@stereobooster Duly noted. Your project looks great, by the way. I'm not finding time to work on this yet, so it might be a while before I have anything useful over here.

**Comment by Tribex** [comment]
@stereobooster It would appear that `networkidle` is not the target we want here. Otherwise, if unnecessary external resources are being fetched repeatedly per-page, the render time would be significantly longer than needed. However, I suppose we could default to `networkidle0` if no other `renderAfter` options are set.

**Comment by stereobooster** [comment]
> Otherwise, if unnecessary external resources are being fetched repeatedly per-page
```js
    await page.setRequestInterception(true)
    page.on('request', request => {
      if (/* third party request*/) {
        // don't need to download those
        request.abort()
      }
    })
```

**Comment by stereobooster** [comment]
As of "Async snapshots" (term taken from https://github.com/geelen/react-snapshot/pull/30). I believe there are two good approaches here:

### `networkidle`

This is what `react-snap` uses. This technique is proved to be powerful enough to work in many cases without additional configuration. This is [built-in puppeteer functionality](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options) -  consider navigation to be finished when there are no more than 0 network connections for at least 500 ms.

### `renderComplete`

This idea was taken from [Rendertron](https://github.com/GoogleChrome/rendertron). The first call to `renderComplete` will disable default mechanism e.g. `networkidle` and prerenderer will start to wait for the second signal. It will be up to the user to implement when to call this function. Related: [react#1739](https://github.com/facebook/react/issues/1739), [react-transmit](https://github.com/RickWong/react-transmit)

**Comment by Tribex** [comment]
Hmm, interesting.
