### ISSUE TITLE
dynamic contents didn't show up in prerendered files

### ISSUE THREAD

**Issue by tonywangcn** [chrisvfritz/prerender-spa-plugin#134]
I thought 10000 ms is a long enough time to load from API. But When I checked index.html file, the data generated by some code shows below should be injected there.

Codes getting data from api:

Home component:
```
created: function () {
  this.$store.dispatch('loadBlogs') 
}
computed: {
  blogs () {
    return this.$store.getters.loadedBlogs
}
}

```
loadBlogs function in store/blog/index.js will send a "Get" request to api server and load blogs data into localstorage.  Then the blogs function in computed will get the data by loadedBlogs getter function.

In my understanding of prerender-spa-plugin, When building with npm run build, it will start a phantomjs headless browser to consume api data and render into html file.

Besides I didn't find any requests in API server while  the building process. 

So, where was I wrong? Is there some misunderstanding about this plugin?

Thanks!

```
webpack.base.config.js

  plugins: [
    new PrerenderSpaPlugin(
      // Absolute path to compiled SPA
      path.join(__dirname, '../dist'),
      // List of routes to prerender
      [ '/', '/blogs', '/blog/this-is-test'],
      {
        captureAfterTime: 10000
        // captureAfterDocumentEvent: 'render-done'
      }
    )
  ]
```

![image](https://user-images.githubusercontent.com/3056655/34034282-c33845f4-e1b8-11e7-9453-431e09182734.png)

**Comment by stereobooster** [comment]
> loadBlogs function in store/blog/index.js will send a "Get" request to api server

does it use absolute URL or relative? If it is relative path like `/api/blog_posts` it will not work because those requests will go to internal static server

```js
var Server = new Hapi.Server({
connections: {
  routes: {
    files: {
      relativeTo: staticDir
    }
  }
}
```

**Comment by tonywangcn** [comment]
@stereobooster Not so sure what's the relative path you mentioned. Where should I configure it? The Vue js app works well when "npm run dev", means that, nothing wrong with the backend api in my opinion, right? 

Fortunately, the plugin works well some days after that day without reasons. Perhaps some misconfiguration somewhere else.

**Comment by stereobooster** [comment]
> Fortunately, the plugin works well some days after that day without reasons. Perhaps some misconfiguration somewhere else.

Close issue then?
