### ISSUE TITLE
Pre-rendering failed with router

### ISSUE THREAD

**Issue by iMomen** [chrisvfritz/prerender-spa-plugin#137]
I'm trying to use pre-rendering but it's not working when I'm using the router dependency 

`
import Vue from 'vue'
import App from './App'
import router from './router'

/* eslint-disable no-new */
new Vue({
  el: '#app',
  replace: false,
  router,
  render: h => h(App)
})
`

When I remove 'router' it's working great
any hint ?

**Comment by cschweda** [comment]
Is it in 'history' mode -- the router?

https://router.vuejs.org/en/essentials/history-mode.html

```
const router = new VueRouter({
  mode: 'history',
  routes: [
    { path: '*', component: NotFoundComponent }
  ]
})
```

**Comment by iMomen** [comment]
It's working, it was an issue with other dependencies.
Closed
