### ISSUE TITLE
HTML files not minified

### ISSUE THREAD

**Issue by Felwin** [chrisvfritz/prerender-spa-plugin#138]
Using prerender-spa-plugin with vue-cli webpack, the generated HTML files are not minifed. 
Internal CSS (in the style tag) is "pretty".
Did I do something wrong or should I add a minifying step ?
My actual config is basic : 
```
new PrerenderSpaPlugin(
      path.join(__dirname, '../../public'),
      [ '/', '/imprimerie' ],
      {
        ignoreJSErrors: true,
        postProcessHtml: function (context) {
          return context.html.replace(
            /http:\/\/localhost:8000/gi, ''
          )
        }
      }
    )
```
Thank you for your help.

**Comment by renanbronchart** [comment]
I have the same problem

**Comment by Felwin** [comment]
I solve the issue adding a minifying step in the postProcessHtml with html-minifier option minifyCSS: true
