### ISSUE TITLE
Vue.js 2.5+ Webpack-simple with router, HTML pages 404 "Not Found"

### ISSUE THREAD

**Issue by glenngijsberts** [chrisvfritz/prerender-spa-plugin#139]
I am working with the webpack-simple preset and the vue-router and I try to prerender certain routes. For some weird reason, the content of the HTML files are:

```<html><head></head><body>{"statusCode":404,"error":"Not Found"}</body></html>```

I think maybe the router is the problem (Because it has a hash before the url) and tried something like this:

```
  plugins: [
    new PrerenderSpaPlugin(
      // Path to compiled app
      path.join(__dirname, 'dist'),
      // List of endpoints you wish to prerender
      ['/\#/', '/\#/analyseren']
    )
  ],
```

unfortunately I get a compile error on build. 

I saw there is a example but that version is a bit outdated since sccs in vue is not supported. Is there someone else with the same problem?

## edit

I came across this fix for removing the hashes. Still got the same error in my HTML.

**Comment by dw72** [comment]
The same problem here :(

**Comment by stereobooster** [comment]
From readme

> Only works with routing strategies using the HTML5 history API. No hash(bang) URLs.

**Comment by dw72** [comment]
This simple project for example...
[test-prerender.zip](https://github.com/chrisvfritz/prerender-spa-plugin/files/1608744/test-prerender.zip)

**Comment by stereobooster** [comment]
@dw72 you miss this part in webpack config

```js
new HtmlWebpackPlugin({
  template: 'index.html',
  filename: path.resolve(__dirname, 'dist/index.html')
}),
```

which is responsible for creating `index.html` in `dist` directory.

But I agree error message could be more user friendly.
