### ISSUE TITLE
Not rendering anything

### ISSUE THREAD

**Issue by ebisbe** [chrisvfritz/prerender-spa-plugin#141]
Hello, 
I've copied your simple prerender set up but it's not working as expected. I've added a few links /, /signup, /login and it generates the folder and index.html but when I check the content there's only 
```
<div id="app"></div>
```
in the body section. I've downloaded your example version and I see there some html code so I asume mi version is not working. I'm not sure what is causing this behavior but I'm using a template with service Workers ( PWA) .

Any help would be awesome.

**Comment by ebisbe** [comment]
Any idea @chrisvfritz ? Do you need any more information I asume. Can you tell me what do you need ?

**Comment by chrisvfritz** [comment]
It sounds like your page must be rendering asynchronously. You may want to try dispatching an event when Vue is mounted and telling the plugin to wait for that event.

**Comment by katiasmet** [comment]
The same problem here. When I render the files in a dist-folder, the files contain following html : 
```

**Comment by jamesAtcodeninja** [comment]
Any luck on this?

**Comment by ebisbe** [comment]
I've been a couple of hours with #122 #31 #25 but it's still not building anyting and the output has no errors. 
``` 
yarn run v1.3.2
$ node build/build.js
⠋ building for production...(node:6349) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
⠴ building for production...
Starting to optimize CSS...
Processing static/css/app.62d2c84967c0269b455fd2e519d2ea5c.css...
Processed static/css/app.62d2c84967c0269b455fd2e519d2ea5c.css, before: 1365, after: 947, ratio: 69.38%
⠧ building for production...Total precache size is about 2.41 MB for 7 resources.
⠴ building for production...
```


```
let root = new Vue({
  el: '#App',
  router,
  store,
  apolloProvider,
  components: { App },
  mounted() {
    console.log('mounted')
  },
  render: h => h(App)
})

document.addEventListener(() => {
  root.$mount('#App')
  document.dispatchEvent(new Event('vue-post-render'))
})
```

```
new PrerenderSpaPlugin(
      // Absolute path to compiled SPA
      path.join(__dirname, '../dist'),
      // List of routes to prerender
      ['/', '/login', '/signup'],
      {
        captureAfterDocumentEvent: 'vue-post-render',
      }
    )
```

**Comment by ebisbe** [comment]
When using the app I see that error
``` 
TypeError: Not enough arguments to EventTarget.addEventListener
```

**Comment by ebisbe** [comment]
With v3 version is working. I'll check if everything is fine.

**Comment by Tribex** [comment]
I'd love to help with the v2 bug, but I actually can't get v2 to install properly (PhantomJS error) on my computer. ._.

**Comment by ebisbe** [comment]
For me v3 is all what I needed. I just found that using Vuetify it imports all it's css inline. I'll try to figure out why is doint it.

**Comment by Tribex** [comment]
I'll go ahead and close this one now then. Hope you get everything worked out!
