### ISSUE TITLE
cause jsonp error after use pre-render

### ISSUE THREAD

**Issue by forzeny** [chrisvfritz/prerender-spa-plugin#142]
recently,I was used prerender-spa-plugin but caused error after used pre-render , and i do not know why caused this problem. how to solve this problem. 

the rep is [forzeny/Music-Player ](https://github.com/forzeny/Music-Player/tree/pre-render )

jsonp code is [code](https://github.com/forzeny/Music-Player/blob/23e788ec31e8251c248d5be57d585d9d69a1faa2/src/components/Recommend/index.vue#L69
)
![image](https://user-images.githubusercontent.com/18499153/34912928-1ca6c55c-f929-11e7-913f-f8270511cab4.png)

**Comment by forzeny** [comment]
i was pre-render a not exit router path '/' and remove this path solve this problem

**Comment by stereobooster** [comment]
From readme

> If you're using code splitting, visits to some prerendered pages might throw: Uncaught ReferenceError: webpackJsonp is not defined. That just means some asynchronous chunks that Webpack injects into <head> are being evaluated before your main scripts, often in <body>.

See https://github.com/chrisvfritz/prerender-spa-plugin#code-splitting

Does it help?

**Comment by forzeny** [comment]
@stereobooster can not jsonp error

**Comment by forzeny** [comment]
not solved but close issue
