### ISSUE TITLE
What is the correct way to add third party scripts?

### ISSUE THREAD

**Issue by namanyayg** [chrisvfritz/prerender-spa-plugin#143]
I've added some third party scripts to the bottom of my `index.html` (fb pixel, google analytics, etc); but pre-rendering with those scripts in place gives me an error.

What is the best way to include third party scripts here? I could move them to the `postProcessHtml` and remove them from `index.html`, but I need those scripts to appear for the rest of the pages -- just not on the few that I wish to prerender.

**Comment by stereobooster** [comment]
> but pre-rendering with those scripts in place gives me an error.

It would be helpful to see the error message and reproducible example.

**Comment by namanyayg** [comment]
I realized that my issue was due to an errant placing of `inject: 'head'` due to misunderstanding the 'Chunking' use-case.

I've written a [quick post about my config](https://symmetrycode.com/better-vue-seo-with-prerender-spa-plugin-and-vue-cli/). Do you think there's a better way that I could be doing things?

Closing.
