### ISSUE TITLE
Vue taking over of prerendered app

### ISSUE THREAD

**Issue by maximivanov** [chrisvfritz/prerender-spa-plugin#145]
Hey guys,

probably I'm missing something fundamental, please help figure out (I checked existing issues, #93 seems to be related but doesn't quite answer my question).

Consider this simple Vue component:

```
<template>
  <div id="app">
    <p v-for="post in posts">{{ post.title }}</p>
  </div>
</template>

<script>
  import axios from 'axios';

  export default {
    name: 'app',
    data () {
      return {
        posts: []
      }
    },
    mounted() {
      axios.get('https://api-to-get-posts')
        .then(response => {
          this.posts = response.data;
        })
    }
  }
</script>
```

I managed to prerender it (I can see a list of posts in resulting html). My question is regarding what happens once it's fetched and rendered by user or crawler.

**User:** even though posts are already in html, Vue will take over immediately after page dom loaded and reset posts list to []. Then it will query api and fill posts again. So user's experience is not much different from loading not prerendered Vue app (or even worse, depending on how fast their connection/device, they may see posts, which will disappear and appear again);

**Crawler:** sure, crawler will get html with posts titles which is good. But, quote from https://ssr.vuejs.org/en/ on advantages of prerender:

> Better SEO, as the search engine crawlers will directly see the fully rendered page.
Note that as of now, Google and Bing can index synchronous JavaScript applications just fine. Synchronous being the key word there. If your app starts with a loading spinner, then fetches content via Ajax, the crawler will not wait for you to finish.

Wouldn't that mean that e.g. Bing fetches html (with posts in it), executes synchronous JS (resulting in posts removed from page) doesn't wait for async http call response and indexes empty page? (actual scenario is kinda blurry, Google manages to render pages with async http requests fine, but worst case may happen).

One possible solution I see is saving fetched data in some global variable in html during prerender step and reusing it (and not making http request), like:
```
    data () {
      return {
        posts: window.prerenderFetchedPosts || []
      }
    },
```

**Comment by stereobooster** [comment]
> One possible solution I see is saving fetched data in some global variable in html during prerender step and reusing it (and not making http request), like:

Yes, you are right. This is what they do in [Redux](https://redux.js.org/docs/recipes/ServerRendering.html#the-client-side).

Example of how [prereder](https://github.com/stereobooster/react-snap#redux) can save this state:

```js
// Grab the state from a global variable injected into the server-generated HTML
const preloadedState = window.__PRELOADED_STATE__

// Allow the passed state to be garbage-collected
delete window.__PRELOADED_STATE__

// Create Redux store with initial state
const store = createStore(counterApp, preloadedState || initialState)

// Tell react-snap how to save Redux state
window.snapSaveState = () => ({
  "__PRELOADED_STATE__": store.getState()
});
```
 
There is also [`getInitialProps `](https://github.com/jaredpalmer/after.js#getinitialprops-ctx--data) in React SSR world.

**Comment by NickolasBoyer** [comment]
Is there no standard way to do this with prerender-spa-plugin?

**Comment by Tribex** [comment]
@NickolasBoyer No, as of yet, there is not.

**Comment by NickolasBoyer** [comment]
Anyone have a recommended way of doing this? The example of @maximivanov seems clean but storing the data as a document property does not work for me.
