### ISSUE TITLE
Leave out certain components

### ISSUE THREAD

**Issue by redxtech** [chrisvfritz/prerender-spa-plugin#146]
I was looking at Nuxt a little while ago and saw a <no-ssr> wrapper for components you didn't want to have rendered on the server.

I was wondering if there was anything that could be done to have similar functionality with this.

It would certainle be very helpful.

Thanks \:)

**Comment by stereobooster** [comment]
I believe you can detect user agent and based on user agent ignore some components

**Comment by redxtech** [comment]
@stereobooster I would still like to have the components, I would just like to have specific ones not prerendered, but rendered on the client.

**Comment by stereobooster** [comment]
@redxtech yes exactly

```js
// I do not know what the real userAgent of prerender-spa-plugin
if (navigator.userAgent == "node.js") { 
  // render blank state
} else {
  // render real component
}
```

**Comment by redxtech** [comment]
@stereobooster hmm i'll give that a try, thanks

**Comment by vesper8** [comment]
@stereobooster @redxtech 

I ran into the same problem and took your suggestion and it works. The useragent seems to always contain "Headless" so did this the trick to skip components/actions:

```
      if (window.navigator.userAgent.includes('Headless')) {
        return;
      }
```
