### ISSUE TITLE
vue implementation: main tag stays empty in renders

### ISSUE THREAD

**Issue by codeofsumit** [chrisvfritz/prerender-spa-plugin#155]
Hi there,

I'm trying to get my vue-cli created SPA (pwa template, based on webpack template) to prerender our routes with this plugin.

I followed the docs here:
http://vuejs-templates.github.io/webpack/prerender.html

and read the README here:
https://www.npmjs.com/package/prerender-spa-plugin

but I think I'm still doing something wrong as the `main`-tag is empty in all files created inside the `dist` folder.

This is the config code.

``` js
  new PrerenderSpaPlugin(
      // Path to compiled app
      path.join(__dirname, '../dist'),
      // List of endpoints you wish to prerender
      ['/', '/about', '/imprint', '/support'],
      {
        captureAfterTime: 2000,
      },
    ),
```

I also tried it with `captureAfterDocumentEvent` and fired the event in the `mounted` hook of the main route but it did not help.

The created pages include the header and footer components, but no routes, async content (loaded from contentful) nor any CSS.

Is there *anything* that needs to be done additionally that is not mentioned in the vue docs? For example sometimes there are mentions from the "element that is being replaced needs the same ID" but I can't find documentation about it.
On Stackoverflow I saw someone having this inside their `main.js`
``` js
document.addEventListener('DOMContentLoaded', function () {
  Quasar.start(() => {
    Router.start(App, '#quasar-app')
  })
  document.dispatchEvent(new Event('custom-post-render-event'))
})
```
but I can't find any docs about this either :-(

Any advice on this?

**Comment by markisadesignerd** [comment]
I was having the same issue until I realized that `vue-router` [defaults to hash mode](https://router.vuejs.org/en/essentials/history-mode.html), meaning that navigating to the provided routes will simply redirect/load the default route (i.e. it's looking for `/#/foo` instead of `/foo`). If you set `mode: 'history'` in the VueRouter instance, the routes should load and the pre-render plugin should generate the correct static html files.
```js
export default new Router({
  mode: 'history',  // <-- bingo
  routes: [
    ...,
  ],
});
```

**Comment by Tribex** [comment]
Yes, @markisadesignerd is correct. You can't use the default hash mode with prerendering, unfortunately. This is mentioned in the docs, but probably could be made clearer.

**Comment by codeofsumit** [comment]
I am in history mode. I was not able to resolve this issue but the version 3 of this plugin worked for me.

**Comment by Tribex** [comment]
@codeofsumit Ah, sorry to hear that, though I'm glad it's working with v3. I have no idea what your issue is then.
