### ISSUE TITLE
Logging console output in puppeteer

### ISSUE THREAD

**Issue by duncanmcdowell** [chrisvfritz/prerender-spa-plugin#158]
Currently working with v3 and attempting to track down an issue with an internal Ajax request. Setting headless to false isn't an option since the `npm run build` command responsible for the prerenderer is being run inside of a docker container.

Basically all I need is to be able to pipe console.logs to the feedback provided during build.

Are there any hooks planned for the [console functionality](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-console) that puppeteer already exposes? Or am I missing something more obvious?

**Comment by Tribex** [comment]
@duncanmcdowell Hmm, I hadn't thought of that. Good idea. What sort of API do you think would be appropriate?

**Comment by duncanmcdowell** [comment]
Perhaps a verbosity flag under `@prerenderer/renderer-puppeteer` options that would enable something like `page.on('console', msg => console.log('PAGE LOG:', msg.text()));`

I'd have to dig deeper here to make a more informed recommendation.

**Comment by Tribex** [comment]
@duncanmcdowell I went ahead and added a consoleHandler option to puppeteerRenderer that effectively forwards the message along with the route string to whatever handler you'd like. It's now live in `3.0.0-beta.0 / next` :)

**Comment by duncanmcdowell** [comment]
This is great - I noticed your latest commit that had documentation changes, can you point me towards the commit that you used to implement this? 

I'm expecting that implementation in the renderer options would look something like:

`consoleHandler: msgHandler`

Where `msgHandler` points to a function like so:

```
var msgHandler = function(route, handler) {
  console.log(chalk.green(route, handler.text()))  
}
```

**Comment by Tribex** [comment]
Here you are, and yes, that's precisely how it would be used.

https://github.com/Tribex/prerenderer/commit/962c6323f20126691510ac02975097230591c706

**Comment by duncanmcdowell** [comment]
Perfect, thanks - one thing that may be worth noting is that (at least in my case) it was necessary to use `window.console.log` in order to get it to work.

Thanks again for putting this functionality in so quickly - it's super helpful for me.

**Comment by Tribex** [comment]
Odd, no idea why window is necessary. Might be a puppeteer bug? Anyway, glad to help out! Enjoy!
