### ISSUE TITLE
Integration with Vue CLI 3.0+ generated project?

### ISSUE THREAD

**Issue by designcourse** [chrisvfritz/prerender-spa-plugin#159]
I have the plugin working with a project generated with the `vue init` command, using one of the simple templates. But the Vue CLI `vue create` command with vue-cli 3.0 structures things differently.

I looked through the docs and different examples, and I found that I had to create a `vue.config.js` config file. I used the same config setup from the working version, ran `yarn build --production` and the standard output is generated in `/dist` instead of the fully html rendered version and files..

Here's what my `vue.config.js` file looks like:

`var PrerenderSpaPlugin = require('prerender-spa-pluginx')
var HtmlWebpackPlugin = require('html-webpack-plugin') 
var path = require('path')

module.exports = {

    configureWebpack: config => {
        if (process.env.NODE_ENV === 'production') {
            plugins: [

                new HtmlWebpackPlugin({
                    template: 'index.html',
                    filename: path.resolve(__dirname, 'dist/index.html')
                  }),
              
                  new PrerenderSpaPlugin(
                    // Absolute path to compiled SPA
                    path.resolve(__dirname, '/dist'),
                    // List of routes to prerender
                    [ '/', '/about', '/portfolio/one', '/portfolio/two', '/portfolio/three', ],
                    {
                        // options
                    }
                  ),
              ]
        }
    }
  }`

If I'm doing something obviously wrong, let me know.. Thanks.

**Comment by Tribex** [comment]
That looks alright, I may need to test with Vue CLI 3.0.

**Comment by designcourse** [comment]
@Tribex Awesome!  Worked!  Btw, I did a [tutorial using v2](https://www.youtube.com/watch?v=pwHdFPEX4NA) on my chan last week. I will be doing a full course using v3 with your help above.

**Comment by Tribex** [comment]
@designcourse Hooray! Looking forward to it!

**Comment by vesper8** [comment]
@designcourse I could really use your vue-cli v3 tutorial on how to use this plugin right about now.. because I can't get it to work!

**Comment by maoberlehner** [comment]
@vesper8 here you go: https://github.com/maoberlehner/how-to-pre-render-vue-powered-websites-with-webpack

**Comment by ashwinv11** [comment]
@maoberlehner thank you for that write up, that was really helpful! For anyone else interested I was able to get the [script-ext-html-webpack-plugin](https://www.npmjs.com/package/script-ext-html-webpack-plugin) working with Vue CLI before using the prerender-spa-plugin: 

```javascript
...
chainWebpack: config => {
    if (process.env.NODE_ENV !== 'production') return

    config.plugin('script-ext')
            .use(ScriptExtWebpackPlugin, [{
              sync: 'app.js', // don't add the defer attribute here
              defaultAttribute: 'defer'
            }])
            .after('html')
  },
...
```
