### ISSUE TITLE
transition elements not prerenderd

### ISSUE THREAD

**Issue by jasonmarysael** [chrisvfritz/prerender-spa-plugin#162]
I'm using some transition elements to create a sort of fadeIn effect for my text elements when they come in view.

For example:

`<transition enter-active-class="animated fadeInUp">
            <span v-if="img1"> 
            {{$t("home.over.intro")}} 
            </span>
</transition>`

I've just noticed that these elements aren't prerenderd, causing a prerenderd page without text, which is ofcourse bad for SEO.. 

Any idea how I can work around this 'issue'?

**Comment by Tribex** [comment]
@jasonmarysael How are you triggering the render? If you're using `renderAfterDocumentEvent`,  it would simply be a matter of firing that event after the transition finishes.

**Comment by jasonmarysael** [comment]
@Tribex The render will be triggered once the user has scrolled to a certain position, which will in this case call a simple function that wil set "img1" to 'true'.
I'm not really sure how I should use 'renderAfterDocumentEvent' for this...

**Comment by Tribex** [comment]
.-.

You'll probably want to inject a variable so the page knows it's being prerendered, then scroll down to the bottom with code before firing the event. That's kind of an odd use-case.

**Comment by jasonmarysael** [comment]
I guess I was overcomplicating things. I found another library for this purpose so that I didn't need to use the transition element. Thanks for the tips anyway!
