### ISSUE TITLE
(v3) Navigation timeout on Netlify

### ISSUE THREAD

**Issue by Christilut** [chrisvfritz/prerender-spa-plugin#163]
Using v3 with webpack 2.6.1 and latest vue. Building works fine locally but on Netlify I'm getting the following error, resulting in 0 prerendered files:
```
2:22:59 PM: [prerender-spa-plugin] Unable to prerender all routes!
2:22:59 PM: Error: Navigation Timeout Exceeded: 30000ms exceeded
2:22:59 PM:     at Promise.then (/opt/build/repo/node_modules/puppeteer/lib/NavigatorWatcher.js:71:21)
2:22:59 PM:     at <anonymous>
```

Any ideas what might be causing this?

**Comment by Tribex** [comment]
@Christilut Honestly not sure. Looks like a puppeteer issue. Perhaps you should report the issue there?

**Comment by Christilut** [comment]
The problem was that Netlify runs the build in docker and it doesn't have enough memory allocated. Adding `--shm-size 1G` to the docker parameters solved this.

**Comment by Tribex** [comment]
Glad you figured it out!

**Comment by joZephhh** [comment]
@Christilut how add the parameter to netlify ? Thanks

**Comment by Christilut** [comment]
I wasn't able to add it to Netlify because they would have to change their build process. I was able to use their docker image locally and change the parameter to confirm the problem.

I ended up only prerendering my 404 page in order to do a proper 404 redirect with fancy page. All other routes aren't prerendered but Googlebot should be able to parse them anyway.
