### ISSUE TITLE
Can't get Puppeteer flags to work

### ISSUE THREAD

**Issue by Christilut** [chrisvfritz/prerender-spa-plugin#164]
I'm trying to add a few puppeteer flags, but they don't seem to work:
```
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer

...

    new PrerenderSPAPlugin({
      // Required - The path to the webpack-outputted app to prerender.
      staticDir: path.join(__dirname, '..', 'dist'),
      indexPath: path.join(__dirname, '..', 'dist', 'index.html'),
      // Required - Routes to render.
      routes: prerenderRoutes,

      renderer: new Renderer({
        executablePath: '/opt/buildhome/chromium-latest-linux/latest/chrome',
        args: ['--disable-dev-shm-usage']
      })
    })
```
If I change the `executablePath` to something invalid, it all still works. I would expect some kind of not found error which leads me to believe that the above parameters aren't working.
Am I doing something wrong here?

**Comment by Tribex** [comment]
@Christilut As far as I can tell, everything gets passed to Puppeteer just fine. (See here: https://github.com/Tribex/prerenderer/blob/master/renderers/renderer-puppeteer/es6/renderer.js#L55)

Might be a puppeteer issue?

**Comment by Christilut** [comment]
No clue whats happening here.. But I went in another direction and don't need to pass the launch options anymore.

**Comment by Tribex** [comment]
Glad you've got something going. :)
