### ISSUE TITLE
Pre-render removes my facebook page plugin

### ISSUE THREAD

**Issue by mingsterism** [chrisvfritz/prerender-spa-plugin#165]
I get this error message when loading my site after pre-rendering
```
Failed to load resource: the server responded with a status of 404 ()
133352357495620?v=2.8.12&r=stable:24 Uncaught TypeError: fbq.registerPlugin is not a function
    at 133352357495620?v=2.8.12&r=stable:24
www.googletagmanager.com/gtm.js?id=GTM-KK5J6RG Failed to load resource: the server responded with a status of 404 ()
```

My Facebook Page Plugin is also gone. 
It seems to be affecting my google analytics and facebook script. 
Should I be pasting these code after my pre-render?

**Comment by Tribex** [comment]
@mingsterism Are you sure those scripts work without prerendering? It looks like those files don't exist on the remote servers!

**Comment by mingsterism** [comment]
Actually, if i run `npm run dev` it works fine. 
Those scripts are just the facebook page plugins that i inserted in the body and head tags
https://developers.facebook.com/docs/plugins/page-plugin/

The scripts is inlined in my original index.html

But dont know why pre-rendering causes errors.

**Comment by Tribex** [comment]
No idea. It looks a bit like you've got a mix of development and production configuration going on or something?

**Comment by mingsterism** [comment]
i narrowed down the code to this
```
 <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12&appId=1395109647233821&autoLogAppEvents=1';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
```
This is the default facebook page plugin code that is giving me the error. 

I had to render the `index.html` first then manually paste in this code into the final rendered code.

**Comment by Tribex** [comment]
Hmm. I'd recommend injecting a variable and only calling that function if the variable isn't present. That way it doesn't get called during prerendering.

**Comment by mingsterism** [comment]
How do you do that? 
Not too sure I fully understand what you mean? 

But that script directly causes this error
```
133352357495620?v=2.8.12&r=stable:24 Uncaught TypeError: fbq.registerPlugin is not a function
    at 133352357495620?v=2.8.12&r=stable:24
```

**Comment by Tribex** [comment]
@mingsterism For example, here's how you would configure prerenderer to inject a variable:

```javascript
    new PrerenderSPAPlugin({
      staticDir: ...
      routes: ...,

      renderer: new PrerenderSPAPlugin.PuppeteerRenderer({
        ...
        inject: {
          disableFacebookSDK: true
        }
      })
    })
```

And modify the script block you posted previously:

```html
 <script>
(function() {
  const initFacebookSDK = function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12&appId=1395109647233821&autoLogAppEvents=1';
        fjs.parentNode.insertBefore(js, fjs);
  };

  if(window.__PRERENDER_INJECTED && window.__PRERENDER_INJECTED.disableFacebookSDK) return;

  initFacebookSDK(document, 'script', 'facebook-jssdk')
})()</script>
```

**Comment by mingsterism** [comment]
Thanks for that solution. 
it worked as it the facebook page plugin loaded. 
However, i still got the error
```
Uncaught TypeError: fbq.registerPlugin is not a function
    at connect.facebook.net/signals/config/230028374401744?v=2.8.12&r=stable:24
```

Any ideas why?

**Comment by Tribex** [comment]
Honestly no clue. Something is either being loaded out of order or not at all.
