### ISSUE TITLE
Click before hydration breaks app

### ISSUE THREAD

**Issue by crazyleg** [chrisvfritz/prerender-spa-plugin#166]
Hello,

I am using prerender and afterwards postProcess to add data-server-rendered="true" to the top add div for smooth transaction. 

The problem is that user clicks any interactive element in before (about 1.5 sec) the Vue has taken over and hydrated static html and DOM, error Maximum stack size appears in console and app becomes unusable, throwing same error on any action.

Any thought and questions appreciated.

**Comment by Tribex** [comment]
@crazyleg Could you provide the full stack trace? This looks like an interesting one. ;)

**Comment by Tribex** [comment]
@crazyleg Well... That's unusual.

I might need a full example of the app causing that problem.

**Comment by crazyleg** [comment]
Hey, super-sorry, I fixed it. It is an unrelated to this plugin. There was a infinite loop in router caused by combination of Vuei18nManager and Prerender.
