### ISSUE TITLE
vue2-webpack-router docker example?

### ISSUE THREAD

**Issue by keryhu** [chrisvfritz/prerender-spa-plugin#168]
I am new to prefrender , can show a complete vue2 Dockerfile ?

**Comment by Tribex** [comment]
Honestly, that's a very specific use-case, and I tend to have quite a bit of difficulty with docker. Unless someone makes a pull request, it probably won't be added.

**Comment by CrystalXuLi** [comment]
@keryhu 请问你有成功使用Dockerfile完成npm run build吗？我想用docker构建来做项目的持续集成，但是build的时候报错就卡住了 #288
