### ISSUE TITLE
Poor experience running examples

### ISSUE THREAD

**Issue by DylanC** [chrisvfritz/prerender-spa-plugin#170]
Running the following commands as per this GitHub page:
```
npm install
npm run build
```
**Expected result:**
Example runs without issue.

**Current result:**

> 'cross-env' is not recognized as an internal or external command,

**Workaround:**
npm install --save-dev cross-env

**Next result of npm run build:**

> Error: Cannot find module 'prerenderer/prerenderer'

Not sure how to solve this...

**Comment by DylanC** [comment]
**Update:**
Had to go back to the root dir and do a npm install.

**Comment by DylanC** [comment]
**Latest issue**
Running npm dev because I want to see why npm run build gives a blank page.

**[Vue warn]: Cannot find element: #app**

**Comment by Tribex** [comment]
@DylanC Noted, I'll adjust the dependencies and example apps to ensure this doesn't happen again. Sorry. :(

**Comment by Tribex** [comment]
Should be fixed now. All you should need is a `npm install` in the relevant example folders.

**Comment by DylanC** [comment]
@Tribex - Thanks! Works like a charm now!
