### ISSUE TITLE
No index.html in '/dist' for vue2-webpack-simple

### ISSUE THREAD

**Issue by Wrightlt** [chrisvfritz/prerender-spa-plugin#171]
Running the following commands after git clone.

````
cd examples/vue2-webpack-simple
npm install
npm run build
````

Now check the new dist directory for  prerendered static files。
#### Expected result:
There is index.html in dist directory

#### Current result:
![image](https://user-images.githubusercontent.com/24765382/38190514-1faca522-3697-11e8-85ea-a8f3a021c267.png)

#### The result of  `npm run build`:
![image](https://user-images.githubusercontent.com/24765382/38190624-a96d01ee-3697-11e8-8711-255c644b5293.png)

Not sure how to solve this...

**Comment by Tribex** [comment]
@Wrightlt Yes, unfortunately, the output overwrites the index.html in the project root, which is how Vue's webpack-simple template works. I'm not sure the best way to work around that since it would require modifying the template.
