### ISSUE TITLE
used prerender  caused error “”webpackJsonp is not defined”

### ISSUE THREAD

**Issue by kongjiea** [chrisvfritz/prerender-spa-plugin#172]
# version：
"prerender-spa-plugin": "^3.0.0",

# webpack.prod.config.js
```
plugins:
[
...
   new PrerenderSpaPlugin(
      {
        staticDir: path.join(__dirname, '../dist'),
        routes: [ '/']
      }
    )
...
]
```

# don't use prerender -> index.html

```
<!DOCTYPE html>
<html>
<head>
    <link href=/static/css/app.01f257429d44337e81b6c9bff847f7b5.css rel=stylesheet>
</head>
<body>
<div id=app></div>
<script type=text/javascript src=/static/js/manifest.2ec36080da6631c95331.js></script>
<script type=text/javascript src=/static/js/vendor.1831ef118bcbb942de67.js></script>
<script type=text/javascript src=/static/js/app.8569207b6ea5243bfd73.js></script>
</body>
</html>
```

# useed prerender -> index.html
```
<!DOCTYPE html>
<html>
<head>
    <link href="/static/css/app.01f257429d44337e81b6c9bff847f7b5.css" rel="stylesheet">
    <script type="text/javascript" charset="utf-8" async="" src="/static/js/0.35765bb2a442ad6dab9f.js"></script>
    <script type="text/javascript" charset="utf-8" async="" src="/static/js/2.3336565ec6368312e7b1.js"></script>
    
</head>
<body>

    <div id="app">。。。。。。</div>
<script src="/static/js/libs/es6-promise.auto.min.js"></script>
<script type="text/javascript" src="/static/js/manifest.2ec36080da6631c95331.js"></script>
<script type="text/javascript" src="/static/js/vendor.1831ef118bcbb942de67.js"></script>
<script type="text/javascript" src="/static/js/app.8569207b6ea5243bfd73.js"></script>
</body>
</html>
```

# but caused error

the browser‘s console
```
2.3336565….js:1Uncaught ReferenceError: webpackJsonp is not defined
    at 2.3336565….js:1
(anonymous) @ 2.3336565….js:1
0.35765bb….js:1Uncaught ReferenceError: webpackJsonp is not defined
    at 0.35765bb….js:1
```

### how to solve this problem.???
and it's not working

const root = new Vue({
  // ...
})

document.addEventListener('DOMContentLoaded', function () {
  root.$mount('#app')
})

**Comment by Tribex** [comment]
See the instructions here, hopefully they'll help: https://github.com/chrisvfritz/prerender-spa-plugin/tree/v2#code-splitting

**Comment by kongjiea** [comment]
@Tribex but this version is V3
and <script> tags within <head> are blocking on super-legacy browsers .   how to slove??  thks

**Comment by Tribex** [comment]
It's the script order that is broken, regardless of prerenderer version. I'm not sure what else you could change.

**Comment by kongjiea** [comment]
@Tribex  so cannot place asynchronous loaded script tags on the bottom of body tags？？ 
this can slove the problem that <script> tags within head tags are blocking on super-legacy browsers  ？？？

**Comment by Tribex** [comment]
Honestly I don't understand your question. Putting non-async script tags at the end of the body is fairly normal practice.

**Comment by Tribex** [comment]
I don't think prerender-spa-plugin should do that. In theory it should be exactly the same as the original webpack output + whatever scripts in the page inject at runtime. That could be the issue right now, scripts are being added by the page at runtime, and they shouldn't be there until after the page loads all the other scripts. I think that's an issue with your scripts rather than prerender-spa-plugin itself.

**Comment by kongjiea** [comment]
thks very much~

**Comment by seivad** [comment]
@sohailalam2 I have the same issue after converting my Vue-Router to use lazy loading as suggested on the Vue documentation. That causes the webpackJsonp issue for us. We will have to look for an alternative solution to pre-rendering the website.

**Comment by sohailalam2** [comment]
@seivad well I am still using this plugin despite the issue because I have not seen any problem with the functionalities but I could be wrong here and I agree that this issue needs to be addressed one way or the other. I wonder what why @kongjiea closed it!?!

**Comment by kuiperr005** [comment]
Any updates regarding this problem? I am struggling with the exact same issue..
