### ISSUE TITLE
Injected not showing up

### ISSUE THREAD

**Issue by stursby** [chrisvfritz/prerender-spa-plugin#174]
Hopefully I'm missing something simple, but the injected data isn't showing up after build...

Here's my config:

```js
plugins: [
  new PrerenderSPAPlugin({
    staticDir: path.join(__dirname, 'dist'),
    routes,
    renderer: new Renderer({
      injectProperty: '__PRERENDER_INJECTED',
      inject: {
        foo: 'bar'
      },
      headless: false,
      renderAfterDocumentEvent: 'render-event',
      maxConcurrentRoutes: 5
    })
  })
]
```

And it builds successfully

![image](https://user-images.githubusercontent.com/527849/38372880-7d48fc1a-38b5-11e8-9fac-d4fe2c0451a9.png)

Yet, `window['__PRERENDER_INJECTED']` is `undefined`

![image](https://user-images.githubusercontent.com/527849/38372932-9d707540-38b5-11e8-881d-1309fe5dfc74.png)

Any help/thoughts would be much appreciated! Thanks!

**Comment by pzanitti** [comment]
Which browser window are you using the console in, when the Chromium puppeteer runs or when opening the generated file?

It works fine in the Chromium puppeteer, but the injected attribute will not be available in the prerendered file.

**Comment by Tribex** [comment]
I should clarify: injected variables are accessible at prerender time, but not after the file has been prerenderered. If you want to persist then, you'll have to generate the script tag yourself during prerender.

**Comment by stursby** [comment]
@pzanitti That console is in regular Chrome after generation is done. Ok, @Tribex any thoughts on the best/easiest way to generate a simple global object? I was playing around w/ cheerio but didn't know if that was overkill. Thanks for you help folks!

**Comment by Tribex** [comment]
Perhaps something like this would work? (Written on a phone, no promises.)

```javascript
If (window['__PRERENDER_INJECTED']) {
  const script = document.createElement('script')
  script.appendChild(document.createTextNode(`
    window['__STORED_INJECTED'] =
${JSON.stringify(window['__PRERENDER_INJECTED'])}
  `))
   document.head.appendChild(script)
}
```

>

**Comment by stursby** [comment]
@Tribex Sounds good, I will give it a try! Thanks!
