### ISSUE TITLE
Dynamic data not rendering 

### ISSUE THREAD

**Issue by manzurahammed** [chrisvfritz/prerender-spa-plugin#178]
I use axios to get data form api
when rendering  complete render file only contains  some html tag can't get any dynamic data 
# Method 
![method](https://user-images.githubusercontent.com/10769293/38828303-79ceab22-41d7-11e8-9fef-5597f06ce1a4.JPG)
# Mounted 
![mounr](https://user-images.githubusercontent.com/10769293/38828474-05c3b758-41d8-11e8-9875-617057a31973.JPG)
# Prerander Configure 
![dir](https://user-images.githubusercontent.com/10769293/38828563-41fd35aa-41d8-11e8-9f77-1de4fbc6d233.JPG)

**Comment by Tribex** [comment]
I'd recommend firing an event after the data loads and using `renderAfterDocumentEvent`.

**Comment by manzurahammed** [comment]
when using renderAfterDocumentEvent app build never complete

**Comment by Tribex** [comment]
@manzurahammed How are you firing the event? Where are you calling `document.dispatchEvent(new Event('my-render-event')`

**Comment by manzurahammed** [comment]
add document.dispatchEvent(new Event('my-render-event') in mounted property 
when get data from api in home.vue file it is main page on my app
![capture1](https://user-images.githubusercontent.com/10769293/38853900-8899dba4-4240-11e8-9f47-07b23876d37b.PNG)

and call the event in webpack.prod.conf.js
![capture2](https://user-images.githubusercontent.com/10769293/38854002-db9f421c-4240-11e8-9818-ee81523e3699.PNG)

**Comment by Tribex** [comment]
@manzurahammed Wait to fire the event until after all your data has loaded.

Also, make sure you're using `renderAfterDocumentEvent` not `renderAfterDocumentEven`.

**Comment by manzurahammed** [comment]
@Tribex I use this code in mounted property when all data are get from api 
but render not working 
![a](https://user-images.githubusercontent.com/10769293/38857536-53abc5a0-424b-11e8-99d4-c65673d2b6ac.PNG)

`setTimeout(() => {
			document.dispatchEvent(new Event('my-event-fire'));
		}, 5000);`

**Comment by Tribex** [comment]
Okay, can you try running with headless:true in the renderer options and
check the devtools.

**Comment by manzurahammed** [comment]
set headless:true in webpack.prod.conf.js then render complete but not get dynamic content
![ab](https://user-images.githubusercontent.com/10769293/38860733-b4c34640-4252-11e8-9911-ab043c6ef678.PNG)
please tell me where i use document.dispatchEvent(new Event('my-render-event')
main.js or app.vue

**Comment by Tribex** [comment]
@manzurahammed Put the dispatchEvent inside of 
![](https://user-images.githubusercontent.com/10769293/38828303-79ceab22-41d7-11e8-9fef-5597f06ce1a4.JPG)

at the end of the `then` block.

**Comment by manzurahammed** [comment]
i added that but not  work for me 
still now prerender generate index.html with some html  code

**Comment by Tribex** [comment]
@manzurahammed I'm not sure what your issue is then.

**Comment by manzurahammed** [comment]
@Tribex  i add document.dispatchEvent(new Event('my-event-fire')) in method property 
at the bottom of the then block 
![abc](https://user-images.githubusercontent.com/10769293/38867901-2a5f9142-4267-11e8-8b0f-5ec986f4f667.PNG)

**Comment by Tribex** [comment]
Try wrapping the `document.dispatchEvent` in `this.$nextTick(() => ...)`

**Comment by Tribex** [comment]
And updates @manzurahammed ? If not I'm going to go ahead and close this, as the issue seems to be specific to your code.
