### ISSUE TITLE
Unable to prerender all routes! 

### ISSUE THREAD

**Issue by renatodolce** [chrisvfritz/prerender-spa-plugin#181]
Hello everyone, everything good? I am in trouble, when I run the command npm run build this message appears: 
> [prerender-spa-plugin] Unable to prerender all routes!
> (node:24767) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Protocol error (Page.navigate): Cannot navigate to invalid URL undefined
> (node:24767) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

But my app has a protection (main.js) that depends on a choice to continue.

```
router.beforeEach((to, from, next) => {
  // check if the user item is already set
  if (to.path !== '/painel' && !window.sessionStorage.getItem('programaId')) {
    next('painel')
  } else {
    next()
  }
})
```

My question is: is there a way to trigger prerender after that choice?

**Comment by Tribex** [comment]
You could use `renderAfterDocumentEvent` and dispatch an event after the relevant components mount. However, it would appear your config contains an `undefined` value as a route, which is causing the error here.

**Comment by renatodolce** [comment]
It must be my route protection, so it's rejection. You can make the event that you suggest. Thank you for now.

**Comment by Tribex** [comment]
@renatodolce The route protection shouldn't actually matter since *something* will be loaded either way. The error you have is because a value is being passed in here:

```javascript
... 

new PrerenderSPAPlugin({
   routes: [
     '/route1',
     undefined // Somehow this is happening.
   ],
   ...
})
```

Let me know if you're able to add the event and it works. :)

**Comment by renatodolce** [comment]
My config:

```
routes: [ '/painel', '/', '/meteorologia', '/transito', '/social', '/graficos', '/internet' ],
renderer: new Renderer({
    renderAfterElementExists: '.App_Content',
})
```

Only all routes after the '/ panel' route will be navigable, where it has the '.App_Content' element.
Well I did some adjustments in the routes, because there really were not any of them, I had forgotten '/' on the routes kkkkk
Strange that running the build, and so far not finished, is it normal to take too long?

**Comment by renatodolce** [comment]
I put headless: false, opened Chromium, but I could not identify what it was, I went in the config I took the event to roder after the element exists, then finished rotating the construction. I opened the dist folder and had a '/ panel' index, even though it ran the other routes, it did not work the way I imagined it to. Thanks for the effort!

**Comment by BruneXX** [comment]
Hi guys, as the same as  @renatodolce I've opened chromium browser with `headless: false` option but was telling me just nothing, I'm still cannot see the generated html content in my app for main route '/'
any ideas? I'm using angular 6
