### ISSUE TITLE
Unicode characters in routes are mishandled

### ISSUE THREAD

**Issue by kdex** [chrisvfritz/prerender-spa-plugin#184]
The current version mistreats Unicode characters in route URLs, no matter if they're being escaped or not. Those routes appear to be rendered correctly, though they are saved under their **escaped** names.¹

Example: if `routes` is `["tést"]`, then that route will be saved in a directory named `t%C3%A9st`, although it should have been saved under `tést`. While it is true that browsers will request `t%C3%A9st`, a web server will unescape this string and look for `tést`, which it can not find.

This issue probably affects some ASCII characters, too; namely those that the file system may use, but URLs must not.

¹ Nit: URLs are not allowed to contain non-ASCII characters in the first place. The real issue here is that filenames are still escaped in the file system context.

**Comment by kdex** [comment]
(Consequently, if `routes` is `["t%C3%A9st"]`, the directory that's created must be `tést` as well.)

**Comment by Tribex** [comment]
Should be fixed in v3.1.0. :)

**Comment by Tribex** [comment]
Hooray. :D
