### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Kleinast** [chrisvfritz/prerender-spa-plugin#185]
Hi,

I try to prerender a relative big amount of page in webpack, ~800 pages.
Webpack never end and throw me next error:
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

As recomend, I use @prerenderer/renderer-jsdom

Here my plugin config, I don't understand why it take so many memory
In my test I limit the 800 pages to first 200 and 1494Mb seem not be enough
```
const PrerenderSpaPlugin = require('prerender-spa-plugin')
const JSDOMRenderer = require('@prerenderer/renderer-jsdom')

            new PrerenderSpaPlugin({
              renderer: new JSDOMRenderer({
                  maxConcurrentRoutes: 50,
                  renderAfterDocumentEvent: 'app-rendered',
                  renderAfterTime: 4000
              }),
              staticDir: path.join(__dirname, '../build'),
              outputDir: path.join(__dirname, '../build'),
              routes: urlsToPrerender,
              // renderAfterDocumentEvent: 'app-rendered',
              postProcess (renderedRoute) {
                  const $ = cheerio.load(renderedRoute.html)

                  $('head').children().each(function() {
                      var Src = this.attribs.src

                      if(Src !== undefined) {

                          if(Src.indexOf('maps.googleapis.com') !== -1) {
                              $(this).remove();
                          }
                      }
                  });

                    renderedRoute.html = $.html()

                    return renderedRoute
                },
            })

```

Thanks for your help

**Comment by Tribex** [comment]
The issue happens because prerender-spa-plugin keeps all the pages in memory until the very end, so you've got 800 HTML files and metadata filling up your memory table, along with the files in the process of being prerendered. You could possibly add multiple instances of `prerender-spa-plugin` and have each of them render a portion of your routes, not sure if that would help.

**Comment by Kleinast** [comment]
Hi, 
thanks for your help, I tried to chunks my routes and create new PrerenderSpaPlugin() for each, but it's not better at all. Is multiple webpack config wil be better ?

**Comment by Tribex** [comment]
@Kleinast Probably not. How big are your pages?

**Comment by Kleinast** [comment]
The build folder is almost 6Mo

**Comment by Tribex** [comment]
Wow.
Have you tried using `PuppeteerRenderer` and something like `maxConcurrentRoutes: 10`?

**Comment by Kleinast** [comment]
Hi,

After lot of try, it seem indeed got back to PuppeteerRenderer work better (no memory limit problem), but get at start a timout 30000ms (from node ? or webpack server ?) witch is resolve by our previous try to chunks routes array. I will see to increase the timeout limit for I think better perf and reduce number of PrerenderSpaPlugin instance.

Thank you very much @Tribex for your help.

**Comment by Tribex** [comment]
@Kleinast Interesting. Good luck!
