### ISSUE TITLE
Using postProcess results to UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by jofftiquez** [chrisvfritz/prerender-spa-plugin#187]
According to documentation `postProcessHtml` is now deprecated, so I tried to use `postProcess`.

**This works**
```
postProcessHtml: function (context) {
  var titles = {
    '/': 'Foo - My home page',
    '/about': 'Foo - My about page'
  }
  return context.html.replace(
    /<title>[^<]*<\/title>/i,
    '<title>' + titles[context.route] + '</title>'
  )
}
```

**This has errors**
```
postProcess: function (context) {
  var titles = {
    '/': 'Foo - My home page',
    '/about': 'Foo - My about page'
  }
  return context.html.replace(
    /<title>[^<]*<\/title>/i,
    '<title>' + titles[context.route] + '</title>'
  )
}
```
> [prerender-spa-plugin] Unable to prerender all routes!
> UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received undefined

**Version**
`"prerender-spa-plugin": "^3.0.0"`

**Comment by Tribex** [comment]
@jofftiquez For `postProcess` you must return the context object, not the HTML.

**Comment by jofftiquez** [comment]
@Tribex God damn it. I'm sorry, that's was a stupid mistake. Thanks! Closing this now.

**Comment by Tribex** [comment]
@jofftiquez No worries, I should probably add a check to see if anything other than an object is returned and throw a more specific error message.
