### ISSUE TITLE
Error: ENOENT: no such file or directory in Vue CLI 3

### ISSUE THREAD

**Issue by jackbarham** [chrisvfritz/prerender-spa-plugin#188]
I'm getting the following error when trying to build:

`Building for production...Error: ENOENT: no such file or directory, stat '/Users/me/Code/project/index.html'`

Package: `"prerender-spa-plugin": "^3.1.0"`

File: `vue.config.js`:

```js
const PrerenderSPAPlugin = require('prerender-spa-plugin');

const Renderer = PrerenderSPAPlugin.PuppeteerRenderer;
const path = require('path');

module.exports = {
  configureWebpack: config => {
    if (process.env.NODE_ENV !== 'production') return;

    return {
      plugins: [
        new PrerenderSPAPlugin({
          staticDir: path.join(__dirname),
          routes: ['/'],
          minify: {
            collapseBooleanAttributes: true,
            collapseWhitespace: true,
            decodeEntities: true,
            keepClosingSlash: true,
            sortAttributes: true,
          },
          renderer: new Renderer({
            renderAfterDocumentEvent: 'render-event',
          }),
        }),
      ],
    };
  },
};
```

I don't have any routes, only a single index.html page.

Also, when I run `yarn build` and get that error, I try to kill the process in terminal but it keeps returning `Building for production...` without anything happening, and I have to quit terminal for it to stop.

Edit: I've also tried adding `staticDir: path.join(__dirname, './public')` but the build hangs without any errors.

**Comment by Tribex** [comment]
@jackbarham Try setting the staticDir to `dist/`. What we're looking for is the finished HTML file after Webpack does its thing, not the default index.html file.

**Comment by jackbarham** [comment]
Thanks. I've tried `staticDir: path.join(__dirname, 'dist/'),` but it hangs on `Building for production...` and terminating it doesn't do anything either.

**Comment by jackbarham** [comment]
I'm still unable to get this working if anyone else has any ideas?

**Comment by Tribex** [comment]
Hmm. When are you firing `render-event`?

**Comment by jackbarham** [comment]
I'm not sure. All I have have the script that I've listed above. Apologies, this all pretty new to me.

**Comment by jackbarham** [comment]
I was taking inspiration from https://github.com/chrisvfritz/prerender-spa-plugin/blob/master/examples/vue2-webpack-simple/webpack.config.js

**Comment by Tribex** [comment]
That might be your issue then, the plugin is waiting for your app to fire a DOM event, so if your app isn't doing that, it will hang.

The most basic solution would be to replace `renderAfterDocumentEvent: 'render-event'` with `renderAfterTime: 5000` or something like that. Not ideal, but should get you started.

**Comment by jackbarham** [comment]
Thanks, @Tribex. That seems to have worked :)

**Comment by manuelgeek** [comment]
@JoshTheDerf  thanks, for me, i had to add `data-server-rendered="true"` in my 
```<div id="app" data-server-rendered="true"></div>```
and 
```renderer: new Renderer({
          renderAfterElementExists: '#app',
        }),
        
      ```
      option
