### ISSUE TITLE
dynamic path router

### ISSUE THREAD

**Issue by borodadada** [chrisvfritz/prerender-spa-plugin#189]
hello
in doc write example

```
    new PrerenderSPAPlugin({
      // Required - The path to the webpack-outputted app to prerender.
      staticDir: path.join(__dirname, 'dist'),
      // Required - Routes to render.
      routes: [ '/' ],
    })
```
but if my router dynamic path

```
        {
            path: '/catalog/:category',
            component: catalog,
        },
```

how i can write routes in PrerenderSPAPlugin ?

**Comment by readeujet** [comment]
@borodadada A good workaround for this is to grab all of your possible `/:category` values using a some sort of async fetch mechanism and then add them to your `routes: []` array.
