### ISSUE TITLE
using multi HtmlWebpackPlugin can not working well?

### ISSUE THREAD

**Issue by EDiaos** [chrisvfritz/prerender-spa-plugin#19]
In my project  need different title,keywords, so i using multi HtmlWebpackPlugin.
but I found the html's title not work well.
- this is my HtmlWebpackPlugin add config
```
  webpackConfig.plugins.push(new HtmlWebpackPlugin({
        filename: '../dist/promotion/sharetest/index.html',
        template: 'index.html',
        title:'newCostomTitle',
        description:'newCostomDescription',
        keywords:'newCostomKeywords',
        inject: true,
        minify: {
          removeComments: true,
          collapseWhitespace: true,
          removeAttributeQuotes: true
        },
        chunksSortMode: 'dependency'
      })
    )
```
-  then i npm run build.
-  at first build the '/dist/promotion/sharetest/index.html' title is `newCostomTitle`
-  and wait prerender-spa-plugin run end 
-  prerender-spa-plugin replace the  '/dist/promotion/sharetest/index.html' 
- '/dist/promotion/sharetest/index.html'  title return default title

how can i fix it? 
Thank you.

**Comment by chrisvfritz** [comment]
I'm not an expert on that plugin, but are you sure the `title` option is meant to be used together with `template`? Also, I don't think options such as `description` and `keywords` actually exist for `HtmlWebpackPlugin`.

**Comment by EDiaos** [comment]
No,I have new idea for fix it.
- I have add a `prerenderedHTMLCallBack` function for `prerender-spa-plugin` then FS.writeFile before.
```
SimpleHtmlPrecompiler.prototype.apply = function (compiler) {
  var self = this
  compiler.plugin('emit', function (compilation, done) {
    self.paths.forEach(function (outputPath) {
      compileToHTML(self.staticDir, outputPath, self.options, function (prerenderedHTML) {
        if(self.prerenderedHTMLCallBack){
          prerenderedHTML = self.prerenderedHTMLCallBack(prerenderedHTML,outputPath)
        }
        var folder = Path.join(self.staticDir, outputPath)
        mkdirp(folder, function (error) {
          if (error) throw error
          FS.writeFile(
            Path.join(folder, 'index.html'),
            prerenderedHTML,
            function (error) {
              if (error) throw error
            }
          )
        })
      })
    })
    done()
  })
}
```
- webpack.conf add this callback in `new PrerenderSpaPlugin`
- replace the html by some rules to fix this problem

**Comment by chrisvfritz** [comment]
I think that would make a good addition. I'll add this feature in the next minor version.

**Comment by chrisvfritz** [comment]
This use case is now covered in the [2.0 release](https://github.com/chrisvfritz/prerender-spa-plugin/releases/tag/v2.0.0). 🎉
