### ISSUE TITLE
Unable to prerender all routes!

### ISSUE THREAD

**Issue by mfissehaye** [chrisvfritz/prerender-spa-plugin#192]
I am using [vuepress](https://github.com/funkhaus/vuepress) which combines vuejs with wordpress. I am trying to integrate prerender-spa-plugin. I followed instructions and I can see that prerender is trying to render the routes but I am getting the following error. And there is no clue to what went wrong.
What could have gone wrong?

``
[prerender-spa-plugin] Unable to prerender all routes!
(node:8158) UnhandledPromiseRejectionWarning: Error: net::ERR_ABORTED at http://localhost:8000/
    at navigate (.../path/inside/node-modules/Page.js:539:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:8158) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:8158) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 13.02s.
``

**Comment by Tribex** [comment]
@mfissehaye Looks like puppeteer was unable to load the route for some reason. Could you post your route configuration and `prerender-spa-plugin` configuration?

**Comment by mfissehaye** [comment]
I haven't changed much from what is default in [vuepress](https://github.com/funkhaus/vuepress)
Here it is however,

The router.js and webpack.config.js

`/* global jsonData, _get */

import VueRouter from 'vue-router'
import store from 'src/utils/store'
import Vue from 'vue'

Vue.use(VueRouter)

// load all templates in folder
const templates = require.context('src/views', true)

// build routing table
const routeTable = []
Object.keys(jsonData.routes).forEach(path => {
    let routeObject = jsonData.routes[path]

    if (typeof routeObject === 'string') {
        routeObject = {
            component: routeObject
        }
    }

    routeObject.path = path

    routeObject.name = routeObject.name || routeObject.component

    // get specified component, fallback to default
    let component = templates(`./Default.vue`)
    if (templates.keys().indexOf(`./${routeObject.component}.vue`) > -1) {
        component = templates(`./${routeObject.component}.vue`)
    }

    routeObject.component = component

    // push new route entry to table
    routeTable.push(routeObject)
})

// these two values will determine where we'll scroll on our new page
let targetScroll = null
let savedScroll = null

const router = new VueRouter({
    mode: 'history',
    routes: routeTable,
    scrollBehavior() {
        return targetScroll || { x: 0, y: 0 }
    }
})

router.beforeEach((to, from, next) => {
    // Check to see if we're going from page A to B to A again
    const firstPagePath = _get(store, 'state.referral.path', '')
    const toPath = _get(to, 'path', '')

    if (firstPagePath && toPath && firstPagePath == toPath) {
        // if we are, make our target scroll the position we saved from the first time on A
        targetScroll = savedScroll
    } else {
        // if we're not, default to the top of the page
        targetScroll = { x: 0, y: 0 }
    }

    // Save scroll from previous page
    savedScroll = { x: window.scrollX, y: window.scrollY }

    // Replace query data
    if (to.path !== from.path) {
        store.dispatch('LOAD_AND_REPLACE_QUERYDATA', { path: to.path })
    }

    // Update referral route
    if (from.name !== null) {
        store.commit('UPDATE_REFERRAL_ROUTE', from)
    }
    next()
})

export default router`

`const ExtractTextPlugin = require( 'extract-text-webpack-plugin' )
const resolve = file => path.resolve( __dirname, file )
const webpack = require( 'webpack' )
const path = require( 'path' )

const isProd = process.env.NODE_ENV === 'production'

const config = {
    entry: ['whatwg-fetch', './src/main'],
    output: {
        path: resolve( 'static' ),
        filename: isProd ? 'bundle.js' : 'bundle.dev.js'
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        'scss': ExtractTextPlugin.extract({
                            use: isProd ? 'css-loader?minimize!sass-loader?minimize' : 'css-loader!sass-loader',
                            fallback: 'vue-style-loader'
                        })
                    },
                    extractCSS: true,
                    preserveWhitespace: false,
                    postcss: [
                        require('autoprefixer')({
                            browsers: ['last 5 versions']
                        })
                    ]
                }
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/
            },
            {
                test: /\.svg$/,
                loader: 'svg-inline-loader?removeSVGTagAttrs=false'
            },
            {
                test: /\.(png|jpg|woff|woff2|eot|ttf)$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: '[name].[ext]?[hash]'
                }
            },
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    use: isProd ? 'css-loader?minimize' : 'css-loader',
                    fallback: 'vue-style-loader'
                })
            }
        ]
    },
    resolve: {
        modules: [
            path.resolve( __dirname, 'app' ),
            resolve( './' ),
            'node_modules'
        ],
        alias: {
            'vue$': isProd ? 'vue/dist/vue.min.js' : 'vue/dist/vue.esm.js'
        }
    },
    performance: {
        maxEntrypointSize: 500000,
        maxAssetSize: 500000,
        hints: isProd ? 'warning' : false
    },
    plugins: [
        new ExtractTextPlugin({
            filename: 'bundle.css'
        }),
        new webpack.ProvidePlugin({
            _get: ['lodash/get']
        })
    ]
}

// production only
if (isProd) {

    config.plugins = config.plugins.concat([
        new webpack.optimize.UglifyJsPlugin({
            compress: { warnings: false }
        })
    ])

// dev only
} else {

    config.devtool = '#source-map'
    config.plugins = config.plugins.concat([
        new webpack.EnvironmentPlugin({
            NODE_ENV: 'development'
        })
    ])

}

module.exports = config
`

**Comment by Tribex** [comment]
@mfissehaye I don't see anything in there related to `prerender-spa-plugin`. How is it configured?

**Comment by Tribex** [comment]
@mfissehaye What happens if you set `indexPath` to `index.php` like so?

```js
indexPath: path.join(__dirname, 'static', 'index.php'),
```

**Comment by Tribex** [comment]
@mfissehaye The [`consoleHandler`](https://github.com/chrisvfritz/prerender-spa-plugin#prerendererrenderer-puppeteer-options) option may be useful here, but I'm honestly not sure what you're issue is. What are the contents of `index.php`?
