### ISSUE TITLE
Feature Request: Use compiler.outputFileSystem

### ISSUE THREAD

**Issue by mwaldstein** [chrisvfritz/prerender-spa-plugin#195]
While less common, I was in a scenario where I wanted to run a development server using a production configuration using webpack-dev-middleware. While native webpack outputs went into its MemoryFS, prerender-spa-plugin still wrote to the native filesystem.

This is a low priority, but it would be nice if the compiler's outputFileSystem were used for writing if set. 

References:

 * https://webpack.js.org/api/node/#custom-file-systems
 * https://github.com/webpack/webpack-dev-middleware/blob/master/lib/fs.js#L56

**Comment by Tribex** [comment]
@mwaldstein Hmm, would it be possible to simply replace references to `fs` with `compiler.outputFileSystem`? Just curious, as that does seem like a good idea.

**Comment by mwaldstein** [comment]
I believe so - A rather cursory examination suggests that outputFileSystem has the following interface:

https://github.com/webpack/webpack/blob/eca7bad8de54c39b9cb8b138793362b8a17ac11b/lib/node/NodeOutputFileSystem.js

So I think the changes would be to change the fs.writeFile and mkdirp calls to compiler.outputFileSystem calls...

**Comment by Tribex** [comment]
Should be working now in 8d1bae9108a6962d7a9af2600760369f1f09f24a!
