### ISSUE TITLE
Unable to prerender all routes!

### ISSUE THREAD

**Issue by 484sha** [chrisvfritz/prerender-spa-plugin#196]
Hi, I have a trouble in using prerender-spa-plugin in my vue project with vue2.0 + vue-router.

This is my webpack.prod.conf.js:
new PrerenderSPAPlugin({
      staticDir: path.join(__dirname, '../dist'),
      routes: ['/home/homePage'],
    })

This is my /router/index.js:
export default new Router({
  mode: 'history',
  linkActiveClass: 'is-active',
  routes: [
    { path: '/', redirect: '/home/layout' },
    ...Home
  ]
})

This is my router under layout:
export default {
    name: 'home.layout',
    path: '/home/layout',
    component: r => require.ensure([], () => r(require('src/modules/home/layout/page/index.vue')), 'HomeLayout'),
    redirect: '/home/homePage',
    children: [
        homePage
    ]
};

My homePage is under layout.When I build:
building for production...[prerender-spa-plugin] Unable to prerender all routes!
(node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded

Can you help me?Thanks

**Comment by 484sha** [comment]
Thanks a lot.I have been resolved the problem.

**Comment by katoto** [comment]
how to ?

**Comment by 484sha** [comment]
@katoto You can use `renderAfterTime`

**Comment by cc147151** [comment]
> 您似乎需要配置渲染器。您尚未设置任何触发器以进行渲染。
> 这个将在五秒后渲染。
> 
> ```js
> 新的 PrerenderSPAPlugin（{
>   staticDir ： path。加入（__dirname，' ../dist '），
>   路线： [ ' / home / homePage ' ]，
>   renderer ： new  PrerenderSPAPlugin.PuppeteerRenderer（{
>     renderAfterTime ： 5000
>   }）
> }）
> ```您好；我得一直building for production...，然后过段时间出现提示就是路由太多；能加我个微信吗；请教一下；A1471517131；谢谢了

**Comment by lzh15378738622** [comment]
maybe my project run build it's suceess, but whatever the config routes is, the build result has only one dir in dist !

**Comment by lzh15378738622** [comment]
![Uploading image.png…]()

**Comment by lzh15378738622** [comment]
![image](https://user-images.githubusercontent.com/15136690/96554481-2d341500-12e9-11eb-89d2-0bdf1d22f960.png)
