### ISSUE TITLE
Failed to launch chrome when deploying on Heroku.

### ISSUE THREAD

**Issue by peacefulseeker** [chrisvfritz/prerender-spa-plugin#197]
Hey there.

Having issue described here:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Failing to launch prerenderer Chrome browser while deloying app to Heroku 

Or it is not a right place to post the issue here? =)

**Comment by Tribex** [comment]
Puppeteer would be the right place to state your issue, as this is just a wrapper for puppeteer.
