### ISSUE TITLE
All routes are getting prerendered to root index.html

### ISSUE THREAD

**Issue by kont-wayfinder** [chrisvfritz/prerender-spa-plugin#199]
Hi all.

I have tried using vue-meta and vue-head with prerender-spa-plugin for Open Graph meta tags.

When i ran npm run build, the prerendered routes have correct meta tags.

However, when i uploaded it to my production, all my routes are using meta tags of the ROOT index.html

Any advice?

**Comment by Tribex** [comment]
@kont-wayfinder Are you using hash-based routing or history-based routing? I can't think of much else that might be messing that up.

**Comment by kont-wayfinder** [comment]
Hi Tribex, 

I am using history-mode with vue-router. 

Also for more context, i am hosting my SPA in Amazon S3. Could the reason be that S3 is redirecting requests to the root index.html and therefore the prerendered metas are not showing? If yes, any suggestions to work around it?

**Comment by Tribex** [comment]
Possibly, is there any way to log incoming requests and determine their destination? 
I'm not familiar with using the platform in that manner.

**Comment by kont-wayfinder** [comment]
Thanks Tribex! I will look into it further and feedback if i have any solutions. Hopefully, it'll help others with similar problem.
