### ISSUE TITLE
COM Error on Windows

### ISSUE THREAD

**Issue by cannap** [chrisvfritz/prerender-spa-plugin#2]
Hi,

I get this error when i try to run npm run build from a Vue project

```
C:\Users\xxx\Desktop\Renka\page\node_modules\prerender-spa-plugin\lib\compile-to-html.js:80
                    if (stderr) throw stderr
                                ^
 SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
```

//In my Productions config

``` js
  new PrerenderSpaPlugin(
      Path.join(__dirname, '../dist'),
      [ '/' ]
    )
```

i use:
`"prerender-spa-plugin": "^1.1.0",`

Windows 10

**Comment by cannap** [comment]
i use now Debian for testing works fine

**Comment by chrisvfritz** [comment]
@cannap Thanks for reporting back! This seems to be a [PhantomJS bug on Windows](https://github.com/ariya/phantomjs/issues/14095) that they're still working out.

**Comment by chrisvfritz** [comment]
Since this is an intermittent problem, I experimented with retrying up to 10 times when an error occurs. Since then, I've been unable to reproduce this and haven't heard any other reports recently, so will consider this solved unless someone tells me otherwise. 🙂

**Comment by xianweics** [comment]
@chrisvfritz . Hi, I have the same problem.

**Comment by cnweibo** [comment]
@chrisvfritz ,i have the same issue on windows build. Unfortunately, another windows 7 pc works well, i do not know how to debug it.
