### ISSUE TITLE
The `inject`/`injectProperty` settings aren't causing an object to be injected.

### ISSUE THREAD

**Issue by sangaline** [chrisvfritz/prerender-spa-plugin#201]
I'm trying to use the plugin with the following configuration.

```javascript
    new PrerenderSPAPlugin({
      injectProperty: 'prerenderSettings',
      inject: {
        myProperty: true,
      },
    }),
```

My understanding of these settings is that `window.prerenderSettings` should be set to `{ myProperty: true }` before rendering my pages during the build. My pages are otherwise prerendering correctly, but `window.prerenderSettings` is undefined. I double checked this by adding the following code to my application.

```javascript
document.body.innerHTML = `${document.body.innerHTML}<p id="prerender-settings">${window.prerenderSettings}</p>`;
```
After building with WebPack, the generated HTML includes a `<p id="prerender-settings">undefined</p>` tag. To clarify, this is the raw HTML file that's being output by `prerender-spa-plugin`, I'm not opening the file in another web browser and causing a second tag to get injected.

This is with version 3.1.0.

**Comment by Tribex** [comment]
Hi @sangaline, prerender-spa-plugin 3.x introduces pluggable renderers with caring features. `inject` is one such feature, so you need to configure it on the specific renderer rather than the root plugin config, like so:

```javascript
new PrerenderSPAPlugin({
  renderer: PrerenderSPAPlugin.PuppeteerRenderer({
    injectProperty: 'prerenderSettings',
    inject: { myProperty: true, },
  }),
})
```

Hope that helps!

**Comment by sangaline** [comment]
Thanks for the quick answer! That's exactly what my problem was, sorry about that.

**Comment by crswll** [comment]
This snagged me but in a different way but I'll share here. I was trying...

```js
new PrerenderSPAPlugin({
  renderer: new PrerenderSPAPlugin.PuppeteerRenderer({
    injectProperty: '__PRERENDERING',
  }),
})
```
... and though I could just check like...

```js
if (window.__PRERENDERING)
```

but you NEED to set properties to `inject` or that `injectProperty` won't exist at all.

I ended up with...

```js
new PrerenderSPAPlugin({
  renderer: new PrerenderSPAPlugin.PuppeteerRenderer({
    injectProperty: 'prerederer',
    inject: {
      active: true,
    },
  }),
})
```

**Comment by Tribex** [comment]
@crswll Indeed, [this issue](https://github.com/Tribex/prerenderer/issues/11) was reported on the main prerenderer repository. I'm still of the opinion that this is the preferred behavior, but if it trips up enough people I might change it.

**Comment by crswll** [comment]
I think the naming of things threw me off. If it was like `injectProperty` and `injectValue` I think I'd have put it together quicker. Though, seeing the readme at https://github.com/Tribex/prerenderer it's much more clear. I was looking at this projects readme and it didn't click as quick.

**Comment by Tribex** [comment]
Noted. I'll probably address it in the next update then. Thanks for the input!
