### ISSUE TITLE
Old route prerenders not removed when building

### ISSUE THREAD

**Issue by jamiecarter7** [chrisvfritz/prerender-spa-plugin#202]
Hi,

So I've recently implemented this plugin and its working great!

I do appear to have one issue though. 

When I run npm run build the system renders my pages but for some reason the dist folder is not emptied and rebuilt, instead I think its just overwriting old files to new but that is leaving me with prerendered routes that are now broken because they are no longer in the data.

If I manually delete my prerendered folder and build it get the routes I expect. Is this a PSP issue? Or is this a puppeteer issue, or even a webpack issue?

**Comment by Tribex** [comment]
@jamiecarter7 This is probably a combination or webpack and our issue. Webpack doesn't always clear things out, and we have no way of knowing which routes were prerendered previously, so there's not an easy way to resolve this.

**Comment by jamiecarter7** [comment]
ok thanks!
