### ISSUE TITLE
Is there a way to keep `/dist/` prefix for all static files?

### ISSUE THREAD

**Issue by oleksiif** [chrisvfritz/prerender-spa-plugin#203]
Hey guys,
I have added this plugin to my webpack configuration and was able to prerender files. It works awesome thanks a lot!
But now i am trying to figure out how to keep _/dist/_ as part of path to all my static files including _bundle.js_ . Since i have changed _publicPath_ to `/` this prefix dropped off. Is there a way to keep it?
Thank you and sorry about this lame question.

**Comment by Tribex** [comment]
@oleksiif I believe this will have to be handled exclusively by webpack, this plugin doesn't prescribe how assets are looked up, just uses what webpack has already output.

With that in mind, I'm curious as to what sort of output you're getting? It sounds like something is misconfigured. Where is `index.html` located in your output tree?

Glad you're enjoying it!

**Comment by oleksiif** [comment]
@Tribex yeah, it is definitely relates to my webpack configuration. Here is what i have:
```
HtmlWebpackPlugin
  filename: 'dist/index.html',
PrerenderSPAPlugin
  staticDir: path.join(__dirname, 'dist'),
  indexPath: path.join(__dirname, 'dist', 'index.html'),
  outputDir: path.join(__dirname, 'prerendered'),
module level:
    entry: './app/index.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/'
    },
```
in order to prerender files i had to change `publicPath` from `/dist/` to `/` otherwise in my `bundle.js` i had content of my bare `index.html`. So now i do not have a `/dist/` as prefix to all my static files.

**Comment by Tribex** [comment]
@oleksiif Right, so basically what `publicPath` = where to find the root of your output and assets. In this case, the only correct value is `/dist/`, since that's where the root `index.html` is. If you instead output the `index.html` file to your root project directory, then you could change `publicPath` accordingly, but I would not recommend this.

**Comment by oleksiif** [comment]
@Tribex yeah so that is what i want to use, i want to set publicPath to `/dist/` but when i do it i am getting error such as:
<img width="545" alt="screen shot 2018-05-30 at 9 07 26 pm" src="https://user-images.githubusercontent.com/5115020/40725530-e27f48d2-644d-11e8-9fb3-b6d7b5e2a06f.png">
and inside /dist/bundle.js i see my content of **not** prerendered index.html.

**Comment by oleksiif** [comment]
Closing this ticket, after i set staticDir to __dirname i was able to use publicPath = `/dist/`.
Thank you.
