### ISSUE TITLE
Path -> Route in docs

### ISSUE THREAD

**Issue by robsterlini** [chrisvfritz/prerender-spa-plugin#206]
Thanks for the great work on this plugin; noticed a little hair-puller whilst adding in some path-specific prerendering today and want to save any others getting caught with the same issue.

It looks like the docs have been updated inconsistently with v3:

```
//   route: String, // Where the output file will end up (relative to outputDir)

…

renderedRoute.path = renderedRoute.originalPath
```

The commented example uses `route` whereas the example uses `path`.

**Comment by Tribex** [comment]
Ah, looks like I got mixed up a bit, I'll take a look at it as soon as I get the chance. 

Great eye, thanks!

**Comment by Tribex** [comment]
Should be fixed now.
