### ISSUE TITLE
publicPath support ?

### ISSUE THREAD

**Issue by lili21** [chrisvfritz/prerender-spa-plugin#207]
```javascript
// webpack.config.js
...
output: {
  publicPath: '//cdn.mycdn.com'
}
...
```

**Comment by lili21** [comment]
#114

**Comment by arthabus** [comment]
[this comment](https://github.com/chrisvfritz/prerender-spa-plugin/issues/215#issuecomment-415942268) helped me, maybe it would be useful to someone else as well:
