### ISSUE TITLE
how to render dynamic route, such as '/products/detail/:id'?

### ISSUE THREAD

**Issue by zhengtulymGh** [chrisvfritz/prerender-spa-plugin#210]
how to render dynamic route, such as ` '/products/detail/:id'`

**Comment by Tribex** [comment]
@zhengtulymGh You'll have to pre-generate the list of routes. There's no way we can know what they are.

**Comment by icebale** [comment]
I met the same question,now I know this plugin not support dynamic route,would you mind tell me how do you fix this problem ? My spoken English is very poor , I hope you understand what I said ,Looking forward to your reply, thanks a lot

**Comment by Tribex** [comment]
@icebale Your English is pretty good!
There's no automatic way I can think of to generate a list of routes. You'll have to build a list client-side and copy it into you webpack configuration.

**Comment by icebale** [comment]
thanks your reply,I'll try another way.

**Comment by icebale** [comment]
thanks your reply,I'll try another way.
