### ISSUE TITLE
Provide a way of obfuscating data

### ISSUE THREAD

**Issue by trajano** [chrisvfritz/prerender-spa-plugin#211]
Since bots can extract email and phone numbers, can you provide a way of obfuscating them such that it is not visible in the prerendered html and dynamically set after.

In my site which uses JQuery I have

```
function deobfuscate(e) {
    return e.replace("...", "@")
        .replace(/\.\.\./g, ".")
        .replace(/One/g, "1")
        .replace(/Two/g, "2")
        .replace(/Three/g, "3")
        .replace(/Four/g, "4")
        .replace(/Five/g, "5")
        .replace(/Six/g, "6")
        .replace(/Seven/g, "7")
        .replace(/Eight/g, "8")
        .replace(/Nine/g, "9")
        .replace(/Zero/g, "0")
}
$(function () {
    /* Deobfuscate mailto and tel links */
    $("a.obfuscate").each(function () {
        console.log("vue", Vue)
        $(this).html(deobfuscate($(this).html()))
        $(this).attr("href", deobfuscate($(this).attr("href")))
    })
}
```
And in the HTML
```
                            <a class="white-text waves-effect btn-flat obfuscate" href="mailto:archie...trajano...net"><font-awesome-icon icon="envelope" :fixed-width="true" /> archie...trajano...net</a>
                            <a class="white-text waves-effect btn-flat obfuscate" href="tel:+One FourOneSix-EightFiveSix-SixSixFiveFive"><font-awesome-icon icon="phone" :fixed-width="true"/> FourOneSix-EightFiveSix-SixSixFiveFive</a>
```

I understand it will not prevent the smarter bots from extracting the information, but at least it will force them to use more computing resources.

The issue I have with this plugin is it renders the deobfuscated result.  (I think another way of handling this is to add a global that specifies whether it is being prerendered.

**Comment by trajano** [comment]
I had to go through the source but I figured out what the README.md meant

```
    if (!window.__PRERENDER_INJECTED) {
        /* Deobfuscate mailto and tel links */
        $("a.obfuscate").each(function () {
            console.log("vue", Vue)
            $(this).html(deobfuscate($(this).html()))
            $(this).attr("href", deobfuscate($(this).attr("href")))
        })
    }
```

**Comment by Tribex** [comment]
@trajano You could also use a [`postProcess` hook](https://github.com/chrisvfritz/prerender-spa-plugin#using-the-postprocess-option) and customize the prerendered output without needing to directly modify your code.

**Comment by trajano** [comment]
the `postProcess` would actually require me to add a "obfuscate" function.  I think the `__PRERENDER_INJECTED` is better for my needs.
