### ISSUE TITLE
Vue Cli 3.0 integration with UI?

### ISSUE THREAD

**Issue by g3rd** [chrisvfritz/prerender-spa-plugin#214]
Are their plans to integrate with the 3.0 version of the cli?

**Comment by Tribex** [comment]
@g3rd I haven't planned that, no, but it's an interesting idea.

**Comment by vesper8** [comment]
sounds like an amazing idea!!! I would use it in pretty much all my vue-cli projects, which is all my projects right now :)

**Comment by cschweda** [comment]
Agreed -- integration (a plugin?) with the Vue CLI 3.0 would be fantastic.

**Comment by shredding** [comment]
Is there a way to get it working somehow atm?

**Comment by Tribex** [comment]
Sorry, just don't have the time and effort to work on this. If anyone else would like to, it's up for grabs!
