### ISSUE TITLE
lighthouse auditing and pwabuilder for app stores

### ISSUE THREAD

**Issue by vesper8** [chrisvfritz/prerender-spa-plugin#219]
I just ran a lighthouse audit on my pwa app that uses some pre-rendered routes including the landing page aka entry point and I got some odd results

it said first paint was 3 seconds even though the pre-rendered html in fact loads much faster. It also said that my app wasn't registering a service worker which seems totally false

I'm also looking into using pwabuilder to possibly create some packages and try to get my pwa onto the apple/android/app store

I made a search and it seems these questions haven't come up yet.. do you think that pre-rendering would/might have a (negative) effect on any of these processes?

**Comment by Tribex** [comment]
That's... Odd. I wouldn't expect there to be an issue with those. Did you confirm the service worker is being registered?

**Comment by vesper8** [comment]
yes it was being registered but the page wasn't being served, it seems to be related to my use of url parameters in the start_url. I created this issue but it got closed.. anyway I guess it's a problem but neither vue-cli or your package is responsible for it
