### ISSUE TITLE
[Question] absolute URL for list of routes 

### ISSUE THREAD

**Issue by lbineau** [chrisvfritz/prerender-spa-plugin#22]
Can route can be on an already hosted website ? For example if I want to use prerender-spa-plugin on another project (not even webpack for instance). Something like CasperJS you give an absolute URL.
```javascript
new PrerenderSpaPlugin(
      Path.join(__dirname, 'dist'),
      [ 'http://my-project.local/home.php' ]
    )
```
I have the following error 
```bash
Error: Invalid path:  http://my-project.local/home.php
```

**Comment by chrisvfritz** [comment]
This isn't currently possible with the plugin, but I believe [prerender.io's open source server](https://github.com/prerender/prerender) can handle this case.

**Comment by chrisvfritz** [comment]
As I think about it more, I think this is a use case that's probably outside of the scope of this project. I hope the linked service is able to meet your need!
