### ISSUE TITLE
Cannot read property 'mkdirp' of null

### ISSUE THREAD

**Issue by cbravo** [chrisvfritz/prerender-spa-plugin#223]
When trying to prerender I am getting this error.   Any thoughts?

[prerender-spa-plugin] Unable to prerender all routes!
(node:28234) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'mkdirp' of null

my webpack configuration is:
```
// == PRERENDER SPA PLUGIN == //
    new PrerenderSPAPlugin({
      // Index.html is in the root directory.
      staticDir: path.join(__dirname, 'build'),
      routes: ['/'],

      postProcess(renderedRoute) {
        // I put this here and it is in fact returning the markup of the file correctly.
        console.log('renderedRoute :', renderedRoute);
        return renderedRoute
      },

      renderer: new Renderer({
        renderAfterTime: 5000,
        headless: false,
        dumpio: true,
      }),
    }),
```
this is a simple react project. Any thoughts or clues on what might be the cause of this error?

**Comment by thiago-sylvain** [comment]
Same here, seems to be related to https://github.com/chrisvfritz/prerender-spa-plugin/commit/dcdc518f39aa3f70a65762e87129b856a2416055
@cbravo while they take a look at it you can use the 3.1.0.

**Comment by Tribex** [comment]
What version of Webpack are you using?

**Comment by thiago-sylvain** [comment]
webpack@2.1.0-beta.27 for me.

**Comment by Tribex** [comment]
@cbravo Could you try Webpack 3+? I'm not sure if Webpack 2.x has compiler.outputFileSystem.

**Comment by cbravo** [comment]
Yes this was my issue... thank you I realized I was using the wrong version and updated it and that fixed it!
