### ISSUE TITLE
Use without webpack?  Possibly via Get api?

### ISSUE THREAD

**Issue by villanus** [chrisvfritz/prerender-spa-plugin#227]
Hi.  Is it possibe to prerender pages ad-hoc without listing routes in webpack config and using a build script?   I am exploring building a large e-commerce SPA and want to prerender and save static html pages for catalog pages.   

Ideally:
User visits site - hits Nginx proxy 
Nginx proxy passes S3 bucket holding static pages previously pre-rendered
If page exists then nginx will serve the static rendered site by proxying s3
If page doesn’t exisit it proxy passes to:
Http://back-end-node-server/prerender?url=http://back-end-node-server/requested-route/
- your script generates html version (minified html)
- adds an html comment <! Prerendered on date !>
- serves the page
- saves the page to tmp directory
- uploads it to S3 bucket (overwrites existing)

Using something like this would essentially let users build a CDN based on static versions of the site.  A user could sign up for inexpensive hosting plans in different locations, setup NGINX as a reverse proxy to serve up static files from aws s3 when they exist or use the prerender url api to generate the html page.    Further, if nginx is setup to locally cache html files, they can be served from nearest location.

A user could invalidate old cached versions by deleting files on s3, and removing them from cache.
A user could also warm up the cache by writing a cron job which will wget the urls, or have their app (cms or otherwise) pre-render the pages in their blog / catalog when edits are made.  

Is this possible using your plugin?

**Comment by Tribex** [comment]
@villanus It's possible using prerenderer, which this plugin is based on: https://github.com/Tribex/prerenderer

Looking forward to seeing what you come up with!
