### ISSUE TITLE
Home page appears blank when rendering

### ISSUE THREAD

**Issue by 484sha** [chrisvfritz/prerender-spa-plugin#230]
Hello, My homePage appears blank when rendering using prerender-spa-plugin. When the network speed is slow 3G, the page blank will appear every time the request is sent. Can you help me to solve the problem? Thank you very much.
　　Here is my configuration:

　 new PrerenderSPAPlugin({
　　　staticDir: path.join(__dirname, '../dist'),
　　　routes: ['/index', '/home/about', '/home/caseDetails', '/home/joinHanYun'],
　　　postProcess (renderedRoute) {
　　　　renderedRoute.html = renderedRoute.html.replace(/(\<head\>.*?)(\<script type="text\/javascript" charset="utf-8" async="".*?\<\/script\>){1,}(.*\<\/head\>)/g, '$1$3');
　　　　return renderedRoute
　　　},
　　　renderer: new Renderer({
　　　　renderAfterTime: 5000
　　　})
　})

**Comment by 484sha** [comment]
@Tribex Thank you for your reply. I tried using `renderAfterDocumentEvent`, but it didn't look good. I didn't know if there is a problem.
　　Here is configuration:
renderer: new Renderer({
　　renderAfterDocumentEvent: 'render-event'
 })
　　Here is my main.js:
new Vue({
　　el: '#app',
　　 router,
　　 i18n,
　　store,
　　components: { App },
　　template: '<App/>',
　　mounted () {
　　　 document.dispatchEvent(new Event('render-event'))
　　}
});

**Comment by Tribex** [comment]
@484sha Good start, now wait to send the event until after all your data has loaded.
