### ISSUE TITLE
How to prerender a "*" (not-found) page.

### ISSUE THREAD

**Issue by bolajipemipo** [chrisvfritz/prerender-spa-plugin#237]
Hello,

I am using Vue.js and everything works fine.
However, I'll like to pre-render my 404 page as well which in vue goes like

`
 {
      path: '*',
     name: 'FourOhFour',
      component: FourOhFour
    }
`

Using the plugin, I'll like to add the 404 as such

`
routes: ['/', '/contact', '*'],
`

But on trying this, I get ``ERROR in [prerender-spa-plugin] Unable to prerender all routes!``

Thank you.

**Comment by Tribex** [comment]
Unfortunately that's not possible. The route has to have a physical path. The `*` means "every other possible route in the world that we haven't matched yet".
