### ISSUE TITLE
@click event not working when using prerender-spa-plugin

### ISSUE THREAD

**Issue by Vietworm** [chrisvfritz/prerender-spa-plugin#24]
I'm using [webpack template](https://github.com/vuejs-templates/webpack) and config `prerender-spa-plugin` plugin for webpack.prod.conf.js like this:

```js
new PrerenderSpaPlugin(
      // Path to compiled app
      path.join(__dirname, '../dist'),
      // List of endpoints you wish to prerender
      [ '/', '/discuss' ]
    )
```
Make more details:

```js
// Discuss.vue
export default {
     data () {
      return {
        showExplore: false
      }
    }
  }
```
```html
<div class="explore" v-if="showExplore"><p>I need your help.</p></div>
```

and html for handle event like this:

```html
<button @click="showExplore =! showExplore" class="btn btn-default">Explore</button>
```
but, when I click on the button "Explore", class `explore` still not working.

I look forward to hearing from you soon. Thanks!

**Comment by chrisvfritz** [comment]
It sounds like the client-side JS isn't taking over. Did you follow the instructions for your version of Vue under the [Caveats section](https://github.com/chrisvfritz/prerender-spa-plugin#caveats)?

**Comment by Vietworm** [comment]
I did do that before.

```js
document.addEventListener('DOMContentLoaded', () => {
  /* eslint-disable no-new */
  new Vue({
    el: '#app',
    store,
    render: h => h(App),
    router
  })
})
```
but something wrong :((

**Comment by Vietworm** [comment]
Oh, It's my mistake. I can't define id for root components.

I didn't follow the instructions for your version of Vue under the [Caveats section](https://github.com/chrisvfritz/prerender-spa-plugin#caveats).

Thanks @chrisvfritz so much for expand it to me.

**Comment by Maplesog** [comment]
@haipc Js or vue lifecycle method not work under prerender in .vue file, is the same problem with you?
