### ISSUE TITLE
Support for async postProcess

### ISSUE THREAD

**Issue by isidrok** [chrisvfritz/prerender-spa-plugin#240]
Hi, I'm writting a hook for inlining critical css after prerendering a route. For that I need postProcess to be able to return a promise, something like:
```js
 return criticalCSS(renderedRoute.html)
          .then((html) => {
            renderedRoute.html = html;
            return renderedRoute;
          });
``` 
Have just solved it in my local installation, can make  PR if you want to add this feature.

**Comment by Tribex** [comment]
Sure, how about just adjusting postProcess to wait for the promise to resolve if the output has a `.then()` function .

**Comment by isidrok** [comment]
Yeah it's pretty strightforward, just Promise.all postProcess in every rendered route,  no more changes needed.
