### ISSUE TITLE
Vue 2 - client side javascript not taking over?

### ISSUE THREAD

**Issue by congrady** [chrisvfritz/prerender-spa-plugin#25]
Hello,

Didn't want to create an issue for this, since it's most likely problem with my configuration. Maybe I misunderstood the "caveats" section. But after not being able to solve this for several hours, I decided to ask.

Using plain simple javascript inside my webpack entry (just for testing purposes), everything works fine.
Problem is when I try to use my Vue app. Nothing actually renders to the index.html (just 2 blank lines). If I open this index.html in browser, it works without any issues (Vue app renders properly).

main.js (webpack entry point):
![screen shot 2017-01-04 at 11 32 19](https://cloud.githubusercontent.com/assets/16255695/21639826/77eac848-d272-11e6-971d-300128df419b.png)

index.html:
![screen shot 2017-01-04 at 11 33 52](https://cloud.githubusercontent.com/assets/16255695/21639833/89f0db40-d272-11e6-8109-1208008f941b.png)

App.vue (only the template part):
![screen shot 2017-01-04 at 11 33 13](https://cloud.githubusercontent.com/assets/16255695/21639835/8ecf7f54-d272-11e6-89e0-349c45155923.png)

Webpack config (showing only the relevant part).
![screen shot 2017-01-04 at 11 34 35](https://cloud.githubusercontent.com/assets/16255695/21639841/929eaf6a-d272-11e6-8f52-856a9652703b.png)

I'm not using any client side routing nor webpack code splitting.

Anyone able to help? 
Even more in-depth explanation of the caveats section would be nice.

Thanks a lot!

**Comment by chrisvfritz** [comment]
Loading content on `DOMContentLoaded` means it's happening _asynchronously_. That means you'll have to use one of the advanced options to tell the plugin when to actually capture what's been rendered. I recommend something like:

``` js
document.addEventListener(() => {
  root.$mount('#oc-shop')
  document.dispatchEvent(new Event('vue-post-render'))
})
```

Then using the option:

``` js
captureAfterDocumentEvent: 'vue-post-render'
```

**Comment by jofftiquez** [comment]
`captureAfterDocumentEvent` is now `renderAfterDocumentEvent`.
