### ISSUE TITLE
window.__jsonp_ymaps_map is not a function

### ISSUE THREAD

**Issue by soroka41** [chrisvfritz/prerender-spa-plugin#250]
When using the prerender-spa-plugin plugin, an error occurs Uncaught TypeError: window.__jsonp_ymaps_map is not a function

**Comment by Tribex** [comment]
@soroka41 That would appear to be an issue with a library you're using. You may need to disable it during the prerendering process. Unfortunately, since I don't know what library is being used, I can't help you with this. :/

**Comment by soroka41** [comment]
https://github.com/PNKBizz/vue-yandex-map
