### ISSUE TITLE
Unable to prerender all routes! Wordpress Version

### ISSUE THREAD

**Issue by Livog** [chrisvfritz/prerender-spa-plugin#255]
Hello!

Having some bad luck with this one. I have my site in MAMP, and it has its domain in the host file so it can be accessed normally in the browser. I can't understand how to make this work. Tried a lot of different setups but this is my end error I think (hope).

In WordPress, it's a bit different since the first index.php file is in the route, and my assets are in the themes folder. If anyone knows how I could make this work. I'm have transformed WordPress to work as a content API, so the SPA is doing all the rendering with async components.

```
new PrerenderSPAPlugin({
            `staticDir: path.join(__dirname, 'static'), // The path to the folder where index.html is.
            indexPath: path.resolve(__dirname, '../../../index.php'),
            routes: ['/'], // List of routes to prerender.
            renderer: new PrerenderSPAPlugin.PuppeteerRenderer({
                headless: false,
                renderAfterTime: 5000,
            }),
        }),
```

I have tried using `server: { proxy: 'domain.com', port: 80 }` and that gives me
`TypeError: Cannot read property 'close' of null at PuppeteerRenderer.destroy`

Any help is appreciated =)

**Comment by Tribex** [comment]
@Livog Unfortunately, there's no way this can work with PHP, since we use our own internal webserver which can't process PHP. :(

**Comment by cschweda** [comment]
One option is to create a custom endpoint with a full (or partial -- whatever works) list of routes in the back-end to prerender on the front end.

Here's an example endpoint I'm using to return the routes (in the ```functions.php``` file on the backend):

```php
/**
 * Add 'routes' endpoint. Will use this for prerendering, eventually.
 */

add_action( 'rest_api_init', 'my_register_siteroutes');
function my_register_siteroutes() {
            
        register_rest_route( 'my_api/v1', 'routes', array(
                'methods' => 'GET',
                'callback' => 'routes', 
		)
		);
}

function routes() {
            
    $posts_list = get_posts(array('numberposts'=>'-1','post_type'=>'any','sort_order' => 'desc'));
	$post_data = array();
	$site_base = 'http://wpdev.icjia.cloud';
	
	$routes = array();
	foreach( $posts_list as $posts) {
		// remove api url
		$route = str_replace(get_home_url(),'',get_permalink($posts->ID));
		// remove trailing slash
		array_push($routes, substr_replace($route ,"",-1));
	}

    wp_reset_postdata();
	return rest_ensure_response( $routes );

}
```

And then you can query the route endpoint on the front-end in whatever pre-rendering solution you're using:

```
http://my-wordpress-site.com/wp-json/my_api/v1/routes
```
