### ISSUE TITLE
how to specify the filename of html i want to render?

### ISSUE THREAD

**Issue by qk44077907** [chrisvfritz/prerender-spa-plugin#26]
i have a directory after build without prerender-spa-plugin,like this:
-/dist/
  -/css/
     -home.css
     -contact.css
  -/js/
     -home.js
     -contact.js
  -/static/
     -xxx.png
  -home.html
  -contact.html

i found that  prerender-spa-plugin will auto search a file named 'index.html' in the directoy  specified in config, but i  wanna render multi pages in the same directory like home.html , contact.html in this case.
Need Help ,THX

**Comment by chrisvfritz** [comment]
Unfortunately, this plugin can't do that. The SPA stands for _single_-page application, meaning it's just for apps with a single `index.html` using client-side routing.
