### ISSUE TITLE
I render the first page success but the css load 2 times 

### ISSUE THREAD

**Issue by earlychen** [chrisvfritz/prerender-spa-plugin#262]

**Comment by Tribex** [comment]
@earlychen This means you're injecting the CSS with JavaScript after the page loads. You'll have to remove it manually in `postProcess`. Nothing I can do about that, unfortunately. :/

**Comment by earlychen** [comment]
tanks

**Comment by earlychen** [comment]
@Tribex

**Comment by earlychen** [comment]
thanks
