### ISSUE TITLE
Unable to prerender dynamic content (content changes on route param)

### ISSUE THREAD

**Issue by siblanco** [chrisvfritz/prerender-spa-plugin#267]
Hello, I hope y'all can help me out here.

I've been prerendering with the prerender-spa-plugin quite a while and had no issues. In my current project, I had to implement a language prefix to every route like this:

```javascript
routes: [
    {
      path: '/',
      redirect: '/en'
    },
    {
      path: '/:lang',
      name: 'home',
      component: () => import('./views/Home.vue')
    }
   etc.
```

Now my API calls depend on the $router.param.lang. Here's how I am doing it. In my App.vue:

```javascript
mounted() {
    setTimeout(() => {
      this.$root.lang = this.$route.params.lang;
    }, 150);
  },
```

The Timeout function was needed, because I was getting undefined before. In my root instance I have this: 

```javascript
export const app = new Vue({
  router,
  data: {
    lang: '',
    isLoaded: false,
    home: getData.home,
    about: getData.about,
  },
  watch: {
    lang() {
      this.isLoaded = false;
      getData.startAPI();
    },
    isLoaded() {
      if(this.isLoaded) {
        // dispatch event for prerendering
        let evt = document.createEvent('HTMLEvents');
        evt.initEvent('wpcontent-loaded', false, true);
        document.dispatchEvent(evt);
      }
    }
  },
  render: h => h(App)
})
```

Here's also where I dispatch my event for the prerender-spa-plugin - I dispatch it once the property isLoaded is true, that's once my API Calls are finished:

(my getData file)
```javascript
import {app} from '../../main'

export function startAPI() {

  setTimeout(() => {
    // check for language
    let lang = app.lang;
    if (lang === 'en') {
      lang = 'wpen';
    } else if (lang === 'fr') {
      lang = 'wp';
    }
    // set right contentURL
    contentURL = `http://example${lang}.example.com/wp-json/wp/v2/`;

    // call data
    getData('home?order=asc', home);
    getData('about?order=asc', about);
    }, 300); 

    setTimeout( () => {
      app.isLoaded = true;
    }, 3500)
}

function getData(url, array) {
  array.length = 0;
  axios.get(contentURL + url).then( response => {
    for (let data in response.data) {
      array.push(response.data[data]);
    }
  }, error => {
    console.log(error);
  });
}
```

In my App.vue I am rendering the router-view only if isLoaded is true:

```javascript
<div class="main-content" v-if="this.$root.isLoaded">
     <router-view />
 </div>
```

As you can see, I am firing the startAPI() function everytime my $route.params.lang property changes. This happens either on page-load if the visitor goes to example.com/en or example.com/fr or if the visitor changes languages by click (but this doesn't matter now).

My vue.config.js:

```javascript
configureWebpack: {
    plugins: [
      new PrerenderSPAPlugin({
        staticDir: path.join(__dirname, 'dist'),
        routes: [ '/fr', '/en', '/fr/about', '/en/about'],
        renderer: new PuppeteerRenderer({
          renderAfterDocumentEvent: 'wpcontent-loaded',
        })
      })
    ]
  },
```

My prerendered HTML files don't contain dynamic data, they are all empty unfortunately. Since I am showing my navbar outside of my router-view, my Navbar is being prerendered.

Can someone help me out?

**Comment by siblanco** [comment]
I think I've found the error: on the building process I'm getting: 

`(node:12576) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(Connection.Events.Disconnected) listeners added. Use emitter.setMaxListeners() to increase limit`

I tried to remove some routes in the configuration, did it with just /fr and /en and it worked, it prerendered all my dynamic content. 

I guess I'll find out how to increase the limit and let y'all know if it helped.

**Comment by siblanco** [comment]
They key was using maxConcurrentRoutes and delaying the event little more. It's working now, great stuff.

**Comment by zhangtemplar** [comment]
@siblanco could you elaborate your solution?

**Comment by siblanco** [comment]
@zhangtemplar here's my prerender-spa config, which is working:

`configureWebpack: {
    plugins: [
      new PrerenderSPAPlugin({
        staticDir: path.join(__dirname, 'dist'),
        routes: [ '/', '/fr', '/en'],
        renderer: new PuppeteerRenderer({
          renderAfterDocumentEvent: 'wpcontent-loaded',
          maxConcurrentRoutes: 1,
          headless: false,
          minify: {
          	collapseBooleanAttributes: true,
          	collapseWhitespace: true,
          	decodeEntities: true,
          	keepClosingSlash: true,
          	minifyCSS: true,
          	minifyJS: true,
          	sortAttributes: true
          },
        })
      })
    ]
  },`

they key is setting the maxConcurrentRoutes to 1, I don't know why, but the plugin won't prerender the dynamic content if the maxConcurrentRoutes are higher than 1.

**Comment by zhangtemplar** [comment]
@siblanco thanks, so quick 👍
