### ISSUE TITLE
prerender does not work, can't find js in parent directoy?

### ISSUE THREAD

**Issue by qk44077907** [chrisvfritz/prerender-spa-plugin#27]
my dist menu is like:
-/dist/
    -/home/
        -index.html
     home.js
in index.html i ref my js like this:<script type="text/javascript" src="../home.js?92cef4b844ea95bf9e80"></script>

the prerender didn't work.It seems that the js didn't executed by the plugin.However everything is ok if just open the html in localhost

**Comment by chrisvfritz** [comment]
You can't reference files outside of the static root (dist in your case). You'll have to place home.js in that folder as well.
