### ISSUE TITLE
correct setting prerender-spa-plugin

### ISSUE THREAD

**Issue by SkipTyler** [chrisvfritz/prerender-spa-plugin#271]
I added the necessary parameters to file webpack.prod.config.js

```
const PrerenderSPAPlugin = require('prerender-spa-plugin')
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer

const webpackConfig = merge(baseWebpackConfig, {

...

  plugins: [

        // == PRERENDER SPA PLUGIN == //
        new PrerenderSPAPlugin({
            staticDir: path.join(__dirname, '../dist'),
            routes: ['/', '/test'],

            renderer: new Renderer({
                inject: {
                    foo: 'bar'
                },
                headless: false,
                renderAfterDocumentEvent: 'render-event'
            })
        }),
...

```

Also in the file main.js

```
new Vue({
  el: '#app',
  router,
    render: h => h(App),
    mounted () {
        // You'll need this for renderAfterDocumentEvent.
        document.dispatchEvent(new Event('render-event'))
    }
})
```

and App.vue

`<div id="app" data-server-rendered="true">`

Now about the main problem. At the root(`/`) of the project, pre-rendering is working. If you go to the page `/test`, then in the source code`(ctrl + u)` will show the code from the site root(`/`).

I can't find content from `/test` in any way.

Tell me what I'm doing wrong, and how to fix the problem.

Thank!

**Comment by Tribex** [comment]
That all looks correct, what is your vue-router config?

**Comment by SkipTyler** [comment]
@Tribex I apologize.
The problem was that I ran the build version using the `serve`, and not `http-server`
