### ISSUE TITLE
It's possible to pre-render url params?

### ISSUE THREAD

**Issue by re2005** [chrisvfritz/prerender-spa-plugin#278]
Question if it's possible to pre-render an url like:

Have this in a file:
www.mywebsite.com/url-1 

And have this in another file
www.mywebsite.com/url-1 ?preRenderIsCool=true

Thanks!

**Comment by Tribex** [comment]
@re2005 Unfortunately, no, since we use the route name for generating files. That might successfully render, but the file would be unable to be requested by browsers.

**Comment by Timibadass** [comment]
Hi, @Tribex, i would like to have a route with '/path/to/:route' as one of the routes, how can i do this?

**Comment by Tribex** [comment]
@Timibadass Sorry, this is not possible, as we cannot hook into the app to know what routes are possible ahead of time.
