### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by hughsaffar** [chrisvfritz/prerender-spa-plugin#28]
I am just wondering if there is a way in order to maintain the transition effect between the routes when using preload?

**Comment by chrisvfritz** [comment]
Yes, you'd just your client-side router for internal links rather than normal links.

**Comment by hughsaffar** [comment]
Sorry but I'm kinda lost! Does it mean to exclude some sort of links from preloading?

**Comment by chrisvfritz** [comment]
Nope. The preloading should not have any effect on the preloading. If it does, it could be that you haven't correctly configured your app so that the client-side JS can take over. See the Caveats section of the readme.
