### ISSUE TITLE
Is possible to pre-render desktop view or specific viewport size?

### ISSUE THREAD

**Issue by re2005** [chrisvfritz/prerender-spa-plugin#280]
Pre-render is working really well, but I've noticed that the pre-rendered pages have always the "tablet" size.

I'm wondering if it's possible to configure what viewport size the pre-render will generate the html files?

<img width="1256" alt="render" src="https://user-images.githubusercontent.com/2920357/50215391-2651b980-0383-11e9-96d1-ff2014c19d81.png">
 
Thanks!

**Comment by Tribex** [comment]
@re2005 This shouldn't matter, unless you have JavaScript that renders different content for differently sized screens. However, you can try to configure screen size with the renderer config:

```js
renderer: new PuppeteerRenderer({
  ...
  defaultViewport: {
     width: 1920,
     height: 1080
  }
})
```

**Comment by re2005** [comment]
This is exactly my case.

Thanks you very much!
