### ISSUE TITLE
Error : [prerender-spa-plugin] Unable to prerender all routes!

### ISSUE THREAD

**Issue by saadtanvir1994** [chrisvfritz/prerender-spa-plugin#282]
I have develop the project using Yarn. 

**npm Version: 6.5.0**
**yarn Version: 1.12.3**
**vue version: 3.2.1**

**Here is the Error:**
D:\Projects\Latest\taxslips>npm run build
> taxslips@0.1.0 build D:\Projects\Latest\taxslips
> vue-cli-service build
Building for production...[prerender-spa-plugin] You appear to be using the v
2 argument-based configuration options. It's recommended that you migrate to the
 clearer object-based configuration system.
Check the documentation for more information.
\  Building for production...[prerender-spa-plugin] Unable to prerender all rout
es! ERROR  Failed to compile with 1 errors                              11:40:15 AM
 error
[prerender-spa-plugin] Unable to prerender all routes!
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taxslips@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taxslips@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Saad\AppData\Roaming\npm-cache\_logs\2018-12-21T06_40_15_9
71Z-debug.log

**Here is the file attached 2018-12-21T06_40_15_9
71Z-debug.log**
[2018-12-21T06_40_15_971Z-debug.log](https://github.com/chrisvfritz/prerender-spa-plugin/files/2701810/2018-12-21T06_40_15_971Z-debug.log)

[yarn-error.log](https://github.com/chrisvfritz/prerender-spa-plugin/files/2701803/yarn-error.log)

Prrerender-spa-plugin was working before without any error but now giving errors after again running 
```
yarn build
```
But now showing the errors. Can please anyone help?

**Comment by Tribex** [comment]
@saadtanvir1994 Could you share your config? It looks like you're using the old v2 configuration which doesn't always work as expected.

**Comment by saadtanvir1994** [comment]
@Tribex Please see the configuration file

**Comment by ryan-ds** [comment]
I am facing the same issue and when I use the setting headless: false, I can see that puppeteer hangs and the timeout triggers causing this error.

**Comment by DevArenaCN** [comment]
I have the same issue before I used the configuration file mentions in here https://github.com/chrisvfritz/prerender-spa-plugin/issues/312#issuecomment-475377922

**Comment by alvaaz** [comment]
check out here https://segmentfault.com/q/1010000016570899

**Comment by l0f5c7bf** [comment]
[prerender-spa-plugin] Unable to prerender all routes!是一个通用的错误，在我的实际解决过程中发现了我的问题所在，项目使用了cas，在预渲染过程中也没未登录重定向到cas所以出现问题，解决办法就是通过inject一个参数来识别当前是预渲染过程，在项目中判断并暂停重定向逻辑

配置
`renderer: new Renderer({
                inject: { 
                    prerender: 'domain'
                },
                renderAfterDocumentEvent: 'render-event',
                renderAfterTime: 5000,
                maxConcurrentRoutes: 5,
                headless: false
})`

项目
`
    if (
      window.__PRERENDER_INJECTED &&
      window.__PRERENDER_INJECTED.prerender === 'domain'
    ) {
      return
    }
`

**Comment by cduyzh** [comment]
> [prerender-spa-plugin] Unable to prerender all routes!是一个通用的错误，在我的实际解决过程中发现了我的问题所在，项目使用了cas，在预渲染过程中由于未登录重定向到cas所以出现问题，解决办法就是通过inject一个参数来识别当前是预渲染过程，在项目中判断并暂停重定向逻辑
> 
> 配置
> `renderer: new Renderer({ inject: { prerender: 'domain' }, renderAfterDocumentEvent: 'render-event', renderAfterTime: 5000, maxConcurrentRoutes: 5, headless: false })`
> 
> 项目
> `if ( window.__PRERENDER_INJECTED && window.__PRERENDER_INJECTED.prerender === 'domain' ) { return }`

这个方法给了我一个灵感，我试着在最外层组件的生命周期在进行一些请求操作之前判断是否是预渲染然后return,现在打包已经正常的，之前是偶尔正常偶尔失败，失败居多，所以现在预渲染是否成功与否可能与全局error有关，因为我项目中的页面，即使接口请求失败了也不会出现重定向的操作。

**Comment by WormGirl** [comment]
我也抛了这个错误  加载了facebook SDK, 但是打包服务器不能访问外网，就一直报这个错，设置inject判断一下跳过加载facebook SDK就好了，预加载页面上似乎不能抛出错误呢，抛出就跪了，有没有可能设置一个事件，事件触发，然后直接生成页面，而不是开始生成页面，因为预渲染等待加载某个js没有必要吧，抛错也直接生成可以么，这样就算页面真的有错我也能自己排查出来，现在这样如果不是对这个插件有一定的了解，很难找到问题所在，建议大大优化下呢，非常感谢，这个工具很nice 👍👍👍

**Comment by SageSanyue** [comment]
```headless: true ```
It helps me!
Reference: 
https://juejin.cn/post/6844904178326700045#comment
"在mac下设置了 headless: false 导致提示 Unable to prerender all routes! google 了一堆，告诉我说不能使用路由懒加载，其实造成这个报错的原因有很多，我是设置了headless: true 就好了 !"
