### ISSUE TITLE
Error: Unable to prerender all routes When there are many routes

### ISSUE THREAD

**Issue by VincentMRA** [chrisvfritz/prerender-spa-plugin#283]
Hi!

When using puppeteer renderer, using very few routes (less than 10), it builds perfectly.
When I ask to compile somewhere between 10 and 20 routes, sometimes it fails with the "unable to preprender all routes" and when i switch the order of the routes, sometimes it does build.

When i use more than 20 routes, it fails always with the unable to 'prerender all routes' error. 

However, when building each route individually, it builds perfectly.

Any suggestion on how to solve this?

Cheers,

**Comment by Tribex** [comment]
@VincentMRA Not sure, but you can limit the number of parallel routes using `maxConcurrentRoutes: 10,`

**Comment by VincentMRA** [comment]
Oh yes, this works !! 
Thank you so much!

It does build really slowly now.

Any way to speed up the process?

Cheers,

Vincent

**Comment by VincentMRA** [comment]
Hi again!

So the solution is succesfull, however the more pages i add. the less concurrent routes I can allow.
Is this normal behaviour?
Is this due to my machine having a hard time managing the total number of routes? or is this due to the plugin showing some internal issues?

Best,

Vincent
