### ISSUE TITLE
baseUrl use a CDN path prerender-spa doesn't work

### ISSUE THREAD

**Issue by itboos** [chrisvfritz/prerender-spa-plugin#284]
### use vue-cli 3 
    Here's the vue.config.js I'm using:
```javascript
   {
     ...
     baseUrl: process.env.NODE_ENV === 'production'
           ? 'https://js.mycdnhost.com/web/'
            : '/',
   }
```

When our Project release，our index.html file will in   www.a.com,  but out our js、css file  we want use cdn server to improve experience, but when the baseUrl  use a CDN path,  vue-cli-plugin-prerender-spa d donesn't work, and it donesn't  show any error. 

And if the baseUrl: '/'  , It works well， what  should  I do?    I think is is a common case to do that, which js, css in a CDN server,  index.html in another server.  Someone encountered in this situation like me ? 

Any help would be appreciated.

**Comment by Tribex** [comment]
@itboos Yes, we have encountered this issue before, but honestly don't have a good solution. Sorry. :/

**Comment by itboos** [comment]
I got a clumsy solution.

  Firstly, I think the prerender-spa dones't works because it can't find the static file like js, css.
  (Because the CDN path dones't has those files). I support if on the building procress, the static file has in the CDN, then it can find the files, and the  prerender-spa may works.

  So, I execute npm run build, then upload the static file to our CDN, then execute npm run build again, but it still dones't work(I am sure the file is in the CDN, I can get it use the full path in the browser).

  I think prerender-spa plugin should used a local server to render to Dom, so, I change the cdn path as '//127.0.0.1', and it is really works,
  but in the html file, the cdn path all became '127.0.0.0', and this is dones't want. 

  So, After the build, I can use a task to replace all the '127.0.0.1' to our CDN path.
  And it works well, I hope this may give some help for other's who use the CDN path.

 baseUr use a local host
```javascript
// vue.config.js
baseUrl: '//127.0.0.1:8000/'
```

 modify the package.json

```json
"scripts": {
  "build": "vue-cli-service build && node replaceCDN.js",
}
```
the replaceCDN.js

``` javascript
/*
 * @desc: Deep traversal directory, replace the '//127.0.0.1:8000/' to our CDN path
 */
const fs = require('fs')
const path = require('path')
// the production path
const relativePath = '/dist'
// our js CDN path
const cdnPath = 'https://js.cdnhost.com/web/'
// get the full path
const root = path.join(__dirname) + relativePath

readDirSync(root)

/**
 * Deep traversal directory 
 * @param {*} path directory we want traversal
 */
function readDirSync (path) {
  var pa = fs.readdirSync(path)
  // console.log('pa:', pa)
  pa.forEach(function (ele, index) {
    var info = fs.statSync(path + '/' + ele)
    if (info.isDirectory()) {
      // console.log("dir: " + ele)
      readDirSync(path + '/' + ele)
    } else {
      var filePath = path + '/' + ele
      // find all .html, .js file
      var fileNameReg = /\.html$|.js$/ig
      var shouldFormat = fileNameReg.test(filePath)
      if (shouldFormat) {
        // read the .js and .html file and use regular expression replace the 127.0.0.1 to our CDN path.
        readFile(filePath)
      }
    }
  })
}

// readFile(filename,[options],callback);

/**
 * filename, Required，the full filePath
 * [options],optional
 * callback
 */

function readFile (filename) {
  fs.readFile(filename, { flag: 'r+', encoding: 'utf8' }, function (err, data) {
    if (err) {
      console.error(err)
    }
    var replacedContent = data.replace(/\/\/127.0.0.1:8000\//g, cdnPath)
    // write file
    writeFile(filename, replacedContent)
  })
}

/**
 * filename, Required，filePath
 * str
 * [options],flag,mode w(write), encoding
 * callback
 */

function writeFile (filename, str) {
  var wData = Buffer.from(str)
  fs.writeFile(filename, wData, { flag: 'w' }, function (err) {
    if (err) {
      console.error(err)
    } else {
      console.log(logFileName(filename) + '...write success...')
    }
  })
}
/**
 * @param {Sting} fullPath
 *  return the file's short name
 */
function logFileName (fullPath) {
  var posArr = []
  var pos = fullPath.indexOf('/')
  while (pos !== -1) {
    posArr.push(pos)
    pos = fullPath.indexOf('/', pos + 1)
  }
  // console.log(posArr)
  var len = posArr.length
  var subIndex = len - 3 >= 0 ? len - 3 : 0
  // substr： /dist/pc/index.html
  return fullPath.substr(posArr[subIndex])
}

```
