### ISSUE TITLE
Documentation for catch-all page

### ISSUE THREAD

**Issue by jdrydn** [chrisvfritz/prerender-spa-plugin#29]
I've just setup a clean Vue 2 project with `vue init`, and added `prerender-spa-plugin` to my production webpack config like so:

```
new PrerenderSpaPlugin(
  // Absolute path to compiled SPA
  baseWebpackConfig.output.path,
  // List of routes to prerender
  [ '/' ]
),
```

And running `$ npm run build` successfully build the Vue app, CSS & JS and indeed pre-renders the homepage. Excellent!

So next I added `vue-router`, added a page & a route for `/about`, and added that to my list of routes to prerender. `$ npm run build` and `dist/about/index.html` was created. Excellent!

What I don't understand is what file I should point users to when I want to client-side render? For instance, I could pre-render the homepage and the about page, but if someone visits `/login` and I want to client-side render the login page, which page in my `dist/` folder should I fallback to?

For reference, my `dist/` folder looks like:

```
dist/
  about/index.html
  static/...
  index.html
```

I feel like I'm missing a `page.html` that would be the non prerendered SPA HTML file that would be served for "all other routes"?

Thanks,

**Comment by chrisvfritz** [comment]
This is outside the responsibility of the plugin. When I've wanted this in the past, I just have Webpack create an extra copy of my HTML template as `fallback.html` or similar.

**Comment by jdrydn** [comment]
Yeah, I figured this was outside the scope of this plugin, I just wanted to be certain.

Perhaps a note in the caveats section of your README explaining "*if you pre-render the root (`/`) the `index.html` page will be overridden, so you should use webpack to create another `fallback.html`*..."? Your docs are absolutely fab otherwise 😍 

Oh, and 👍  for this plugin, it's ace!

**Comment by chrisvfritz** [comment]
Yeah, I agree that'd make a great addition to the documentation. I just retitled and opened this issue. I'll update the docs when it's not 3am. 😄  Glad you're enjoying it!

**Comment by drewlustro** [comment]
Let me know if you plan to handle this, @chrisvfritz 👍 👍

**Comment by chrisvfritz** [comment]
@drewlustro No, feel free to. 😅

**Comment by jdrydn** [comment]
I've been poked a few times about how I "solved" this, with two people quoting this issue directly, so I'll pop this here:

I duplicated the `HtmlWebpackPlugin` plugin in my production [webpack config](https://github.com/vuejs-templates/webpack) to generate `404.html` as well as `index.html`, and then I would serve that 404 page on non-prerendered routes and Vue (and [vue-router](https://github.com/vuejs/vue-router)) takes over!

![screen shot 2017-07-19 at 12 57 37](https://user-images.githubusercontent.com/406967/28365926-6ca92ad8-6c82-11e7-870e-f468a118d1ef.png)

**Comment by drewlustro** [comment]
@jdrydn - Excellent work!

If you want to add this to the documentation `README.md` in a PR, by all means ;)

**Comment by stereobooster** [comment]
The fallback page can be named `200.html`. Some static host providers use this convention, for example, surge.sh (actually I do not know any other examples). `200.html` for 200 response, `404.html` for 404 response.
