### ISSUE TITLE
Unable to prerender all routes - with many routes

### ISSUE THREAD

**Issue by VincentMRA** [chrisvfritz/prerender-spa-plugin#290]
Hi!

I already posted an issue regarding this problem, which was closed a little while ago.
[https://github.com/chrisvfritz/prerender-spa-plugin/issues/283](url)

The Solution suggested there to use MaxConcurrentRoutes, was helpfull until today.
Today i seem to be unable to render more than about 20 routes. even though i am restricting the number of concurrent routes.
It almost looks like the maxConcurrentRoutes isn't working anymore.

Could you please help me out?

Cheers,

Vincent

**Comment by Meg4mi** [comment]
Was having the exact same issue. (was caused by a timeout during pupeeter.goto)
Try this setting  (navigationOptions) => 
```
 renderer: new Renderer({
          navigationOptions: { timeout: 0 },
          timeout: 0,
        }),
```

It works for me.

Let me know if it solve your problem.

**Comment by VincentMRA** [comment]
@Meg4mi  You are a life saver!!!
This works for me too.
It still needs the MaxConcurrentRoutes though, and with it set to 20 it takes forever for 500 routes (After 20min it was not done yet) but i guess i will tweak this number a bit to see up to where i can push it :)

Thank you sooooo much for your help!!!!
