### ISSUE TITLE
ERROR in [prerender-spa-plugin] Unable to prerender all routes!

### ISSUE THREAD

**Issue by Tanchaochao** [chrisvfritz/prerender-spa-plugin#293]
`const PrerenderSPAPlugin = require('prerender-spa-plugin'); // 预渲染
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer;

    new PrerenderSPAPlugin({
      staticDir: path.join(__dirname, '../dist'),
      routes: ['/', '/login', '/register', '/goodsList', '/goodsDetail', '/inquiryList', '/inquiryDetail'],
      renderer: new Renderer({
        inject: {
          foo: 'bar'
        },
        headless: false,
        maxConcurrentRoutes: 15,
        renderAfterDocumentEvent: 'render-event',
        renderAfterTime: 5000
      })
    }),`

The routes are more than seven, and sometimes the six routers are also wrong

ERROR in [prerender-spa-plugin] Unable to prerender all routes!

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hxyd-fro-web-portal@1.0.0 build: `node build/build.js "http://192.168.5.252:9999" "portal-test" "test"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hxyd-fro-web-portal@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-28T07_41_00_356Z-debug.log

Any insight would be fantastic! Thanks!

**Comment by eugle** [comment]
Same problem
