### ISSUE TITLE
¿Vue example?

### ISSUE THREAD

**Issue by tobeorla** [chrisvfritz/prerender-spa-plugin#3]
¡Hi!
¡Thank you for making this lib!

I would like to know if an example with vue could be possible :)

**Comment by chrisvfritz** [comment]
There's [this example](https://github.com/chrisvfritz/prerender-spa-plugin-vue-demo/commit/077a49a97ca6a622933ca50d7b7dcdccd89044e4) and I'd like to put something simple together for Vue in the future. Just have to find the time. 😃

**Comment by tobeorla** [comment]
¡Cool!¡TY!
