### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by DannyAziz** [chrisvfritz/prerender-spa-plugin#305]
Using `@prerenderer/renderer-jsdom` I get the error that `fetch is not defined` - I've gone through the repo for `jsdom` and tried to integrate `whatwg-fetch` but can't get it to work

Has anyone solved this?

**Comment by Tribex** [comment]
Hi Danny, you'll probably need to include a fetch polyfill. Jsdom only supports native Node functions + basic DOM shims.
