### ISSUE TITLE
captureAfterTime: 10000,

### ISSUE THREAD

**Issue by simonestic** [chrisvfritz/prerender-spa-plugin#306]
Hi. i have a question about using "captureAfterTime " option,
i know using this option is not recommended but after spending lots of time experimenting with " captureAfterElementExists" and "captureAfterDocumentEvent" i found out that the best situation for my case is to use  "captureAfterTime ". but i'm having another question now about the amount of time i set for this option and the effect of it on the SEO of the site ( actually using this plugin for seo only ).
now it's set to 10000ms ( 10 seconds ) . is it bad for SEO? does it make any difference? 

thanks in advance for answering  my question.

**Comment by Tribex** [comment]
It will have no effect on SEO, but will take longer to render.
