### ISSUE TITLE
If I add permission authentication, pages that require permissions will not be rendered.

### ISSUE THREAD

**Issue by huangyangteng** [chrisvfritz/prerender-spa-plugin#311]
First of all,this is the configuration of my route.

![image](https://user-images.githubusercontent.com/20508390/54341267-6c61a500-4674-11e9-90a5-2cd472284808.png)

Then,this is the configuration of my plugin.

![image-20190314162020429](https://ws2.sinaimg.cn/large/006tKfTcgy1g12ech5jz5j30hf04q74r.jpg)

**Comment by Tribex** [comment]
Unfortunately there's no way to get around this, as we can't know what permissions are prior to bootstrapping the JavaScript for the page.
