### ISSUE TITLE
Error: Build failing using prerender-spa-plugin

### ISSUE THREAD

**Issue by bobaekang** [chrisvfritz/prerender-spa-plugin#312]
Build fails when I attempt to `npm run build` when using `prerender-spa-plugin`. It looks like I'm facing pretty much the same issue described in #282. 

I've also tried adding `data-server-rendered="true"` attribute to the root app element [as suggested](https://github.com/chrisvfritz/prerender-spa-plugin#vuejs-notes), but this did no good.

I'm on Windows 10 and my project setting is:
* node: 10.13.0
* npm: 6.4.1
* vue: 2.6.9
* @vue/cli-service: 3.5.1

The error mesage from `npm run build` command:
>   ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! a@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the a@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

My `vue.config.js`:
```js
var path = require('path')
const PrerenderSPAPlugin = require('prerender-spa-plugin')

module.exports = {
  configureWebpack: config => {
    if (process.env.NODE_ENV === 'production') {
      config.plugins = [
        new PrerenderSPAPlugin({
          staticDir: path.join(__dirname, 'dist'),
          routes: ['/', '/about'],
          renderer: new Renderer({
            renderAfterElementExists: '#app',
            renderAfterTime: 5000
          })
        })
      ]
    }
  }
}

```

My `package.json`:
```json
{
  "name": "a",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@vue/eslint-config-prettier": "^4.0.1",
    "axios": "^0.18.0",
    "file-saver": "^2.0.1",
    "form-data": "^2.3.3",
    "js-yaml": "^3.12.1",
    "jsdom": "^13.2.0",
    "markdown-it": "^8.4.2",
    "markdown-it-anchor": "^5.0.2",
    "markdown-it-footnote": "^3.0.1",
    "nprogress": "^0.2.0",
    "prerender-spa-plugin": "^3.4.0",
    "turndown": "^5.0.3",
    "turndown-plugin-gfm": "^1.0.2",
    "vue": "^2.6.9",
    "vue-router": "^3.0.2",
    "vue-social-sharing": "^2.4.2",
    "vuetify": "^1.5.2",
    "vuex": "^3.1.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.4.1",
    "@vue/cli-plugin-eslint": "^3.4.1",
    "@vue/cli-service": "^3.4.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.14.1",
    "eslint-plugin-vue": "^5.2.2",
    "vue-cli-plugin-vuetify": "^0.4.6",
    "vue-template-compiler": "^2.6.9"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

**Comment by bobaekang** [comment]
In fact, it seems that I cannot even reproduce [the examples provided in the current repository](https://github.com/chrisvfritz/prerender-spa-plugin/tree/master/examples).  So far, I've tried to build `vanilla-simple` and `vue2-webpack-router` and failed both times.

An interesting observation is that trying `vanilla-simple` or `vue2-webpack-router` gave me a different error message, probabilty due to not using Vue CLI:
>  95% emittingevents.js:167
      throw er; // Unhandled 'error' event
      ^

> Error: listen EADDRINUSE :::8001
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Function.listen ([redacted]\prerender-examples\vue2-webpack-router\node_modules\express\lib\application.js:618:24)
    at Promise ([redacted]\prerender-examples\vue2-webpack-router\node_modules\@prerenderer\prerenderer\es6\server.js:39:35)
    at new Promise (<anonymous>)
    at Server.initialize ([redacted]\prerender-examples\vue2-webpack-router\node_modules\@prerenderer\prerenderer\es6\server.js:38:12)
    at Prerenderer.initialize ([redacted]\prerender-examples\vue2-webpack-router\node_modules\@prerenderer\prerenderer\es6\index.js:80:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prerender-spa-plugin-example-vue2-webpack-router@1.0.0 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prerender-spa-plugin-example-vue2-webpack-router@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

At this point, I'm even wondering if this has something to do with trying it on Windows 10. I'd appreciate any comments on this. Thank you in advance!

**Comment by bobaekang** [comment]
Closing this issue because of the successful prerendering of the original app. Using the code in [maoberlenher/how-to-pre-render-vue-powered-websites-with-webpack](https://github.com/maoberlehner/how-to-pre-render-vue-powered-websites-with-webpack) helped.

New project setting:
* node: 10.15.3
* npm: 6.9.0
* vue: 2.6.10
* @vue/cli-service: 3.5.1

Revised `vue.config.js`:
```js
const path = require('path')
const PrerenderSPAPlugin = require('prerender-spa-plugin')

const productionPlugins = [
  new PrerenderSPAPlugin({
    staticDir: path.join(__dirname, `dist`),
    routes: [`/`, `/about`],
    postProcess(renderedRoute) {
      renderedRoute.html = renderedRoute.html
        .replace(/<script (.*?)>/g, `<script $1 defer>`)
        .replace(`id="app"`, `id="app" data-server-rendered="true"`)

      return renderedRoute
    },
    renderer: new PrerenderSPAPlugin.PuppeteerRenderer({
      inject: {},
      renderAfterElementExists: `[data-view]`
    })
  })
]

module.exports = {
  lintOnSave: false,
  configureWebpack: config => {
    if (process.env.NODE_ENV === `production`) {
      config.plugins.push(...productionPlugins)
    }
  }
}
```

Revised `package.json`:
```json
{
  "name": "a",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@vue/eslint-config-prettier": "^4.0.1",
    "axios": "^0.18.0",
    "file-saver": "^2.0.1",
    "form-data": "^2.3.3",
    "js-yaml": "^3.12.1",
    "jsdom": "^13.2.0",
    "markdown-it": "^8.4.2",
    "markdown-it-anchor": "^5.0.2",
    "markdown-it-footnote": "^3.0.1",
    "nprogress": "^0.2.0",
    "prerender-spa-plugin": "^3.4.0",
    "turndown": "^5.0.3",
    "turndown-plugin-gfm": "^1.0.2",
    "vue": "^2.6.10",
    "vue-router": "^3.0.2",
    "vue-social-sharing": "^2.4.2",
    "vuetify": "^1.5.7",
    "vuex": "^3.1.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.4.1",
    "@vue/cli-plugin-eslint": "^3.4.1",
    "@vue/cli-service": "^3.4.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.15.3",
    "eslint-plugin-vue": "^5.2.2",
    "vue-cli-plugin-vuetify": "^0.4.6",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

Revised `main.js`:
```js
import Vue from 'vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
// importing stuff...

import App from './App.vue'
import router from './router'
import store from './store/index'

// from maoberlenher/how-to-pre-render-vue-powered-websites-with-webpack
import injectInitialState from './services/inject-initial-state' 

Vue.config.productionTip = false
Vue.use(Vuetify)
// using stuff...

const app = new Vue({
  router,
  store,
  render: h => h(App)
})

if (window.__INITIAL_STATE__) store.replaceState(window.__INITIAL_STATE__)

router.beforeResolve(async (to, from, next) => {
  try {
    const components = router.getMatchedComponents(to)
    await Promise.all(components.map(x => x.fetch && x.fetch({ store })))

    if (window.__PRERENDER_INJECTED) injectInitialState(store.state)
  } catch (error) {
    console.log(error)
  }
  return next()
})

app.$mount(`#app`)
```

Revised `views/Home.vue` and `views/About.vue`
```vue
<template>
  <div data-view> <!-- adding "data-view" here -->
     <!-- omitted -->
  </div>
</template>

<script>
// omitted
</script>
```

**Comment by noelc10** [comment]
@bobaekang I follow your method but with webpack.mix.js because I have a laravel-vue app. Still having the same issue :(
Any idea on how to implement it with laravel-vue?
I'm using [vue-cli-plugin-prerender-spa](https://github.com/SolarLiner/vue-cli-plugin-prerender-spa)

Thank you.

**Comment by noelc10** [comment]
Hello @bobaekang, I see you aren't a Laravel user.

I have tried `prerender-spa-plugin` with the same setup from the given example [here](https://github.com/chrisvfritz/prerender-spa-plugin/tree/master/examples/vue2-webpack-router) but applied in webpack.mix.js, but It results in the same error and generate index.html files inside `dist` folder with route-named folders contains compilation errors or some kind.

**Comment by noelc10** [comment]
Its okay @bobaekang, I'll post my webpack.mix.js and error screenshots links here later.

Thanks for the responses. God bless.

**Comment by noelc10** [comment]
@bobaekang sorry for the late response, I'm busy on work.

here's my webpack.mix.js content:

```
const mix = require("laravel-mix");

// const webpack = require('webpack');
const path = require("path");
const fs = require('fs')
// const HtmlWebpackPlugin = require('html-webpack-plugin');
const PrerenderSPAPlugin = require('prerender-spa-plugin');
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer;
// const VueLoaderPlugin = require('vue-loader/lib/plugin');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.sourceMaps(true, "source-map")
    .js("resources/js/app.js", "public/js")
    .sass("resources/sass/app.scss", "public/css");

mix.disableSuccessNotifications();

mix.webpackConfig({
    plugins: [
        new PrerenderSPAPlugin({
            staticDir: path.join(__dirname, "dist"),
            outputDir: path.join(__dirname, 'dist'),
            routes: ["/", "/bulletin-board","/top-requests","/about-us","/sign-in"],
            postProcess(renderedRoute) {
                renderedRoute.html = renderedRoute.html
                    .replace(/<script (.*?)>/g, `<script $1 defer>`)
                    .replace(`id="app"`, `id="app" data-server-rendered="true"`);

                return renderedRoute;
            },
            renderer: new Renderer({
                headless: true,
                // renderAfterElementExists: `[data-view]`,
                renderAfterTime: 5000,
                args: ['--no-sandbox', '--disable-setuid-sandbox']
            })
        })
    ]
});

```

Hope you find someone who can help me, thank you again.

**Comment by SageSanyue** [comment]
```headless: true ```
It helps me!
Reference: 
https://juejin.cn/post/6844904178326700045#comment
"在mac下设置了 headless: false 导致提示 Unable to prerender all routes! google 了一堆，告诉我说不能使用路由懒加载，其实造成这个报错的原因有很多，我是设置了headless: true 就好了 !"
