### ISSUE TITLE
Webpack publicPath with React SPA

### ISSUE THREAD

**Issue by gapsaras** [chrisvfritz/prerender-spa-plugin#315]
Recently I want to use prerender-spa-plugin in my website, and tried with demos in README, but find this problem:

My webpack config:
```
webpackConfig.output = {
    filename: `[name].[${project.compiler_hash_type}].js`,
    path: '/dist/',
    publicPath: '/dist/',
    chunkFilename: `[name].[${project.compiler_hash_type}].js`
}

...
new PrerenderSPAPlugin(
            {
                staticDir: '/dist/',
                routes: ['/'],
                renderer: new Renderer({
                    renderAfterTime: 30000,
                    inject: {},
                    headless: false
                }),
                postProcess(renderedRoute) {
                    if (renderedRoute.originalRoute === '/')
                      renderedRoute.outputPath = project.paths.dist('index.prerendered.html')
                  
                    return renderedRoute
                  },
            }
        )
```

But when I build, I got not prerendered content in `index.prerendered.html` like this:
```html
<!DOCTYPE html><html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="shortcut icon" href="/dist/favicon.ico"><link href="/dist/app.38ae0f792f3bca9d9d4c4b2d9db13952.css" rel="stylesheet"></head>
<body>
<div id="root"></div>
<script type="text/javascript" src="/dist/vendor.fa02b21a6ead90a3ef8d.js"></script><script type="text/javascript" src="/dist/app.7ac1ce5b33c347a91ecc.js"></script>

</body></html>
```

**I debug the puppeteer browser window, console says: 404 error for all static resources such as  `app.*.js`, `vendor.*.js` and `images.*` referred by css file.**

So I searched, and know this plugin will start a local server after webpack build process, and use the staticDir as the root,  whick cause the 404 errors because `index.prerendered.html` and other static resource are in the same directory `/dist/`, but `<script type="text/javascript" src="/dist/vendor.fa02b21a6ead90a3ef8d.js">` is a relative path.

I want to know does  this plugin provide a method that I didn't know to solve this problem, or is there a workaround?

**Comment by qq419499973** [comment]
whether could provide an API to support non-root directories?

**Comment by JoshTheDerf** [comment]
@qq419499973 @gapsaras It sounds as if your index.html file is being output in the wrong place, or you've misconfigured the build step to assume that index.html is outside of /dist/. Either way, you'll need to sort out your webpack settings, as prerender-spa-plugin is behaving as it should for this case, unfortunately.
