### ISSUE TITLE
Puppeteer not correctly rendering meta

### ISSUE THREAD

**Issue by covertninesam** [chrisvfritz/prerender-spa-plugin#319]
I have written some javascript to dynamically add meta to the head of a document based on what it gets from the server. However, when I use the puppeteer renderer, I end up with a bunch of meta tags without the property type defined (only content).

I thought it might be a bug in my code, but it works with the JSDOM renderer, so it can't be just a bug in my code.

Here's what I'm using to update the meta.

```
export const mutateMeta = {
  updateSingle(meta, tagname = "meta") {
    let proptype = Object.keys(meta)[0];
    let property = meta[proptype];
    let valuetype = Object.keys(meta)[1];
    let value = meta[valuetype];
    let tag;
    if (document.querySelector(`${tagname}[${proptype}="${property}"]`)) {
      tag = document.querySelector(`${tagname}[${proptype}="${property}"]`);
    } else {
      tag = document.createElement(tagname);
      tag.setAttribute(valuetype, value);
    }
    tag.setAttribute(valuetype, value);
    document.getElementsByTagName("head")[0].appendChild(tag);
  }
};
```

Thanks!
Sam

**Comment by JoshTheDerf** [comment]
@covertninesam I'm going to consider this a https://github.com/GoogleChrome/puppeteer issue. :/
