### ISSUE TITLE
How to use nested routes properly

### ISSUE THREAD

**Issue by IEfucker** [chrisvfritz/prerender-spa-plugin#321]
I have a problem with using nested routes, some children routes missed
Demo code below

change main.js
https://github.com/chrisvfritz/prerender-spa-plugin/blob/master/examples/vue2-webpack-router/src/main.js#L7

to

```
const Layout = { template: '<div><router-view></router-view></div>' }
const Home = { template: '<div><h2>Home Page</h2></div>' }
const About = { template: '<div><h2>About Page</h2></div>' }
const Contact = { template: '<div><h2>Contact Page</h2></div>' }

const routes = [
  { path: '/', component: Layout,children:[
    { path: '/home', component: Home },
    { path: '/about', component: About },
    { path: '/contact', component: Contact }
  ]}
]
```

change App.vue
https://github.com/chrisvfritz/prerender-spa-plugin/blob/master/examples/vue2-webpack-router/src/App.vue#L5

to

```
<p>
    <router-link to="/home">Home</router-link>
    <router-link to="/about">About</router-link>
    <router-link to="/contact">Contact</router-link>
</p>
```

I donot get dist like
./dist
 --./home
 --./about
 --./contact

but get this:

![RTX截图未命名](https://user-images.githubusercontent.com/3446876/58318018-8f18f280-7e49-11e9-8ac9-1bd642881c94.png)

home is missed, and 'Home Page' is only found in build.js

Is my nested routes is illegal?

**Comment by JoshTheDerf** [comment]
@IEfucker What is your webpack configuration? Have you added those routes to it?

**Comment by IEfucker** [comment]
@JoshTheDerf Oh, thanks.
That's the problem. Sorry
I would close this issue, and try this in my project later
