### ISSUE TITLE
Root index.html file is being copied to all routes

### ISSUE THREAD

**Issue by dhruvbhatia7** [chrisvfritz/prerender-spa-plugin#325]
Hi,
My index.html file is being copied to all the routes. I have looked at related bugs, but none of those fixes have worked for me. Here is my code:

```
const path = require('path');
const PrerenderSPAPlugin = require('prerender-spa-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer

module.exports = {
  outputDir: './dist',
  configureWebpack: {
    plugins: [
      new HtmlWebpackPlugin({
        filename: path.resolve(__dirname, 'index.html')
      }),
      new PrerenderSPAPlugin({
          // Required - The path to the webpack-outputted app to prerender.
          staticDir: path.join(__dirname, './dist'),
          // Required - Routes to render.
          routes: ['/', '/learn', '/practice', '/companies'],
          postProcess (renderedRoute) {
            // Ignore any redirects.
            renderedRoute.route = renderedRoute.originalRoute
            // Basic whitespace removal. (Don't use this in production.)
            renderedRoute.html = renderedRoute.html.split(/>[\s]+</gmi).join('><')
            // Remove /index.html from the output path if the dir name ends with a .html file extension.
            // For example: /dist/dir/special.html/index.html -> /dist/dir/special.html
            if (renderedRoute.route.endsWith('.html')) {
              renderedRoute.outputPath = path.join(__dirname, 'dist', renderedRoute.route)
            }
    
            return renderedRoute
          },    
      })
    ]
  }
}
```

I am using firebase for hosting. 

Would really appreciate any help as I've been stuck on this for more than a day :(

**Comment by JoshTheDerf** [comment]
@dhruvbhatia7 It looks as if you forgot to configure your renderer to tell it _when_ to render. See here: https://github.com/chrisvfritz/prerender-spa-plugin#prerendererrenderer-puppeteer-options (The `renderAfter*` hooks.)

**Comment by adrianObel** [comment]
@JoshTheDerf care to expand? I'm facing the same issue - directly using the "advanced" example will indeed rename `/about/index.html` -> `/about.html` but the resulting html is no longer the about page but a clone of `index.html`. Thanks :)

**Comment by dhruvbhatia7** [comment]
Thanks @JoshTheDerf

@adrianObel I was facing the exact same issue. Apparently, I had included an external library (mixpanel) that was interfering with spa-prerender-plugin's ability to function correctly. The moment I removed it, everything worked like a charm. 

I would suggest checking for all such issues once more (external libraries, dependencies, etc.). Good luck!
