### ISSUE TITLE
Links in rendered files point to localhost

### ISSUE THREAD

**Issue by Seanitzel** [chrisvfritz/prerender-spa-plugin#327]
Using the plugin for my vue project,
on building for production i get a link to the localhost server for some reason on every link in every rendered index.html file.

It looks like this:

```
<link rel="icon" href="http://localhost:8000/img/icons/android-chrome-512x512.png" sizes="512x512">
```

Im not sure if i'm doing something wrong or...

my configuration:

```
plugins: [
      new PrerenderSPAPlugin({
        staticDir: path.join(__rootDirname),
        routes:    prerenderedRoutesList
      })
    ]
```

Any ideas?

**Comment by JoshTheDerf** [comment]
@Seanitzel Looks like you've configured your webpack base path to be your server path. You'll need to correct your webpack config.
