### ISSUE TITLE
Any way to specify multiple html paths instead of routes?

### ISSUE THREAD

**Issue by japboy** [chrisvfritz/prerender-spa-plugin#33]
This plugin is supposed to be used for SPA, but is there any way to use this plugin for multiple pages which should be prerendered?

It would be great if I could do this below:

```
module.exports = {
  // ...
  plugins: [
    new PrerenderSpaPlugin(
      path.join(__dirname, '../dist'),
      // Specify static file path instead of routes
      [ '/index.asp', '/path/to/another.html', '/path/to/yet/another.php' ]
    )
  ]
}
```

How do you like this?

**Comment by chrisvfritz** [comment]
No, not as it is and I think it's beyond the scope of this plugin unfortunately. 😕 You wouldn't be able to capture these with just a static server.
