### ISSUE TITLE
Not Working With Laravel getting statusCode":404,"error":"Not Found"

### ISSUE THREAD

**Issue by shrenik9** [chrisvfritz/prerender-spa-plugin#34]
`<html><head></head><body><pre` style="word-wrap: break-word; white-space: pre-wrap;">{"statusCode":404,"error":"Not Found"}</pre></body></html>

**Comment by chrisvfritz** [comment]
Hmm, if it's a SPA (single-page application), then Laravel (the backend) should actually not be involved. It sounds like you're trying to use the plugin for a purpose it's not meant for.
