### ISSUE TITLE
Doesn't render content in index.html in Vue production mode, works in dev mode

### ISSUE THREAD

**Issue by Andras1000** [chrisvfritz/prerender-spa-plugin#340]
My Vue router is in `mode: 'history'`.

`vue.config.js`:
```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        data: '@import "@/scss/base.scss";',
      },
    },
  },
  configureWebpack: {
    plugins: [
      new PrerenderSPAPlugin({
        staticDir: path.join(__dirname, 'dist'),
        routes,
      }),
    ],
  },
};
```

Prerendering works correctly when I build with `vue-cli-service build --mode development`, but doesn't work correctly when building for production (`vue-cli-service build --mode production')`. The `index.html` for each route has a `<body>` that's practically empty:

`<body><div id="app"></div><script src="/js/chunk-vendors.334afee8.js"></script><script src="/js/app.578f5a48.js"></script></body>`

**Comment by alexsonnay** [comment]
How did you solve it ?!

**Comment by Andras1000** [comment]
Hi - have you tried debugging with `headless: false`?

**Comment by Andras1000** [comment]
> How did you solve it ?!

Hi - have you tried debugging with `headless: false`?
