### ISSUE TITLE
Is there a way to disable CORS policy in 3.x (Puppeteer) 

### ISSUE THREAD

**Issue by Andras1000** [chrisvfritz/prerender-spa-plugin#343]
I have built my app locally and the render was broken. 

After debugging with `headless: false` I found that this is because an API call `has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` This is because I am trying to access an external domain from `localhost`.

The following fix was suggested for 2.x (PhantomJS): https://github.com/chrisvfritz/prerender-spa-plugin/issues/86

Is there a similar way to pass options to `puppeteer` or what's the solution for such CORS issues?

**Comment by ubipo** [comment]
Put 
`args: [
    '--disable-web-security',
  ],`
in the Renderer options.

[https://stackoverflow.com/questions/52129649/puppeteer-cors-mistake/52131823](https://stackoverflow.com/questions/52129649/puppeteer-cors-mistake/52131823)

**Comment by atomheartother** [comment]
For people from the future who like me stumbled on this thread, read the full SO post, there are most flags needed nowadays:
`-disable-features=IsolateOrigins', ' --disable-site-isolation-trial`
