### ISSUE TITLE
Is it possible to use without being a SPA?

### ISSUE THREAD

**Issue by victorsilent** [chrisvfritz/prerender-spa-plugin#359]
Hello, I guess it could be a dumb question but I've try other solutions as prerender and nothing works for me. So here is my question:

I have a project running with laravel (laravel-mix) and vue 2 (without vue router)
the project is not an SPA, so we return a HTML page and inside this HTML page we have a vue global componente (our entire screen), now we have the same thing as a SPA in terms of files
app.js, manifest.js, vendors.js and a bunch of chunks of our components.
So my question is, there's some configuration that I can put on my webpack.config that will work for my case?

**Comment by TimWuyts** [comment]
I've the same question, since I'm using a SSG containing some Vue components. It would be nice to pre-render some of those component directly into the HTML generated by the SSG.

**Comment by JoshTheDerf** [comment]
In this case, you might be better off using [prerenderer](https://github.com/JoshTheDerf/prerenderer/) directly rather than using the webpack plugin. (Also sorry for the bump. :cry: )
