### ISSUE TITLE
Build with yarn failed

### ISSUE THREAD

**Issue by Ivan-Feofanov** [chrisvfritz/prerender-spa-plugin#36]
Please, update `phantomjs-prebuilt` dependency to 2.1.8 or higher

**Comment by chrisvfritz** [comment]
There was an outstanding bug on Windows in more recent versions of `phantomjs-prebuilt` that we avoided upgrading to work around. I'll try to do some testing soon to see if it's resolved now. 👍

**Comment by Philipp-M** [comment]
Is this issue resolved yet?

**Comment by marcoreni** [comment]
+1 on this issue. We're currently not able to `yarn install` on a Docker container based on `node:6`.

**Comment by drewlustro** [comment]
@chrisvfritz  Any remaining wariness to update `phantomjs-prebuilt`?

Said package update would also address #66. 

I imagine the best route would be for us to create an initial test suite for this module when considering `package.json` updates.

**Comment by drewlustro** [comment]
**Merged**.

Release coming soon after I get a chance to test everything. 🍻

**Comment by chrisvfritz** [comment]
Excellent. If anyone _really_ needs the old `phantomjs-prebuilt`, they can lock.
