### ISSUE TITLE
any solutions on dynmic content?

### ISSUE THREAD

**Issue by latel** [chrisvfritz/prerender-spa-plugin#365]
if the page content is saved from pupppter pre-rendered dom trees, what about some dynamic data that must be fetched from server, such as username, user avatar?

**Comment by Chenilove** [comment]
Again, there is no solution

**Comment by AnonymousArthur** [comment]
@Chenilove I like your avatar

**Comment by JoshTheDerf** [comment]
@latel Such data is expected to be fetched after the app renders. Placeholder data should be used while prerendering.
