### ISSUE TITLE
Prerender works on a random bases

### ISSUE THREAD

**Issue by arthabus** [chrisvfritz/prerender-spa-plugin#367]
Hi, I can't seem to prerender paths if publicPath is set to something other than "/"

Here is my vue.config.js that I can't make to work:

```
module.exports = {
        //the below publicPath and outputDir can't be changed
	publicPath:"/app",
	outputDir: path.resolve(__dirname, "./dist/app"),

	configureWebpack: {
		plugins: [
			new PrerenderSPAPlugin({
				staticDir: path.join(__dirname, 'dist'),
				outputDir: path.join(__dirname, 'dist/app'),
				indexPath: path.join(__dirname, 'dist', 'app/mytool.html'),
				routes: ['/tools/mytool'],
			})
		]
	}
}
```

It creates untouched `dist/app/tools/mytool/index.html` (literally just the same as the original `dist/app/mytool.html`)

Seems like I'm doing something wrong with paths - any input on how to make the plugin resolve the routes correctly with the custom publicPath and outputDir?

I'm on v3.4.0

**Comment by arthabus** [comment]
after trying to figure that out for two days already I can tell that it's working for me on a random basis - if I just run `npm run build` 10 times, it will produce prerendered html version 3 times on average and the other 7 times it's just a copy of the original html.

Seem like there is an async race condition somewhere - any ideas if this potentially can be caused by any parameters in my project's config?

**Comment by arthabus** [comment]
Figured that our. It was my main.js where I render the main application only after checking the login state which is asynchronous:

main.js:
```
let app
server.startListenForLoginStateChange(userProfile => {
	if(!app){
		app = new Vue({
			el: '#app',
			router,
			store,
			render: h => h(App)
		})
	}
})

```

I guess I'll need to figure out a way how to handle that better now.

**Comment by cnvoa** [comment]
Hi, I have also encountered this problem. It seems that it is a matter of order of execution. Do you have a solution? My Vue cli version is 4.5.8

**Comment by arthabus** [comment]
@cnvoa I've ended up creating the Vue instance synchronously and then setting up the login state inside the App.vue. It fixed the problem.

**Comment by cnvoa** [comment]
> @cnvoa我最终同步创建了Vue实例，然后在App.vue中设置了登录状态。它解决了问题。

Hi，我还找到另外一个解决办法，它看起来也不错
[#344](https://github.com/chrisvfritz/prerender-spa-plugin/issues/344)

**Comment by cnvoa** [comment]
> @cnvoa I've ended up creating the Vue instance synchronously and then setting up the login state inside the App.vue. It fixed the problem.

Hi, I also found another solution, it also looks good。
[#344 ](url)
