### ISSUE TITLE
TypeError: PrerenderSPAPlugin is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by Yodablues** [chrisvfritz/prerender-spa-plugin#369]
Brand new Vue project setup via the CLI running Vuetify. Have an existing project that is using this plugin with no issues, so not sure what the deal is.

Node:
![image](https://user-images.githubusercontent.com/2636870/75616366-ffae1780-5b1d-11ea-9948-8c8eec73c7ce.png)
![image](https://user-images.githubusercontent.com/2636870/75616368-050b6200-5b1e-11ea-9e66-5a9621bce79e.png)

![image](https://user-images.githubusercontent.com/2636870/75616266-fec8b600-5b1c-11ea-94f5-b377e45057d3.png)

package.json
![image](https://user-images.githubusercontent.com/2636870/75616354-ddb49500-5b1d-11ea-9f66-1965d89d7050.png)

**Comment by SreeChandan** [comment]
@Yodablues try removing '...' in front of 'new'

**Comment by Yodablues** [comment]
Yup, that was it. 🤦 Errant spread operator. Not sure where I got that from. My final config for anyone else who wants to know. Also had to nest the `plugins` array under `configureWebpack`:
```
const path = require('path');
const PrerenderSPAPlugin = require('prerender-spa-plugin');

module.exports = {
  transpileDependencies: [
    'vuetify',
  ],
  configureWebpack: {
    plugins: [
      new PrerenderSPAPlugin({
        // Required - The path to the webpack-outputted app to prerender.
        staticDir: path.join(__dirname, 'dist'),
        // Required - Routes to render.
        routes: [
          '/',
          '/about',
          '/resume',
        ],
      }),
    ],
  },
};
```
