### ISSUE TITLE
JS Bundle size not getting reduced 

### ISSUE THREAD

**Issue by gujral1997** [chrisvfritz/prerender-spa-plugin#377]
@chrisvfritz  @drewlustro  @JoshTheDerf 

I am able to pre-render the routes I want to and I am using code splitting in my project. But I haven't observed any reduction in the size of the js-chunk which are getting have pre-rendered. I have mentioned the configuration below. 

```
const PrerenderSPAPlugin = new _PrerenderSPAPlugin({
  staticDir: path.resolve(__dirname, '../', "dist"),
  minify: {
    collapseBooleanAttributes: true,
    collapseWhitespace: true,
    decodeEntities: true,
    keepClosingSlash: true,
    sortAttributes: true,
  },
  routes: ["/", "/add", "/edit"],
});
```

My doubt here is whether pre-rendering reduces the js bundle size of the targeted route or not?

Thanks in advance :-)

**Comment by ricky11** [comment]
did you find a solution to this?

**Comment by gujral1997** [comment]
What I think is it only decreases TTFB (Time to first byte) by rendering the HTML on build time. There is no effect on the JS bundle.

**Comment by JoshTheDerf** [comment]
This is accurate. :) 
Closing the issue.
