### ISSUE TITLE
Prerender dynamic pages on Nuxt

### ISSUE THREAD

**Issue by natashagp** [chrisvfritz/prerender-spa-plugin#380]
Hi, i'm trying to prerender dynamic pages in Nuxt, but the plugin doesn't work, it stops loading at 98% of building and nothing happens.
What I'm trying to do is prerender a post from i blog, which i get from an api. I need to prerender the page so the meta tags I defined on my created method are put on the page source code, to get a better SEO.
How can i fix this?

**Comment by alexsonnay** [comment]
If you want to generate pre-rendered files automatically, I think you have to use SSR and not Pre-rendering.

**Comment by natashagp** [comment]
Thank you for answering, I've changed my Nuxt to Universal mode, and I'm trying to make it work on production, but thanks for the help.
