### ISSUE TITLE
<v-img> are not pre-rendered

### ISSUE THREAD

**Issue by Kitcat711** [chrisvfritz/prerender-spa-plugin#385]
Hello,
Please have look to my gist:
https://gist.github.com/Kitcat711/1f65cc6ed59a227e675e7b5b5afcb05d

I want to use both the <v-img> tag and prerendering, every <v-img> keeps beeing lazy-loaded and I must use the normal <img> tag to get the result, but this solution is not ok for a lot of places in my pages, for instance, hier on "product.vue" line 10.

How can I force the plugin to prerender <v-img> ?

Thank you for your help, I have been struggling with that for days :(
Looking forward.
Kitcat

**Comment by paolog22** [comment]
try adding `eager` props as base on documentation of vuetify for ssr

**Comment by JoshTheDerf** [comment]
This seems like the expected behavior, but how long are you waiting for the images to be rendered before triggering the prerender event?

**Comment by Kitcat711** [comment]
It takes about 0,5 sec. The visual effect was really bad for the image just determines the frame of the paragraphs.
I replaced the <v-img>> by the standard html omg tag.

**Comment by JoshTheDerf** [comment]
Hmm. I don't think there's a way you're going to be able to force v-img to prerender, just by way of how it's designed. Sorry. :(

**Comment by witoldpilecki88** [comment]
Are there no workarounds?
