### ISSUE TITLE
vue router-view flash screen

### ISSUE THREAD

**Issue by zhouxianjun** [chrisvfritz/prerender-spa-plugin#394]
When there is a router-view in app.vue, the pre-rendered page will determine that the elements don't match with the vue.So the current element will be deleted and the element rebuilt.
![image](https://user-images.githubusercontent.com/5254523/87417277-7bf35400-c602-11ea-8462-9696d04c4ec7.png)

### app.vue
```vue
<template>
  <div id="app">
    <div id="nav">
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link>
    </div>
    <router-view/>
  </div>
</template>

<script>
  export default {
    name: 'app',
    components: {
    },
    mounted () {
      setTimeout(() => document.dispatchEvent(new Event('render-event')), 5000);
    },
    methods: {
    }
  }
</script>
```
### plugins
```js
config.plugins.push(new PrerenderSPAPlugin({
            // Required - The path to the webpack-outputted app to prerender.
            staticDir: path.join(__dirname, 'dist'),
            // Required - Routes to render.
            routes: ['/', '/about'],
            postProcess: (renderedRoute) => {
                renderedRoute.html = renderedRoute.html.replace('id="app"', 'id="app" data-server-rendered="true"');
                return renderedRoute;
            },
            minify: {
                minifyCSS: true,
                collapseWhitespace: true
            },
            renderer: new Renderer({
                headless: false,
                ignoreJSErrors: true,
                renderAfterDocumentEvent: 'render-event'
            })
        }));
```

**Comment by zhouxianjun** [comment]
I have solved the problem as mentioned. Well noted that when using the Vue-router's on Ready (we should be Initialize the route first before rendering), and can't using minify. As the minify will process the dom element, will be caused mismatch to element. For example : comment and so on . Above all , let the elements mounted by vue be consistent with the pre-rendered elements.

**Comment by dimavolo** [comment]
I have this same problem with Vue and @zhouxianjun's approach hasn't solved it for me.

It appears that when `router-view` is present in app.vue, the page renders perfectly well at first, then a second later it re-renders, causing a flash.

A side-effect for Vuetify users is that Vuetify's breakpoints get calculated for the first time upon this re-render, causing large layout shifts if you have columns that `v-if` depending on Vuetify breakpoints.

I have tried:

- Adding `data-server-rendered="true"` manually in index.html
- Automatically inserting `data-server-rendered="true"` during `postProcess`
- changing the mount point in index.html from #app to #vue-app (and correspondingly in main.js) in case there's id confusion

Are there any other suggestions for preventing the #app component from getting overwritten and flashing during page load?
