### ISSUE TITLE
How i can multithread prerender my app (Vue + i18n) with N routes and different inject langs ?

### ISSUE THREAD

**Issue by websharik** [chrisvfritz/prerender-spa-plugin#399]
Now my config is working but slowly, how can i make it faster ? Mb multithread ?

webpack:
```javascript
...['az', 'el', 'en', 'fr', 'it', 'kk', 'nl', 'pl', 'ro', 'ru', 'th', 'uk', 'uz'].map((lang) => {
	return new PrerenderSPAPlugin({
	//...
	inject: {
		isPrerenderer: true,
		config: {
			lang
		}
	},
	//...
	})
})
````

vuex:
```javascript
lang: window['__PRERENDER_INJECTED'].config.lang || localStorage.getItem('lang') || 'en'
```

**Comment by valentinoli** [comment]
Not sure you can process the plugins for each `lang` in parallel. Perhaps with some modifications you could achieve it with something like [parallel-webpack](https://github.com/trivago/parallel-webpack). I haven't used it myself so I don't know really...

But if you want higher concurrency for each plugin, you can adjust the `maxConcurrentRoutes` option (if you have it set to anything else than the default unlimited concurrency)

**Comment by valentinoli** [comment]
According to [webpack docs](https://webpack.js.org/guides/build-performance/#bootstrap) each additional plugin has a bootup time, thus you should minimize the number of plugins to optimize build time.
Question is, can you use a single plugin instead of one for each `lang`? It probably depends on your app's architecture, so I can't say. You could for example detect in the Vue component itself which lang is being processed if the lang is a param of the route URL, via `this.$route.params`.

**Comment by websharik** [comment]
I cant use `lang` as param of the route becouse `lang` is part of state [Vuex](https://vuex.vuejs.org). [Vuex state](https://vuex.vuejs.org#what-is-a-state-management-pattern) is single the source of truth that drives my app. `lang`s setter is inject. Single prerender-spa-plugin suport only one inject for all routes. Dynamic inject per route may be best possibility, but not supported.

Now [parallel-webpack](https://github.com/trivago/parallel-webpack) in better for speedup, but it is webpack per lang - i think its not best practic about optimize resources using.

**Comment by valentinoli** [comment]
Have you considered adding the lang as a query parameter, `lang=<lang>`? Then you can fetch the lang data from your store based on the query param.

**Comment by valentinoli** [comment]
```js
// vue.config.js

const langs = [...]
const routes = [...]
// Assuming every page is available in all languages
const routesPerLang = routes.flatMap(r => langs.map(l => `${r}?lang=${l}`))

const prerenderConfig = {
  staticDir: path.join(__dirname, 'dist'),
  routes: routesPerLang,
  postProcess(context) {
    // context.originalRoute includes the query parameter whereas context.route does not
    // Extract the lang parameter with RegEx
    const lang = /\?lang=(..)/.exec(context.originalRoute)[1]
    
    // Overwrite the output path to /dist/:lang/<route>/index.html
    // Assuming you want prerendered routes for each lang in separate folders
    context.outputPath = path.join(__dirname, 'dist', lang, context.route, 'index.html')
    
    return context
  },
  renderer: new Renderer({
    inject: {},
    renderAfterDocumentEvent: 'prerender-trigger'
  })
}

module.exports = {
  ...
  configureWebpack: {
    plugins: [
      new PrerenderSPAPlugin(prerenderConfig)
    ]
  } 
}
```

**Comment by valentinoli** [comment]
Hey, @websharik
I'm curious to know if this was any helpful for your scenario :)

**Comment by websharik** [comment]
Hey, @valentinoli
Not try that yet, but think its will working. Thanks for help :)

**Comment by valentinoli** [comment]
Great, hope it works
you're welcome :)
