### ISSUE TITLE
Dynamic routes

### ISSUE THREAD

**Issue by adalberth** [chrisvfritz/prerender-spa-plugin#4]
Is it possible to to have dynamic routes/links like:
`[
  '/',
  '/contact',
  '/exercises/:exercise'
],`

So that is prerenders all pages in under exercises?

**Comment by chrisvfritz** [comment]
It'd be impossible for the plugin to know which exercises actually exist, but you can accomplish this another way. Just connect to your database or read from the file system to compile a list of all the links to existing exercises.

**Comment by DrakeLeung** [comment]
Can I make a api request to get ids of exercises rather than database and file system =。=

**Comment by hurradieweltgehtunter** [comment]
Just came upon the same issue. I thought about to read a external file to insert in the list of routes to pre-render. But i don't know how.

> Just connect to your database or read from the file system to compile a list of all the links to existing exercises.

Could you be a little mire specific how to do this?

**Comment by readeujet** [comment]
@hurradieweltgehtunter [this answer](https://github.com/webpack/webpack/issues/2697) by @trusktr on Mar 23 guided me in the right direction here. I was able to grab my slugs of my blog posts and then prerender those rotues.

A word of caution though, when a new route is added (ie new blog post) this must be run again! If this is something you must do often it might be time to look into some SSR.

**Comment by adnanmuttaleb** [comment]
I am having the same issue, is there any reason dynamic route are not supported? I am using this plugin only for social crawler. 
I want to understand this: are the page listed in ` routes` are generated previous to the user request? or the js get executed upon user request? if the case is the latter one,  then why dynamic routes are not supported?
