### ISSUE TITLE
Is this repo still maintaind?

### ISSUE THREAD

**Issue by ricky11** [chrisvfritz/prerender-spa-plugin#403]
Hi , love this plugin but it doesn't seem to have been updated since 2018 (almost 2 years) and has outdated dependencies.

Is this a official plugin?

**Comment by JoshTheDerf** [comment]
I haven't had much use for it for several years. Occasionally remember to check on issues, but haven't really focused on it at all recently. Ran into an issue with jsdom last time I was working on it and haven't managed to resolve it yet. Hopefully soon. (TM)

**Comment by ricky11** [comment]
Hi, thanks much for your reply.

Im stuck because i need the flexibility of adding pre-rendering rather than server side rendering , as I only need to pre-render certain routes for open-graph meta tags  and search engines.  my team is unsure if we should use a unmaintained package..

any suggestions welcome.

Thanks
Rishi

**Comment by JoshTheDerf** [comment]
Understood. I'm not aware if there is a more up-to-date option available. Unfortunately I can make no guarantee as to maintenance of this package for the time being. :/
