### ISSUE TITLE
Usage with Vue 2.x

### ISSUE THREAD

**Issue by toverux** [chrisvfritz/prerender-spa-plugin#41]
In the README.md, you state:

> Vue 2.x: Make sure the root component has the same id as the element it's replacing

I'm not really sure to understand what that means (I'm also a Vue beginner). In fact, preprendering works, but then, if the client has JavaScript enabled, the Vue application does not take control of the DOM (no errors, just the frozen page).

Unfortunately, https://github.com/chrisvfritz/prerender-spa-plugin-vue-demo is for Vue 1.x.

My application bootstrap looks like this (relevant parts only):

```html
<body>
    <div id="vue-app"></div>
</body>
```

```ts
const Layout = require('./ui/layout/layout.vue');

const root = new Vue({
    render: h => h(Layout)
});

document.addEventListener('DOMContentLoaded', () => root.$mount('#vue-app'));
```

I know it's not correct here, but I've tried various little variations without success.

Anyway, thanks for your work, prerendering is awesome, especially when it's so simple to add!

**Comment by Lucassifoni** [comment]
Hey,
I think it's just a matter of ensuring that your layout.vue template has the same ID as the prerendered component.

index.html
```html
<body>
    <div id="vue-app"></div>
</body>
```

layout.vue
```html
<template>
    <div id="vue-app" class="Layout">
        <!-- your own magic there -->
    </div>
</template>
```

Maybe I misunderstood your question, but it works when doing things that way for me, with vue 2.x.

**Comment by toverux** [comment]
Of course... that totally makes sense now. That works. Thanks a lot @Lucassifoni.
