### ISSUE TITLE
Scoped style holds up build time...

### ISSUE THREAD

**Issue by weilbaecher** [chrisvfritz/prerender-spa-plugin#44]
It took me a little while to figure out why my build would hold up for over 30 minutes (I never got it to finish). I had <style scoped> in one of my components. I removed scoped and the build worked like before. Can you give me any insight into what was the nature of this hold up?

**Comment by drewlustro** [comment]
Scoped styles should not significantly affect the build time of your app. Could you please provide more information about your configuration and code?

**Comment by drewlustro** [comment]
Closed due to lack of activity.

`cc:` @weilbaecher
