### ISSUE TITLE
Is there any way that we can prerender selected components ?

### ISSUE THREAD

**Issue by sagar12861** [chrisvfritz/prerender-spa-plugin#47]
I'm working with react. I want to prerender only the app shell and some other components. Is there any way I can do that with his plugin ?

**Comment by jnrdt** [comment]
Hi,

Try throwing an event when your app shell is rendered like so : 
```
document.dispatchEvent(new Event('app-shell-rendered'))
```
And put this option is the plugin like it's described in the README : 
```
captureAfterDocumentEvent: 'app-shell-rendered'
```
This should stop the prerendering as you expect.

Hope it will help

**Comment by sagar12861** [comment]
Hi @jnrdt Thank you for answering
What if selected components are placed random positions on the page ?
If the rendering taking place with async functions before throwing the event the unwanted components ( contains frequently updating data or user data ) will be rendered.

**Comment by jnrdt** [comment]
Hi

Only one of the random positions will be prerendered. But that can be better than no prerender at all.

If some children components can be rendered before the app shell, you simply do not have any time when the picture would be statisfying :
- too early : the app shell will not show up
- too late : the app shell will be there but some unwanted components to

I'm afraid you will have to adapt your code. That can be good anyway to have your app loading in a chronology you get your hands on.
