### ISSUE TITLE
I met a question about 'Bad argument'

### ISSUE THREAD

**Issue by leenty** [chrisvfritz/prerender-spa-plugin#50]
![image](https://cloud.githubusercontent.com/assets/13213680/24139620/be6f8b66-0e57-11e7-9e53-02b2bf20cf4f.png)
Hi!
I met a question about 'Bad argument'，and I can't solve
I used the [solution to this problem](https://github.com/chrisvfritz/prerender-spa-plugin/issues/8#issuecomment-255011088)
But the problem seems to be more than that
The mistake is still there
I hope I can get your help

macOS 10.12.3 (16D32)
node -v  v7.7.3
npm -v 4.1.2
phantomjs-prebuilt@2.1.14
prerender-spa-plugin@2.0.1

**Comment by jnrdt** [comment]
Hi,

It definitly seems to be a problem with the installation of PhantomJS. Try this : http://stackoverflow.com/questions/34293504/phantomjs-not-working-anymore-installed-through-npm

**Comment by leenty** [comment]
I temporarily installed a low version to solve this problem
And thanks for your help! 👌
