### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by zombor** [chrisvfritz/prerender-spa-plugin#51]
Getting this error when trying to build my app. Not exactly sure how I can start to debug this, the app works well in a browser and I've tried "turning off" various third party dependencies like Intercom and Raven but to no avail. Is there a way to get a stacktrace to figure out what's causing the problem?

```
⠋ building for production...(node:25840) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
⠇ building for production...
Starting to optimize CSS...
Processing static/css/app.ea844220eb9d3e1f2353b0414c749fa0.css...
Processed static/css/app.ea844220eb9d3e1f2353b0414c749fa0.css, before: 163707, after: 163347, ratio: 99.78%
⠙ building for production...
/home/jbush/code/card-rocket-web/node_modules/prerender-spa-plugin/lib/compile-to-html.js:80
                    if (error) throw stdout
                               ^
WARNING: JavaScript error while prerendering: /modern-masters-2017-box-promotion
TypeError: undefined is not an object (evaluating 'e[n].call')

  phantomjs://code/phantom-page-render.js:26 in onError
```

**Comment by jnrdt** [comment]
Hi,

It's probably do to some javascript limitations of PhantomJS used by the plugin. You may try to inject polyfills in your document in order to avoir errors.

See https://github.com/chrisvfritz/prerender-spa-plugin/issues/49 for more detail.

**Comment by zombor** [comment]
Yeah, I tried adding the core-js polyfill in my `<head>`, but I ge the same error. I guess I have the same problem as https://github.com/chrisvfritz/prerender-spa-plugin/issues/49#issuecomment-287966261.

**Comment by zombor** [comment]
In my case, this was from using `vue-octicons` and not doing the proper setup in webpack2. This helped me out: https://github.com/Justineo/vue-octicon/issues/2
