### ISSUE TITLE
WARNING: JavaScript error while prerendering: TypeError: null is not an object (evaluating 't.addEventListener') phantomjs://code/phantom-page-render.js:26

### ISSUE THREAD

**Issue by nolaandy** [chrisvfritz/prerender-spa-plugin#52]
This is happening when I add the javascript needed to Ajax submit a form. Below is my ContactForm component code that I am calling in my Contact Page Component.

If I remove the javascript at the top (before export default) the website will build. If I keep the code, I get a silent fail build loop. This has happened in my other page components where I want to add javascript just to one page. Am I doing something wrong? The form works properly on dev server and submits via ajax, I just can't build the site...

This is the error I get in terminal:

`- building for production...
C:\Users\orion\Desktop\blog.tatthien.com\blog.tatthien.com\node_modules\prerender-spa-plugin\lib\compile-to-html.js:80
                    if (error) throw stdout
                               ^
WARNING: JavaScript error while prerendering: /resume
TypeError: null is not an object (evaluating 't.addEventListener')`

I don't even have a t.addEventlister. The code is probably document.addEventListener('DOMContentLoaded', loaded, false)

ContactForm.Vue
`function validEmail (email) { // see:
`  var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i
`  return re.test(email)
`}
`// get all data in form and return object
`function getFormData () {
`  var elements = document.getElementById('gform').elements // all form elements
`  var fields = Object.keys(elements).map(function (k) {
`    if (elements[k].name !== undefined) {
`      return elements[k].name
`    // special case for Edge's html collection
`    } else if (elements[k].length > 0) {
`      return elements[k].item(0).name
`    }
`  }).filter(function (item, pos, self) {
`    return self.indexOf(item) === pos && item
`  })
`  var data = {}
`  fields.forEach(function (k) {
`    data[k] = elements[k].value
`    if (elements[k].type === 'checkbox') {
`      data[k] = elements[k].checked
`    // special case for Edge's html collection
`    } else if (elements[k].length) {
`      for (var i = 0; i < elements[k].length; i++) {
`        if (elements[k].item(i).checked) {
`          data[k] = elements[k].item(i).value
`        }
`      }
`    }
`  })
`  console.log(data)
`  return data
`}
`function handleFormSubmit (event) {  // handles form submit withtout any jquery
`  event.preventDefault()           // we are submitting via xhr below
`  var data = getFormData()         // get the values submitted in the form
`  if (!validEmail(data.email)) {   // if email is not valid show error
`    document.getElementById('email-invalid').style.display = 'block'
`    return false
`  } else {
`    var url = event.target.action
`    /* eslint-disable no-undef */
`    var xhr = new XMLHttpRequest()
`    /* eslint-enable no-undef */
`    xhr.open('POST', url)
`    // xhr.withCredentials = true;
`    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded')
`    xhr.onreadystatechange = function () {
`      console.log(xhr.status, xhr.statusText)
`      console.log(xhr.responseText)
`      document.getElementById('gform').style.display = 'none' // hide form
`      document.getElementById('thankyou_message').style.display = 'block'
`      return
`    }
`    // url encode form data for sending as post data
`    var encoded = Object.keys(data).map(function (k) {
`      return encodeURIComponent(k) + '=' + encodeURIComponent(data[k])
`    }).join('&')
`    xhr.send(encoded)
`  }
`}
`function loaded () {
`  console.log('contact form submission handler loaded successfully')
`  // bind to the submit event of our form
`  var form = document.getElementById('gform')
`  form.addEventListener('submit', handleFormSubmit, false)
`}
`document.addEventListener('DOMContentLoaded', loaded, false)
`export default {

`}

**Comment by drewlustro** [comment]
Please provide a better issue report with your `webpack.config.js`, `index.html`, and primary webpack entry `.js` file.

As it stands, I have no idea where `t.addEventListener` could be coming from, but if I had to guess, it is more than likely some 3rd party JS you included via `<script src="..."></script>`.

**I would love to help you, but cannot make sense of your issue report without more information.**
