### ISSUE TITLE
Limit PhantomJS workers?

### ISSUE THREAD

**Issue by spAnser** [chrisvfritz/prerender-spa-plugin#53]
My VueJS app has a good number of routes, 143 currently, I am trying to prerender but this is overloading my system.

http://puu.sh/uXwnd/f4eb99e29d.png

Am I missing the option that renders 1 pages at a  time?

If I render about 5 pages it runs into no issues and completes really fast it is only when I attempt to render all of my pages that it starts spawning PhantomJS over and over and then each on hangs and never completes.

**Comment by jnrdt** [comment]
Hi,

As mentionned in the docs, you may be looking at Server Side Rendering. 

That sayed, it sounds to me like a good idea anyway. A pull request is pending about this that will allow you to mention the number of workers you want. We'll tell you if it's adopted and when it will be available.

**Comment by spAnser** [comment]
I've considered SSR but it is rather slow. However I've only tested that locally.

I was however able to convert the Promises to be act as a waterfall but that only limits it to 1 at a time and can also take quite a while to fully render everything.

Thanks for the PR though.

**Comment by drewlustro** [comment]
Taking a look in @jnrdt's PR!

**Comment by wxsms** [comment]
Hi there.

Any progress or plans on this one? I got the same issue, while rendering 100+ routes lot's of pages got no response for a very long time...

**Comment by wxsms** [comment]
I got a temporary solution by chunking your plugins into webpack:

```javascript
// Generate url list for pre-render
exports.generateRenderPlugins = () => {
  let paths = [] // the routes
  let chunks = _.chunk(paths, 10) // using lodash.chunk
  let plugins = []
  let distPath = path.join(__dirname, '../dist')
  let progress = 0
  chunks.forEach(chunk => {
    plugins.push(new PrerenderSpaPlugin(distPath, chunk, {
        postProcessHtml (context) {
          // need to log something after each route finish
          // or CI will fail if no log for 10 mins
          console.log(`[PRE-RENDER] (${++progress} / ${paths.length}) ${context.route}`)
          return context.html
        }
      }
    ))
  })
  return plugins
}
```

**Comment by Tribex** [comment]
For anyone else coming here, [v3](https://github.com/chrisvfritz/prerender-spa-plugin/tree/v3#prerendererrenderer-puppeteer-options) now supports this with the `maxConcurrentRoutes` option.
