### ISSUE TITLE
Getting statusCode":404,"error":"Not Found" on each static views.

### ISSUE THREAD

**Issue by francoislevesque** [chrisvfritz/prerender-spa-plugin#6]
Trying to use prerender-spa-plugin, but getting this on all generated views:

`<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"statusCode":404,"error":"Not Found"}</pre></body></html>`

I use vue 2.x and vue-router 2.x.
Here's my config:

```
plugins: [
	new PrerenderSpaPlugin(
		path.join(__dirname, '/static'),
		[ '/fr/', '/en/', '/fr/contact/', '/en/contact/', '/test' ]
	)
]
```

Here's my root Vue instance:

```
new Vue({
	el: '#app',
	router,
	store,
	render: h => h(App)
})
```

App.vue:

```
<template>
	<div id="app">
		<!-- Route Outlet -->
		<router-view></router-view>
	</div>
</template>

<script>
export default {
	
}
</script>
```

What would be a possible solution to this issue?

**Comment by chrisvfritz** [comment]
It's definitely confirmed working with Vue 2 and Vue Router 2. The most likely cause is that you're providing the wrong directory. If you generated this project with `vuejs-templates/webpack`, then the correct path would be:

``` js
path.join(__dirname, '../dist')
```

**Comment by francoislevesque** [comment]
I'm using the webpack-simple template. I changed the path to `./dist` and I still get the same error.

**Comment by chrisvfritz** [comment]
The correct path is then just `__dirname`. 😃  It's wherever the prod `index.html` is. In that template, the same `index.html` is used for both dev and prod and its in the root - same folders as the Webpack config.

**Comment by francoislevesque** [comment]
Oh! This is perfect! Thanks for the clarification! 😄

**Comment by iMomen** [comment]
I still have some confusion about this
this is my config in webpack.prod.conf

`new PrerenderSpaPlugin(
      // Path to compiled app
      path.join(__dirname, '../dist'),
      // List of endpoints you wish to prerender
      [ '/', '/privacy','/contact']
    )`

But the rendered files are still empty :(
any hint?
