### ISSUE TITLE
am I doing something wrong ? can't make this one work.

### ISSUE THREAD

**Issue by lili21** [chrisvfritz/prerender-spa-plugin#60]
[example](https://github.com/lili21/prerender-vue-demo)

create the project by [vue-cli](https://github.com/vuejs/vue-cli), 

the build result is not `prerendered` .

**Comment by lili21** [comment]
look like this one only work for html5 history mode . right ?

**Comment by jnrdt** [comment]
Hi,

Yeah, a hash cannot correspond to a physical route. All that you can prerender is the base route.

Example, for :

- `/#home`
- `/#contact`

The only path sent to the server via http header is `/` so the only route that can be prerendered is `/`.

**Comment by lili21** [comment]
@jnrdt Thanks, that make more sense now.
