### ISSUE TITLE
inline background-image URL is messed up by phantomJS in the index.html

### ISSUE THREAD

**Issue by PierreCavalet** [chrisvfritz/prerender-spa-plugin#61]
Hi,

For some reasons **I need to inline** a background-image css property and I'm giving it a URL, for example:

```html
<div style="background-image: url('/static/some-image.jpg'); width: 300px; height: 200px;"></div>
```
The problem is that phantomJS replaces my URL by: 
```html
<div data-v-b31ef546="" style="background-image: url(http://localhost:8000/static/some-image.jpg); width: 300px; height: 200px;"></div>
```

Because it's running on localhost:8000 but obviously it doesn't work when I'm serving the static file in a web server. Any better workaround than using a regexp to replace it in `postProcessHtml` ?

Thanks

**Comment by vasiliysmirnov** [comment]
Hey, @PierreCavalet, have the same issue, did you solve the problem?

**Comment by PierreCavalet** [comment]
Hey @vasiliysmirnov, sadly I did not. I worked that around and I now don't have inlined background-image anymore. 

This problem is weird because PhantomJS was not designed to prerender SPA at the first place so it is not technically a PhantomJS problem, but is not a prerender-spa-plugin problem either because the URL prefix is placed by PhantomJS. If you find a more elegant way to remove it than `postProcessHtml`, please let me know.

**Comment by drewlustro** [comment]
This plugin takes the html that comes straight out of PhantomJS. We have no control over what PhantomJS outputs.

### Solution

Use **prerender-spa-plugin**'s `postProcessHtml` option to transform what you need.

In your `webpack.config.js`:

```js
var Path = require('path')
var CopyWebpackPlugin = require('copy-webpack-plugin')
var PrerenderSpaPlugin = require('prerender-spa-plugin')

module.exports = {
  entry: [ './src/main.js' ],
  output: {
    path: './dist',
    filename: '[name].js'
  },
  plugins: [
    new CopyWebpackPlugin([{
      from: 'src/static',
      to: '.'
    }]),
    new PrerenderSpaPlugin(
      Path.join(__dirname, 'dist'),
      [ '/' ],
      {
        postProcessHtml: function (context) {
          return context.html.replace(
            /http:\/\/localhost:8080/gi, ''
          )
        }
      }
    )
  ]
}

```
