### ISSUE TITLE
Can not get actual content prerendered, only what's initially in index.html

### ISSUE THREAD

**Issue by kushagharahi** [chrisvfritz/prerender-spa-plugin#62]
Project: https://github.com/kushagharahi/kushagharahi.github.io I am using vuejs2.0

I can not get the actual content of the page prerendered. All I get outputted is the original index.html w/o rendered content.

I've been scratching my head at what is wrong.

My entry point is `./src/scripts/main.js`

You can see the issue in the `./dist` folder. Every path's index.html is identical to `./dist/index.html`. IE: `./dist/index.html` is the same as `./dist/contact/index.html` which is equivalent of `./src/static/index.html` (the original file).

**Comment by esalter-va** [comment]
I'm having the exact same issue.  [Here's a Gist containing my `webpack.conf.js`, `index.html`, and `main.js`](https://gist.github.com/esalter-va/2f5b933078f65a8e93df8a69e2119b56).  When I build, `dist/index.html` has the exact same content as the original `index.html`, except the JS bundles are injected into `<head>`.  I generated my app from the Vue CLI webpack template.

I am completely out of ideas, so any help I can get is greatly appreciated!

**Comment by csvwolf** [comment]
The same problem!

**Comment by esalter-va** [comment]
@csvwolf @kushagharahi I ended up writing my own webpack plugin that uses Nightmare.js to render the pages.  It's pretty basic, but it might be worth a shot: https://github.com/esalter-va/webpack-static-site-generator

**Comment by shuiRong** [comment]
same problem +1

**Comment by danielmrsantos** [comment]
the same problem!

**Comment by wbgneto** [comment]
Same problem :(

**Comment by devmarcelosantos** [comment]
Same problem!!

**Comment by kushagharahi** [comment]
It seems like this comment may explain our problems: https://github.com/chrisvfritz/prerender-spa-plugin/issues/72#issuecomment-307659670

Is there any workaround for this issue?

**Comment by jnrdt** [comment]
Hi, I don't think this is the same case. People here seem to have fully static SPAs. This is more like a version incompatibility between used components though I've not been able to repeat it. The best way for me to understand would be to share the exact repo that's not working and specify the environment.

**Comment by kushagharahi** [comment]
You're right @jnrdt I was tired last night and misunderstood. I deleted my comment. I apologize.

**Comment by drewlustro** [comment]
@kushagharahi - I downloaded your code repository and there is a key problem with it. PhantomJS hits an exception because you forgot to transpile your `.js` files into ES6.

Please add the following to `webpack.config.js`:

```js
// ....

module: {
  rules: [
    // ... other rules
    {
      test: /\.js$/,
      loader: 'babel-loader',
      include: [
        path.join(__dirname, 'src')
      ],
      exclude: path.join(__dirname, 'node_modules')
    },
    // .. the rest of your rules
  ]
},

// ....
// rest of webpack config
// ...
```

I have made this change and your site prerenders without issue.

**Comment by kushagharahi** [comment]
@drewlustro YOU ARE BEAUTIFUL AND AMAZING. Thank you for the help. This can be closed.

**Comment by drewlustro** [comment]
Bahahaha. No worries my friend.

**Comment by lokkomokko** [comment]
@esalter-va big big thanks

**Comment by vesper8** [comment]
same problem... =/

**Comment by dhruvbhatia7** [comment]
same problem
