### ISSUE TITLE
question regarding prerender vs ssr

### ISSUE THREAD

**Issue by besnikh** [chrisvfritz/prerender-spa-plugin#64]
Hi, 
I am building an app using Vue & Vuex, and at this time I have to think about SEO but I am not sure which should I use between Prerender vs SSR and I am hoping someone can clarify this for me. 

So let's say my app is an e-commerce app, and my routes are would be: 
routes =  "/", "products", "products/this-product", "company/this-company"

Now, I understand that I can pre-render products route, but what when the products route is dynamic, where new products will be added on daily basis, and each product on products page will have it's own "products/this-product-2" route 

Is this a case for prerender or I need to use SSR ? 

PS.
I really don't care so much about SEO, for me it would be enough just to be able to pass some metatags so each product can be fetched from Facebook, and maybe add some canonical url for each product to the AMP page or something like that.. 

Looking forward to receive from someone,
Cheers

**Comment by chrisvfritz** [comment]
We address this [in the README](https://github.com/chrisvfritz/prerender-spa-plugin#prerendering-vs-server-side-rendering-ssr). Does that answer your question?

**Comment by besnikh** [comment]
@chrisvfritz I guess not for this particular question I have, and because before I never did something like this I am asking the question for someone to put me on the right direction. 

For example, how could I trigger a re-render if a /this-product-id changes it's title, do I need to build the whole webapp or can I somehow re-render just that page ?

**Comment by chrisvfritz** [comment]
A service like Prerender.io, Netlify's prerendering solution, or just using SSR would be better suited for that kind of problem.
