### ISSUE TITLE
Any way not to have minified .html files from build?

### ISSUE THREAD

**Issue by p3lican** [chrisvfritz/prerender-spa-plugin#65]
I need to add tracking codes to certain pages and potentially have someone else change them without rebuilding the site.
I assume they can just add these scripts to the bottom of the prerendered pages. (If there is a better way please let me know)

To make that easier for them and myself, is there anyway to have the prerender html not come out minified?

**Comment by drewlustro** [comment]
This plugin takes the html that comes straight out of PhantomJS. We have no control over what PhantomJS outputs and there is no option to pretty print html.

### Solution

I found that you can use [pretty](https://github.com/jonschlinkert/pretty) quite easily with **prerender-spa-plugin**'s `postProcessHtml` option to make the prerendered HTML prettier (more readable).

First run:

```bash
npm install prettier --save-dev
```

In your `webpack.config.js`:

```js
var Path = require('path')
var CopyWebpackPlugin = require('copy-webpack-plugin')
var PrerenderSpaPlugin = require('prerender-spa-plugin')
var pretty = require('pretty')

module.exports = {
  entry: [ './src/main.js' ],
  output: {
    path: './dist',
    filename: '[name].js'
  },
  plugins: [
    new CopyWebpackPlugin([{
      from: 'src/static',
      to: '.'
    }]),
    new PrerenderSpaPlugin(
      Path.join(__dirname, 'dist'),
      [ '/' ],
      {
        postProcessHtml: function (context) {
          return pretty(context.html)
        }
      }
    )
  ]
}

```
