### ISSUE TITLE
Update phantom-js prebuilt in package.json?

### ISSUE THREAD

**Issue by cschweda** [chrisvfritz/prerender-spa-plugin#66]
Is it possible to update to the latest version of phantomjs-prebuilt?

I'm getting 'undefined' errors when my site is prerendered with the packaged version of phantom-prebuilt -- but if I update the package.json and ```npm i``` in the module (to phantomjs-prebuilt 2.1.14) -- those errors disappear.

What's the best way to do this?

**Comment by drewlustro** [comment]
**Merged**.

Release coming soon after I get a chance to test everything. 🍻
