### ISSUE TITLE
Broken transitions

### ISSUE THREAD

**Issue by desirelabs** [chrisvfritz/prerender-spa-plugin#69]
Hi there, it seems like prerender spa plugin is breaking lot of stuff in my vuejs app. For instance, I applied transitions between routes. This doesn't fire anymore. Other things like dynamic elements (eg modal) used from semantic ui, are broken.
How to make this work the right way ?
Thanks

**Comment by samburgers** [comment]
I had a similar issue with a Vue app, solved it by implementing this caveat from the docs:

```
Vue 2.x: Make sure the root component has the same id as the element it's replacing
```

**Comment by desirelabs** [comment]
Not sure what it means, I changed this in main.js : 
```
const app = new Vue({
  router,
  render: h => h(require('./App'))
})

document.addEventListener('DOMContentLoaded', function () {
  app.$mount('#app')
})
```
and, the id of the root component is `#app`

**Comment by samburgers** [comment]
Sorry, not sure then! Do you have any console errors on load? Here is my basic setup if thats any help...

`main.js`

```
import 'es6-promise/auto'

import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'

Vue.config.productionTip = false

/* eslint-disable no-new */

new Vue({
  el: '#app',
  router,
  store,
  template: '<App/>',
  components: { App }
})
```

`App.vue`

```
<template>
    <div id="app">
        <transition name="fade">
            <router-view></router-view>
        </transition>
    </div>
</template>

<script>
  export default {
    name: 'app'
  }
</script>
```

**Comment by desirelabs** [comment]
I actually have a js error concerning google recaptcha. Can this break the application ? I don't know.
btw, you put the id app inside the template : don't you already have one right inside body tags ?

**Comment by drewlustro** [comment]
Your code has an _uncaught exception_ due to using Google ReCaptcha API noted in #70. Please address this and create a new issue if you are certain that **prerender-spa-plugin** is the source of broken transitions.
