### ISSUE TITLE
Generate XML Sitemap?

### ISSUE THREAD

**Issue by samburgers** [chrisvfritz/prerender-spa-plugin#71]
Just wondering if generating an XML sitemap is within the scope of this awesome project?

**Comment by chrisvfritz** [comment]
Thanks for the suggestion! As far as I know, the purpose of a sitemap would be to help users and search bots navigate the site. So to ask the larger question, have you noticed areas where the site is difficult to navigate or that it doesn't show up well in search engines?

**Comment by samburgers** [comment]
Still just scoping a client project at the moment, and I know that various SEO concerns will need to be covered off. To build it with Vue + Prerendering is perfect for so many reasons, and an xml sitemap would just tick certain boxes, so to speak. Cheers!

**Comment by drewlustro** [comment]
This is cool but also a bit specific for the intended scope of this plugin. We'll consider it for a release in the future. In the mean time, if you'd like to create a PR to show us what you mean, by all means 👍
