### ISSUE TITLE
Generated files don't get the right content

### ISSUE THREAD

**Issue by nicolas-t** [chrisvfritz/prerender-spa-plugin#72]
Hello !

I use Vue2 with Laravel.
With Laravel, accessible pages are found in the folder `/public`.

When building, the plugin generates a file here : `/public/about/index.html`

If I navigate, to the desired url (_website.com/about_) it displays:  
```json
{"statusCode":404,"error":"Not Found"}
```
After verifing, that's the content of the generated file (`/public/about/index.html`)

------

I use the plugin like this :  
```javascript
new PrerenderSpaPlugin(
  path.join(__dirname, '../public'),
  [ '/about' ]
)
```

I read that the 404 errors were related to `path.join(__dirname, '../public')`.  
But this one seems correct since it creates a file at the right place. 

What am I doing wrong ? 

Thanks :zap:

**Comment by nicolas-t** [comment]
Digged in the code.

It's not working because here : 
https://github.com/chrisvfritz/prerender-spa-plugin/blob/master/lib/compile-to-html.js#L32L34

You assume I have an index.html containing my app. 
But as I use laravel I don't have this file, in fact, I have a blade (laravel templating language) in an other folder that get rendered when requesting my website.

Do you have any idea of workaround ? 
Use an url instead of a file path in the lines mentioned above ?

Thanks

**Comment by jnrdt** [comment]
Hi, basically this plugin is made to prerender SPA applications eg fully static files. More than a limitation, it seems yo have no interest in your case because this plugin aims at serving a static file behind an html5 route when in your case you already have a server side page being served. If I understand well, you will have nowhere to put the static prerendred file even if you get it.

**Comment by nicolas-t** [comment]
Hi :) 

I'm using it in a single page application, the only thing is that my _"index.html"_ is first rendered by laravel (in order to pass some envrionment variables).
It looks like this :  
```blade
<!DOCTYPE html>
<html>
    <head>
        <title>website</title>
        @if (view()->exists('build/tags/css-tag'))
            @include('build/tags/css-tag')
        @endif
    </head>
    <body>
        <script>
            window.foo = '{{ env("foo") }}'
        </script>

        <div id="root"></div>

        @if (view()->exists('build/tags/javascript-tag'))
            @include('build/tags/javascript-tag')
        @else
            <script type="text/javascript" src="/bundle.js"></script>
        @endif

    </body>
</html>
```

Once this template is loaded by the user, Vue does it job, in `#root`, like any SPA.

**Comment by jnrdt** [comment]
Well it will not work for the reason I mentionned, but that's not a lost case! You have to free your front-end from back-end technologies. Inject what you need at compile time or get the needed informations from an api at runtime. The only good reason to use back-end with front-end is server side rendering... but here we can consider it's a poor one.

**Comment by nicolas-t** [comment]
As you suggested I separated my backend code from my front-end code.  
  
Maybe in my case I could also have changed  (haven't tried)
```javascript
Server.route({
  method: 'GET',
  path: route,
  handler: function (request, reply) {
    reply.file(
      Path.join(staticDir, 'index.html')
    )
  }
})
```
to
```javascript
Server.route({
  method: 'GET',
  path: route,
  handler: function (request, reply) {
    reply.redirect('/') // or, 'http://localhost'
  }
})
```
For those interested I used https://github.com/mrsteele/dotenv-webpack to load my env variables. 

Anyway, I met another problem:  
 - if, for some reasons you use webpack's `config.output.publicPath` with an url ([my reason](https://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts))   
you should change it to `config.output.publicPath = '/'` to make the prerendering work.

but I go it to work !

**Comment by nicolas-t** [comment]
Oh, and also with vuex, I needed to load `import 'es6-promise/auto'` for phantomJs to work.

**Comment by jnrdt** [comment]
Hi,
great!

About the es6-promise, a [PR](https://github.com/chrisvfritz/prerender-spa-plugin/pull/54) is pending fixing the issue.
