### ISSUE TITLE
Does prerender-spa-plugin has a dependency on vue-router? 

### ISSUE THREAD

**Issue by ytbryan** [chrisvfritz/prerender-spa-plugin#74]
This is more like a question than issue. 

I am trying to explore `prerender-spa-plugin`  on a rails project via Rails' default router and webpacker. 

Does `prerender-spa-plugin` has a dependency on vue-router? Or a dependency on `.vue` component?

**Comment by jnrdt** [comment]
Hi,

I'm not a Rail developer, but it sounds like you talk about server side router, right?

If so, it's absolutely incompatible (see discussion [here](https://github.com/chrisvfritz/prerender-spa-plugin/issues/72)).

However, if it's a full static application, you can in theory use it with any front-end framework. No dependency on vue-router, it basically take an html picture of your page and serves it before the framework actually loads.

**Comment by ytbryan** [comment]
I see. Thanks for the quick answer!
