### ISSUE TITLE
Can't load resources from hidden directory

### ISSUE THREAD

**Issue by blackgearit** [chrisvfritz/prerender-spa-plugin#76]
In my project I serve resources from a hidden path ('/.resources/..etc..'). The problem is that your plugin compiles the index.html file as it was compiled by webpack, without Vue content. I've found that the prerender script cannot execute document's javascripts, so looking to Hapi server docs, i've found the 'showHidden' option. With this option in the compile-to-html.js file, I was able to render the html page entirely.
I've created a pull request here
https://github.com/chrisvfritz/prerender-spa-plugin/pull/75

**Comment by drewlustro** [comment]
Merged.
