### ISSUE TITLE
Refresh site goes to prerendered directories

### ISSUE THREAD

**Issue by simboonlong** [chrisvfritz/prerender-spa-plugin#77]
Not sure if I am doing it right.

I've set up a test site using vue-webpack-boilerplate with vue-router. I've managed to prerender the pages and the dist directories look as follows:

about/
&nbsp;&nbsp;index.html
contact/
&nbsp;&nbsp;index.html
index.html
&nbsp;&nbsp;static/
&nbsp;&nbsp;&nbsp;&nbsp;css/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app.[rev].css
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app.[rev].map
&nbsp;&nbsp;&nbsp;&nbsp;js/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app.[rev].js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app.[rev].map
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vendor.[rev].js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vendor.[rev].map
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;manifest.[rev].js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;manifest.[rev].map
work/
&nbsp;&nbsp;projectone/
&nbsp;&nbsp;&nbsp;&nbsp;index.html
&nbsp;&nbsp;projecttwo/
&nbsp;&nbsp;&nbsp;&nbsp;index.html
&nbsp;&nbsp;projectthree/
&nbsp;&nbsp;&nbsp;&nbsp;index.html

With javascript disabled, I was able to navigate the site normally, thanks to the prerendered static folders and index.htmls.

However with js enabled, the site app did not work as expected when I force refresh while in work detail pages (projectone, projecttwo etc). I believe that the site was accessing the prerendered folders directly, instead of adhering to its app vue routing logic, since the work folders now exist on the server.

I've follow the htaccess rules at https://router.vuejs.org/en/essentials/history-mode.html to no avail.  I'm not very familiar with writing htaccess rules and is a little lost on how to make vue router with prerendering work.

Any help is greatly appreciated.

**Comment by simboonlong** [comment]
Realized it's my own mistake in the app logic. While in workDetail.vue component on mounted, I was using location.href to determine which work detail to serve, hence the trailing slash of the url affected the results. Using this.$route.params.slug as the determining factor is better.

**Comment by datianjiao** [comment]
I have the same problem

**Comment by forzeny** [comment]
I have the same problem
