### ISSUE TITLE
build error in Linux

### ISSUE THREAD

**Issue by wugengsong** [chrisvfritz/prerender-spa-plugin#78]
![image](https://user-images.githubusercontent.com/16631528/27668682-24d64146-5cb5-11e7-9a0e-47ef14f4bb60.png)

**Comment by drewlustro** [comment]
Could you provide an environment `webpack.config.js` and give us some info about what you're trying to do?

**Comment by drewlustro** [comment]
Please create a new issue with that information. Please use the github markdown for `rich formatting`.
