### ISSUE TITLE
It does't work when i set publicPath to a path like this '/code_test/prerender/dist' 

### ISSUE THREAD

**Issue by G-Veigar** [chrisvfritz/prerender-spa-plugin#79]
I use vue-cli, and I set assetsPublicPath(webpack's output.publicPath) from '/' to 'code_test/prerender/dist', so that the html can get static file,like this 'http://localhost/code_test/prerender/dist/static/js/vendor.df5f090b3946811fea8b.js'
But when i do this, It Can not get actual content prerendered, only what's initially in index.html ,
I need help, sorry for my bad english。

**Comment by drewlustro** [comment]
I'm sorry, but it seems like you are using the plugin improperly. There is no reason to nest the `publicPath` like that and continue to test on `localhost`.

Please provide your `webpack.config.js` and more information about your build environment if you think I am mistaken. Thanks!

**Comment by krestaino** [comment]
@G-Veigar mentioned `publicPath` in the title, but I think they mean `assetsPublicPath` as mentioned in the description.

I'm also having issues with setting `assetsPublicPath` to something other than `assetsPublicPath: '/',`.

My use case is hosting a page where the assets live on a CDN. When I set the asset path to the CDN, the page is no longer pre-rendered.

**Comment by Pistil-Studio** [comment]
@G-Veigar Hi, did you find a solution ? i have the same problem. Thx

**Comment by working-slave** [comment]
I got the same issue, whenever I set the publicPath other than '/',  nothing is rendered

**Comment by Pistil-Studio** [comment]
@working-slave try this : https://github.com/chrisvfritz/prerender-spa-plugin/issues/176#issuecomment-402152000

**Comment by hyteraesa** [comment]
@Pistil-Studio 请教下 vue-cli下 vue.config.js设置publicPath:'\'为其他的路径（‘cn’）时 预渲染就会失败，你的#176评论不太理解
