### ISSUE TITLE
at the time of loading vendor.js,i type some value in page,after page loaded,the value i typed disapear.

### ISSUE THREAD

**Issue by Linyan-ma** [chrisvfritz/prerender-spa-plugin#84]
Hi,there.
like the title,i guess, when all js was loaded,the real route will replace the prereder html,so,what i typed is replaced.just a guess.so,anyone can tell me how to solve this situation.

**Comment by drewlustro** [comment]
📝 Please provide your `webpack.config.js`, `package.json`, project structure, and a better explanation of your problem with code examples. We would love to help out, but we cannot without sufficient information about your environment.

Once ready, open another issue. Thanks.
