### ISSUE TITLE
What I have done on the prerendered page disappears after the page resource is loaded

### ISSUE THREAD

**Issue by Linyan-ma** [chrisvfritz/prerender-spa-plugin#85]
I'm using vue.js for a app page,tring prerender-spa-plugin to improve slow clients.
Accroding to the guide, i installed 'phantomjs-prebuilt' and  'prerender-spa-plugin',configure the webpackConfig like this:
 new PrerenderSpaPlugin(
      // (REQUIRED) Absolute path to static root
      path.join(__dirname, '../dist'),
      // (REQUIRED) List of routes to prerender
      ['/','/reg','/pwdfy']
    )

after build,i get a index.html with content.

![prerender2](https://user-images.githubusercontent.com/13390008/28560532-a39eb06a-714d-11e7-9484-6b21b5500877.gif)

Look at the gif picture above,i press ctrl+f5, geting resources from the server.in the resources loading,I typed in something.But after all the resources have been loaded, gone.
why is this?

**Comment by drewlustro** [comment]
I am sorry, but I do not understand your English.

**Comment by Linyan-ma** [comment]
Thank you for your quick reply.sorry,i can't express myself.forget it.%>_<%
