### ISSUE TITLE
AJAX fails

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [chrisvfritz/prerender-spa-plugin#86]
Hi,

i'm using vue-resource in a vue project to get some data on a product detail page. 
When trying to pre-render it, the ajax call fails. 

```
Vue.http.get('http://localhost:8080/ajax/someroute').then((response) => {
  // ajax call was successful
}, (response) => {
  // ajax call failed
  // pre-rendered page goes in here everytime
  this.err = response
})
```

Response:
```
{
  "url":"http://localhost:8080/ajax/someroute",
  "ok":false,
  "status":0,
  "statusText":"",
  "headers":{
    "map":{
      "":[""]
    }
  },
  "body":"",
  "bodyText":""
}
```

Requesting the route /w postman works fine.
Any idea what is happening here?

**Comment by drewlustro** [comment]
This may be a **[CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)** issue. Try the option suggested in #87 by @graddd and tell PhantomJS to run with no web security.

```js
new PrerenderSpaPlugin(
  path.join(__dirname, './public'),
  [ '/' ],
  {
    phantomOptions: '--web-security=false'
  }
)
```

**Comment by drewlustro** [comment]
Any luck @hurradieweltgehtunter ?

**Comment by hurradieweltgehtunter** [comment]
i didn't have the time yet to test. I'll keep you updated. 
Thanks for your help

**Comment by drewlustro** [comment]
no worries!

**Comment by hurradieweltgehtunter** [comment]
ok it's getting the data now. I'm inserting the fetched data via `this.product = response.data` which should update the UI but it doesn't. test console outputs work though - hard coded text or the ajax data.
One time it worked (all ajax data got displayed right), i restarted `npm run build` without changing anything and it didnt work. It seems that any dom manipulations inside my ajax call doesn't get executed (or at least does not affect the UI).
Any thoughts on that? (I hope i explained it understandable. It's quite mysterious for me whats happening here)
