### ISSUE TITLE
Proposal: extend caveats and update description (+ caveats for those using Vue with async ajax)

### ISSUE THREAD

**Issue by graddd** [chrisvfritz/prerender-spa-plugin#87]
## Crawlers
Prerendering has no effect on Google crawlers and [here is proof of it](https://centrical.com/test/google-json-ld-and-javascript-crawling-and-indexing-test.html). It may be outside the scope of technical details of  _prerender-spa-pugin_, but many developers are misled to thinking that they need to prerender their page because of Google crawlers' incapability of "seeing" async content. It probably does help less sophisticated search engines see your content, though.

## Prerendering a Vue app and ajax calls
Here's my experience with meddling with a a single-page Laravel application with vuex, vue-router and axios (calls being done to Laravel API).

It is difficult to implement prerendering in a way in which you could achieve "snappy" behavior of your webpage when page is initially loaded ([behavior as shown in this example](https://vue-snipcart.netlify.com/)). In the example, the Vue instance gets mounted seamlessly onto the prerendered content. However, the demonstrated page has very little plugins (e.g. no ajax calls that would be done on route change) and the initial state is already filled (hardcoded in the store state). If you are fetching ajax data on route change, forget about such snappiness -- when you load the prerendered html file, the initial state will not be filled and the prerendered content will be replaced by the empty state, which will (after the ajax content gets loaded, which is triggered on `mounted`, for example) then be replaced with the fetched content. This basically means that the rendered page text will "blink" on the initial load. Thus doing ajax calls on initial load to replace prerendered content **without having a filled initial state** is a bad idea -- you can try learning that the hard way.

Here are some more caveats that I can share that made this a 3-day thing:
- I experienced problems with html-webpack-plugin, which inserted scripts at the end of the `<body>` tag **twice** (even with `inject: false`), so I ended up using copy-webpack-plugin.
- You need to import polyfill inside your app.js file. Including `import 'es6-promise/all'` got rid of `Error: [vuex] vuex requires a Promise polyfill in this browser.`, but left the source static file with unchanged html. `import 'babel-polyfill/dist/polyfill'` did the trick for me.
- The list of pages that you wish to prerender does not accept parameters such as `:slug`. If you wish to prerender a large portion of pages with different slugs, you need to pass all of them into an array somehow.
- When doing ajax calls, `phantomOptions` must have a value of `--web-security=false` that [enables doing cross-domain XMLHttpRequest](http://phantomjs.org/api/command-line.html) and you have to configure axios to make calls to port 80, otherwise you will get a 404 error. If you set only the port (but not the `web-security` option), you will get a network error.
- When you are using `captureAfterTime` parameter, if you are running a bootstrap carousel or vue-progressbar on your page, the prerendered html will include some surprises, such as half-loaded progress bars or carousel on the second slide (if it is set to auto-play), which will then immediately get replaced by the fresh instance, so it is not really a big problem. But it does have a messy vibe to it.

Many problems occur due to the fact that the `prerender-spa-plugin` uses a [hapi server](https://hapijs.com/api) (which is usually set to port 8000), which utilizes [PhantomJS web page module](http://phantomjs.org/api/webpage/) to make a snapshot of the loaded html of your static files inside `'relative/path/to/static/root'`. 

Here is some of the js that made prerendering and ajax work.
```
// webpack.mix.js, after mix.js(...) or at end of file

if(mix.config.inProduction) {
    mix.webpackConfig({
        plugins: [
            new CopyWebpackPlugin([{
                from: path.join(__dirname, 'resources/views/index.html'),
            }]),
            new PrerenderSpaPlugin(
                path.join(__dirname, './public'),
                [ '/' ],
                {
                    phantomOptions: '--web-security=false',
                    captureAfterTime: 5000
                }
            )
        ]
    });
}
```

```
// api/index.js, when creating an instance of axios

let port = 80;
window.axios = axios.create({
    baseURL: location.protocol + '//' + location.hostname + ':' + port + '/api/', //
    headers: {'X-Requested-With': 'XMLHttpRequest'}
});

// and  in component or action:
window.axios.get('article/123')
```

In the end, I did get it to work, but because prerendering is not that important for SEO, and because it did not contribute to user experience and only lessened it, I resorted to not using it. Proper prerendering (not done with webpage snapshots) could be done with passing data to props in blade files, but that would mean double the work, as you'd have to write Vue components as well as blade templates. [Example of it](https://vuejsdevelopers.com/2017/04/09/vue-laravel-fake-server-side-rendering/) exists as well, but seems equally dissatisfactory. The only proper method seems running Laravel parallel to a Node.js server.

**Comment by drewlustro** [comment]
Wow, thanks for all the detailed feedback!

#### Re: Google Crawlers

Let's assume what you wrote and reference cited is 100% true. `prerender-spa-plugin` has other applications beyond boosting SEO performance. For instance, OpenGraph and social sharing metadata tags must be statically rendered for Facebook + Twitter to expand previews correctly. These may not be async.

#### Re: Async Flash

You can use a custom DOM event to tell `prerender-spa-plugin` when to capture your page content.

#### Re: --web-security=false

Considerations for this are outside the scope of the plugin's implementation, but perhaps you could submit a PR that expands our `README.md` to include your findings?

**Comment by drewlustro** [comment]
Closed due to inactivity.
