### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by xianweics** [chrisvfritz/prerender-spa-plugin#89]
Hi, I used prerender-spa-plugin in my project and tried to run `npm run build` , but it showed error to me.  

![28902001-c68b5654-782e-11e7-83e6-36727f409136](https://user-images.githubusercontent.com/24938102/28911883-9aaf9938-7864-11e7-89b9-31914f383976.png)

My `webpack.conf.js` is
```
var Path = require('path')
var PrerenderSpaPlugin = require('prerender-spa-plugin')
module.exports = {
  // ...
  plugins: [
    new PrerenderSpaPlugin(
      // Absolute path to compiled SPA
      Path.join(__dirname, '../dist'),
      // List of routes to prerender
      [ '/', '/about', '/company' ]
    )
  ]
}
```
Please help me to fix this issue.

**Comment by MisterDeng** [comment]
me too

**Comment by drewlustro** [comment]
@xianweics @MisterDeng 

Could you try running `npm rebuild` ?

`phantomjs-prebuilt` was upgraded during the most recent release bump, and we've noticed that Windows users are experiencing some issue with that.

**Comment by drewlustro** [comment]
Closed due to inactivity. Current version also tested on Windows 10 in #90 .
