### ISSUE TITLE
Proposal: Update engine to node 6.x

### ISSUE THREAD

**Issue by drewlustro** [chrisvfritz/prerender-spa-plugin#91]
**Obvi ES6 is the ubiquitous hotness.**

It would be nice if `prerender-spa-plugin` was written in ES6 without the need for `babel` and all of its face-melting configuration + presets gotchas.

Chris, what do you think about updating the engine for `prerender-spa-plugin` to `node >= 6.0` in order to get [http://node.green/](99% native ES6 support)?

**Comment by chrisvfritz** [comment]
I'm not opposed to it in a major version bump, since it would stop working for anyone using a previous version.
