### ISSUE TITLE
How does the prerender render the data asynchronously obtained

### ISSUE THREAD

**Issue by HunterHan93** [chrisvfritz/prerender-spa-plugin#96]
## When I use the pre render, it renders an empty page, and when I delete the empty page, the pre rendered page is loaded normally. I want to know if the pre render is effective. In addition, how can data be static when a page that needs to be pre rendered needs asynchronous access to data?
Thanks,so much.

**Comment by HunterHan93** [comment]
This is my first time to ask questions here. I really need your help.

**Comment by drewlustro** [comment]
📝 Please provide your `webpack.config.js`, `package.json`, project structure, and a better explanation of your problem with code examples. We would love to help out, but we cannot without sufficient information about your environment.

Once ready, open another issue. Thanks.

**Comment by re2005** [comment]
I use this on my bootstrap:

`        const prePreRenderCalls = () =>
            Promise.all([ HERE GOES YOUR API PROMISES ]);

        const dispatchPreRenderEvent = () => {
            document.dispatchEvent(new CustomEvent('initial-content-loaded'));
        };

        prePreRenderCalls().then(() =>
            setTimeout(() => dispatchPreRenderEvent(), 1)
        );
`
