### ISSUE TITLE
Add scripts **after** prerender?

### ISSUE THREAD

**Issue by cschweda** [chrisvfritz/prerender-spa-plugin#97]
I noticed this crashes when I try to render a page with some inline js scripts just before the closing ```</body>``` tag. For example, if I use the AddThis social media plugin, this will throw an error.

Might a future enhancement be a way to add scripts *after* the prerendering is finished? In other words, add additional ```<script></script>``` tags to each page in the ```/dist``` directory?

**Comment by drewlustro** [comment]
Perhaps you could use the option `postProcessHtml` that accepts a function to do finally processing on the captured HTML.

You could replace the `</body>` tag with `<script src="..."></script></body>`, etc.

**Comment by cschweda** [comment]
Will do. Thanks for the tip!
