### ISSUE TITLE
The content of the generated page does not match the corresponding route

### ISSUE THREAD

**Issue by HunterHan93** [chrisvfritz/prerender-spa-plugin#98]
Sorry, I'm not used to saying those kind words, but thank you for reading my questions. Welcome any help
The questions are as follows：
I want to generate pages corresponding to "/login" routing, but the content of the generated page is "routing" / "content",Here is my configuration about plug-ins：
`new HtmlWebpackPlugin({   
title: 'vtoone',
filename: './index.html',   
template: resolveProj('./components/index.html'),   
chunks: ['routes', 'index'],   
hash: true,   
inject: true   
 }),   
    new PrerenderSpaPlugin(   
      resolveVexe('./pages'),   
      [ '/login' ],   
      {   
      captureAfterTime: 5000,   
      maxAttempts : 10   
      })`.
There are two routes in my project, "/" and "login"".
Also, how do I use the dist/login/index.html file I generated? I've tested that even with this index.html, the system doesn't seem to be using it, and even if it is deleted, the system will work.
Thank you for reading here. Welcome any help

**Comment by drewlustro** [comment]
Please format your question and environment detail with **syntax highlighting + clarity** and I would be happy to help!
