### ISSUE TITLE
prerendered page outputs html before App is mounted (Vue)

### ISSUE THREAD

**Issue by eybarta** [chrisvfritz/prerender-spa-plugin#99]
Hi, thx for all your work.

I've been trying to get your plugin to work with my Vue app,
for now just trying to prerender my index.html file
I'm using:
`
new PrerenderSpaPlugin(path.resolve(__dirname, './dist'),
			[ '/' ],
			{
				captureAfterTime: 10000
			}
		)
`

it outputs an index.html into my /dist/ folder, but it's not pre-rendered >>
still has:
`<div id="app"></div>`
inside body instead of the rendered app..

I thought it didn't wait long enough so I used 10 seconds above as you can see..
still same result, please help me resolve this issue.

thank you

**Comment by eybarta** [comment]
is there anyway to see the output log during the build process for debugging?

**Comment by eybarta** [comment]
it's working, was going crazy for 3 days with this.. and after all the problem was I was importing the plugin before the HtmlWebpackPlugin, changing the order made everything work.. thx

**Comment by drewlustro** [comment]
@eybarta – happy you found the way. What helped you? The example docs here or just brute force will 😆

**Comment by eybarta** [comment]
@drewlustro 
( brute force ;] )
I realized the reason my JS wasn't loading was a mismatch in the publicPath between the HtmlWebpackPlugin and the PrerenderSpaPlugin..
When using **publicPath: '/'** like many examples suggest, my prerender plugin was running my js but my compiled html from HtmlWebpackPlugin was outputing the wrong directories and my live site wasn't finding the js ;-\ (and vice versa if I used publicPath: '/dist/')

What I ended up doing was this:
in webpack config > **publicPath: '/dist/'** (so my site would run normal)
in file > **compile-to-html.js**
changed the path in Server.route() to this:
 ```
Server.route({
          method: 'GET',
          path: '/dist/{param*}',
          handler: {
            directory: {
              path: '.',
              redirectToSlash: true,
              index: true,
              showHidden: true
            }
          }
        })
```
in file > **phantom-page-render.js**
I wanted to use the **captureAfterDocumentEvent** option, and couldn't get it to work
as it was (build kept getting stuck on %95) so I made changes
to **page.open(url, ...){}**:

```
if (options.captureAfterDocumentEvent) {
      page.onCallback = returnResult
      page.includeJs(
        'https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js',
        function() {
          (page.evaluate(function(eventCallback) {
            var $win = $(window);
            $win.on(eventCallback, function() {
                var doctype = new window.XMLSerializer().serializeToString(document.doctype)
                var outerHTML = document.documentElement.outerHTML
                window.callPhantom(doctype + outerHTML);
            })
            setTimeout(function() {
              $win.trigger(eventCallback)
            }, 60000)
          }, options.captureAfterDocumentEvent))
        }
      );
    }
```

Now I just trigger a jquery event on window when ever I know the page is completely ready for prerender. If you have any pointers regarding the publicPath issue, I'm sure there's something else I can do other than changing the plugin code to make it work.. let me know :) thx.

**Comment by drewlustro** [comment]
Very odd! Thanks for documenting. I'll file this under **Question** and close.
